### ISSUE TITLE
Option control renders item list at the wrong location

### ISSUE THREAD

**Issue by WatIsDeze** [okamstudio/godot#1008]
Hey all, been playing around with Godot for a bit now and ran into a problem regarding the option control. When I use a Node2D as the main scene node, the option item list shows up at the top left of the option control. When using a Control as the main scene node, the option item list shows at the top left the game window. (See screenshots).

The following link is a zip file containing my test project: https://app.box.com/s/sc0bobjgufiz5ok1cey6

Excuse me if the following explanation may be a bit sluggish, I am new to github, and would just like to see this bug solved.

What I've basically done is setup a hierachy in my main scene such as this:
Node2D -> "main"
- WindowDialog -> "dialog_mainmenu"
- Button -> "button_startgame"
- Button -> "button_quitgame"
- Optionbox -> "option_difficulty"

After that, I've added code, in the _ready() function of the Node2D -> "main" script, in order to add the items to the option control.

![screen shot 2014-12-19 at 19 19 56](https://cloud.githubusercontent.com/assets/10252874/5515013/fdd37422-8856-11e4-8085-eb7dbd457711.png)
![screen shot 2014-12-20 at 06 46 01](https://cloud.githubusercontent.com/assets/10252874/5515014/fe2c4246-8856-11e4-836b-0563e6888c09.png)

While trying to figure out where the problem lies in C++, I also noticed that with the clean source code, the Tooltip positions incorrectly as well.

![screen shot 2014-12-20 at 16 24 26](https://cloud.githubusercontent.com/assets/10252874/5515308/c1a39df2-8864-11e4-9497-0158c8759021.png)

**Comment by WatIsDeze** [comment]
Any updates on this yet? Haven't been able to figure it out myself yet due to a lack of better knowledge about the C++ code :)

**Comment by reduz** [comment]
i got back to the city some days ago and working on fixing several issues,
will get to this one briefly

**Comment by reduz** [comment]
well, I was almost certain that this surprisingly wasn't a bug but API misuse, but it really was a strange and obscure bug, so congratulations on your find :P

**Comment by reduz** [comment]
It's surprising that no one else found it, but I can see why, as you put a Sprite when everyone else would have used TextureFrame (there is not much of a merit mixing 2D and GUI stuff), I just can't believe this bug was around for so long, so i'm glad you reported it.
