### ISSUE TITLE
Project Settings / General / locale / fallback seems ineffective

### ISSUE THREAD

**Issue by UsernameIsAReservedWord** [okamstudio/godot#1011]
Hi,
I'm still on stable 1.0 version, win64.

Unless I did not understand how to use it, or what it is actually supposed to do, the **locale/fallback** option into the **project settings** seems not to work.

I explain : In case I don't provide a translation for a locale, I want the translator to use the "en" locale instead. So I put "en" into the **fallback** field.

However, it seems not to work. If I run command line for lang that I donot support, Instead of displaying the english translation, it keeps displaying the key ID.

Bug or misunderstanding ?

Edit : indeed the workaround would be to use english translations as keys .....

Edit 2 : oh, and I was using it to translate a Label in which I put a string key name "LIKE_THIS_ID"

**Comment by reduz** [comment]
seeing the code, what fallback does is weird, i think it makes no sense, will change it so it does what you describe

**Comment by reduz** [comment]
please test

**Comment by UsernameIsAReservedWord** [comment]
It works indeed ! thanks !
