### ISSUE TITLE
[suggestion] about 2d tilemap filtering artifacts

### ISSUE THREAD

**Issue by UsernameIsAReservedWord** [okamstudio/godot#1012]
Hi,

Into the tilemap tutorial, it is said that when using a single texture for all the tiles, it will most likely result in filtering artifacts that can't be avoided, unless disabling filtering or using workarounds.

In my previous attempt at writing an opengl tilemap game engine, I solved this problem by adding an inset of about 0.5 pixel to the UV coords of the tiles.
This inset was small ennough to be unoticiable, and allowed the use of filtered texture without artifacts.

I haven't looked deep ennough into Godot source code, so I duno if it is possible or not, and I have not found a conversation about it into the forum, so duno if you tried that already. So, just in case, you have this suggestion ...

**Comment by Zylann** [comment]
+1, I did the same in another attempt for creating a tile map in a game engine, and this method worked for me.

**Comment by UsernameIsAReservedWord** [comment]
well, a simpler workaround is to take this artifact in consideration when creating the texture, by reserving a border of 1 pixels around every tiles into the single texture.

for instance, use 32x32 pixels tiles (including the 1px border) into the single texture, and use a Region Rect of (1,1,30,30) into Godot ...

... and no more artifact.

It is also possible to manually add the offset of 0.5pixels into the Region Rect when creating the tileset into Godot.

so, all in all, I think this suggestion is pointless and should be closed. @Zylann : if you desagree, I'll open it again for you.
