### ISSUE TITLE
minor UI glitch: sampleplayer doesn't show samples after loading library

### ISSUE THREAD

**Issue by adolson** [okamstudio/godot#1016]
if you have a sampleplayer node (or maybe sampleplayer2d, I forget), and you load a library into the samples, the play parameter stays at an integer spinbox. it should be updated to the menu list of samples in the library. currently you have to click away to another node, and back for this to show up correctly. again, this is minor, but there's a UI push for 1.1 so I'm submitting these things I find.

**Comment by reduz** [comment]
i think fixed, test!

**Comment by adolson** [comment]
fixed!
