### ISSUE TITLE
extending code completion

### ISSUE THREAD

**Issue by KellyThomas** [okamstudio/godot#1032]
First of all congratulations on the recent improvements to code completion, it really helps make GDScript shine!

I have noticed a couple of places where improvements may be possible.

1. after typing "`func `" it would be helpful to list any functions belonging to the parent class to assist those times that we want to override.
2. When calling a function with a known parameter type it could suggest  the constructor for that type and local or member variables of that type.
3. Input Action names could be suggested for `input.is_action_pressed()`

As with any interface decisions, opinions will vary, this is just my two cents.

Thank you for all your hard work.

**Comment by reduz** [comment]
oh nice ideas
