### ISSUE TITLE
Error in 3d kinematic_char demo: Index p_shape_idx out of size

### ISSUE THREAD

**Issue by rraallvv** [okamstudio/godot#1051]
The demo runs ok, but the log shows:

	[1;31;40mERROR: create: [1;37;40mCondition ' !create_func ' is true. returned: 0
	[0;31;40m   At: core/os/mutex.cpp:39.[0;0;37m
	opening pack /Users/rraallvv/Desktop/godot-upstream/tools/Godot.app/Contents/MacOS/Godot, -1, -1
	opening pack /Users/rraallvv/Desktop/godot-upstream/tools/Godot.app/Contents/Resources/data.pck, -1, -1
	[1;31;40mERROR: is_shape_set_as_trigger: [1;37;40mIndex p_shape_idx out of size (shapes.size()).
	[0;31;40m   At: scene/3d/collision_object.cpp:322.[0;0;37m
	[1;31;40mERROR: is_shape_set_as_trigger: [1;37;40mIndex p_shape_idx out of size (shapes.size()).
	[0;31;40m   At: scene/3d/collision_object.cpp:322.[0;0;37m
	[1;31;40mERROR: is_shape_set_as_trigger: [1;37;40mIndex p_shape_idx out of size (shapes.size()).
	[0;31;40m   At: scene/3d/collision_object.cpp:322.[0;0;37m
	[1;31;40mERROR: is_shape_set_as_trigger: [1;37;40mIndex p_shape_idx out of size (shapes.size()).
	[0;31;40m   At: scene/3d/collision_object.cpp:322.[0;0;37m
	[1;31;40mERROR: is_shape_set_as_trigger: [1;37;40mIndex p_shape_idx out of size (shapes.size()).
	[0;31;40m   At: scene/3d/collision_object.cpp:322.[0;0;37m
	[1;31;40mERROR: is_shape_set_as_trigger: [1;37;40mIndex p_shape_idx out of size (shapes.size()).
	[0;31;40m   At: scene/3d/collision_object.cpp:322.[0;0;37m
	[1;31;40mERROR: is_shape_set_as_trigger: [1;37;40mIndex p_shape_idx out of size (shapes.size()).
	[0;31;40m   At: scene/3d/collision_object.cpp:322.[0;0;37m
	[1;31;40mERROR: is_shape_set_as_trigger: [1;37;40mIndex p_shape_idx out of size (shapes.size()).
	[0;31;40m   At: scene/3d/collision_object.cpp:322.[0;0;37m
	[1;31;40mERROR: is_shape_set_as_trigger: [1;37;40mIndex p_shape_idx out of size (shapes.size()).

It seems to be triggered when the kinematic character collides with other objects.

**Comment by reduz** [comment]
should be fixed
