### ISSUE TITLE
3d RigidBody has unexpected behaviour when colliding with multiple StaticBodies

### ISSUE THREAD

**Issue by Anarchid** [okamstudio/godot#1067]
It seems that when a RigidBody travelling at rather specific velocity impacts multiple StaticBodies (or other RigidBodies in static mode) at the same time, this allows the colliding object to go into places where it should not be physically able to fit.

In particular, the colliding RB can travel through very tiny slits between two SB's, or through intersections of two SB's collision volumes (with no "air" between them whatsoever).

[Here](https://dl.dropboxusercontent.com/u/19320633/collisionbug.zip)'s an unreduced testcase for the issue. In this game the player controls a character in third or first person mode, and can throw RigidBody cubes by clicking LMB. On the scene exists a set of white cubes with thin slits or intersections, and when the thrown cube is projected to hit the slits or the intersection, it "disappears", sliding through and being ejected on the cube's other side.

Enabling or disabling continous CD, collision monitor, or number of reported collisions doesn't seem to affect the problem.

You can see the intersection which should be shot at here:

![intersection screenie](https://dl.dropboxusercontent.com/u/19320633/godot-intersection.png)

I'll try to add a reduced zero-interaction test case a bit later.

**Comment by reduz** [comment]
fixed! for some reason the CCD code for 3D physics was not there, re-added it. Please test!
