### ISSUE TITLE
[request] add a .set_ord_at(pos,unicode) method to String 

### ISSUE THREAD

**Issue by UsernameIsAReservedWord** [okamstudio/godot#1072]
Hi!

Godot stable 1.0.
I'm trying to set individual character in a string using its unicode value.

    var my_str = "A"

    var ord = my_str.ord_at(0)
    ord += 1
    my_str[0] = ord

The code above generates an _"Invalid set index '0'"_ error.
Is this normal, or is it a bug ?

**edit : corrected the variable name in the example above**

**Comment by reduz** [comment]
just made it so you can assign an integer and it will take it as an unicode value, since the type can be inferred or detected anyway

**Comment by UsernameIsAReservedWord** [comment]
great ! thanks ! I'll test it as soon as possible. (and Happy New Year to you BTW !)

**Comment by UsernameIsAReservedWord** [comment]
I've just tested it. It works indeed ! Thanks !
