### ISSUE TITLE
Importer can not handle some e-values for vertex positions.

### ISSUE THREAD

**Issue by TheoXD** [okamstudio/godot#1073]
Importer can't tolerate low values that are very close to 0, expressed as Euler-values. So for example instead of 0.00001 blender can give 1e-5 if the value is small enough, and some values break, like for example -1.9684875951497816e-10   To reproduce just use this value in any .dae and see how the vertex is going towards infinity.

**Comment by reduz** [comment]
I think i fixed this bug, this is quite interesting. The problem was that GPUs when using half16 totally fuck up with denormals, forcing them to 0 solved the issue.
