### ISSUE TITLE
.git file missing; can't clone

### ISSUE THREAD

**Issue by aaronkuchma** [okamstudio/godot#1086]
I tried cloning the wiki locally so I have offline access to it, but the .git file the page refers to is missing.

https://github.com/okamstudio/godot.wiki.git gets a 404 error.

**Comment by adolson** [comment]
$ git clone https://github.com/okamstudio/godot.wiki.git
Cloning into 'godot.wiki'...
remote: Counting objects: 5424, done.
remote: Total 5424 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (5424/5424), 32.31 MiB | 125.00 KiB/s, done.
Resolving deltas: 100% (3728/3728), done.
Checking connectivity... done.


??

Doesn't seem to be an issue. Please close this.
