### ISSUE TITLE
Crashed in parse_json.

### ISSUE THREAD

**Issue by dbsGen** [okamstudio/godot#1088]
When the json string is empty, it will crash.
A test code.
   
    var h = {}
    h.parse_json("")  # crash
    h.parse_json(" ")  # go fine

**Comment by Murii** [comment]
Here is the fix in dictonary.cpp line 185: 

Error Dictionary::parse_json(const String& p_json) {

	String errstr;
	int errline=0;
	if (p_json != ""){
	Error err = JSON::parse(p_json,*this,errstr,errline);
	if (err!=OK) {
		ERR_EXPLAIN("Error parsing JSON: "+errstr+" at line: "+itos(errline));
		ERR_FAIL_COND_V(err!=OK,err);
		}
	}

	return OK;
}

**Comment by reduz** [comment]
i think this was fixed by the PR

**Comment by dbsGen** [comment]
I think add the check code to JSON::parse is better.
Anyway, thanks a lot.
