### ISSUE TITLE
custom android template showing no export template found 

### ISSUE THREAD

**Issue by sad2santi** [okamstudio/godot#1105]
Compiled and referenced release and debug apk as shown in https://github.com/okamstudio/godot/wiki/compiling_android. But still show "no export templates found. download and install export template". 
![10906476_557834814352370_4106927596500063905_n](https://cloud.githubusercontent.com/assets/10323520/5602737/4c857424-9317-11e4-9b42-b319cf933674.jpg)

**Comment by Murii** [comment]
Have you filled in Settings - Edtitor Settings - Android the spaces ?
![image](https://cloud.githubusercontent.com/assets/7363306/5602757/064f2dc4-936c-11e4-909d-7a80345f8c23.png)

**Comment by okamstudio** [comment]
you need to do all the stuff mentioned there, and also install the export
templates anyway

https://github.com/okamstudio/godot/wiki/export_android

On Sat, Jan 3, 2015 at 12:11 PM, sad2santi <notifications@github.com> wrote:

> COmpiled and referenced release and debug apk as shown in
> https://github.com/okamstudio/godot/wiki/compiling_android. But still
> show "no export templates found. download and install export template".
> [image: 10906476_557834814352370_4106927596500063905_n]
> <https://cloud.githubusercontent.com/assets/10323520/5602737/4c857424-9317-11e4-9b42-b319cf933674.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1105>.
>



-- 

*OkamStudio*

**Comment by sad2santi** [comment]
Ooh.. so even after compiling for android and referencing the corresponding debug and release apk, I have to install the export template provided in http://www.godotengine.org/wp/download/. Or the export template can also be compiled?

**Comment by reduz** [comment]
nope, just install them, your custom one you reference from the android
export settings

**Comment by sad2santi** [comment]
Thanks... now I have understood it. I'm closing the issue.
