### ISSUE TITLE
_draw function called only once!?

### ISSUE THREAD

**Issue by Murii** [okamstudio/godot#1115]
![image](https://cloud.githubusercontent.com/assets/7363306/5606840/928c6894-944b-11e4-9835-238b5dd44c6f.png)

Why this function is called only once!?

**Comment by philiplb** [comment]
Due to performance. Everytime you want something to be redrawn, you have to call update().
See https://github.com/okamstudio/godot/wiki/tutorial_custom_draw_2d

**Comment by Murii** [comment]
I dont think this should behave like this but whatever...

**Comment by reduz** [comment]
https://github.com/okamstudio/godot/wiki/tutorial_custom_draw_2d

Please read above
