### ISSUE TITLE
Switching automatically to dedicated GPU (nvidia Optimus)

### ISSUE THREAD

**Issue by the-mech** [okamstudio/godot#1120]
Hey Guys,

Im using Godot on a Windows Laptop with two GPUs ( integrated cpu one and dedicated nvidia).

My Problem is that when i run a larger scene,
the gpu sucks at framerate,

optimus doesn't switches to the dedicated nvidia gpu,

can someone help me?

**Comment by reduz** [comment]
i have no idea, never seen this kind of hardware

**Comment by raasumy** [comment]
I have similar hardware and I just pointed each card to render it's
separate monitor, so GPU intense stuff is handled on my main screen with
efficient processor. Maybe you should try the same.

**Comment by UsernameIsAReservedWord** [comment]
@the-mech : did you set the Windows performance level to high into the battery/energy management things ?

**Comment by the-mech** [comment]
thx guys, switching manually to the dedicated card works fine..

im just worried about developer who finish their games and publish them via steam or so..

there are many people out there who have a laptop with such a hardware config..

the problem with optimus is that, this f**ker is only possible to switch the card when it detects directx or cuda calls.

thus godot is a opengl engine, games with higher performance will use only the integrated chip and not the dedicated. this could result in frustration of many players, so they could give negative reviews on the game, wich results in a bad selling rate..

i found out that is possible to force the dedicated card but im not sure how to implement it.

http://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/OptimusRenderingPolicies.pdf

the third page explains that exporting an global variable would force optimus to switch the card.

example code:

    extern "C" {
    _declspec(dllexport) DWORD NvOptimusEnablement = 0x00000001;
    }

i hope you guys understand my point :smile:

**Comment by SolarLune** [comment]
I see the point, and I see the concern, but I don't think it's such a huge deal. Most people who purchase a game off of Steam will check around to see why something runs so slowly, and they'll probably get an answer on the forums telling them to force the use of the main, dedicated graphics card. I don't think it's such a huge deal, though automatic switching would be a nice feature to implement eventually.

**Comment by reduz** [comment]
seems easy to add anyway

**Comment by the-mech** [comment]
yeah you're right @reduz 

added the few lines to platform/windows/windows.cpp

and compiled the templates, to use as custom binary.

works perfect! :)

**Comment by reduz** [comment]
pullrequestme that!

**Comment by reduz** [comment]
I assume it's in os_windows.cpp ?

**Comment by the-mech** [comment]
oh, yeah thats the file i've meant

**Comment by PaulArgent** [comment]
Hello!
I have the opposite problem: Godot ignores the forced setting to use the integrated Intel GPU. The Nvidia control panel is configured to force the use of integrated graphics for both the editor itself and for builds. But Godot still uses a discrete Nvidia Optims GPU (RTX 3060 Laptop version) both for the editor and for the build. I'm writing a few non-gaming GUI apps on Godot and I care about power saving over performance. That's why I need integrated graphics by default. Is it possible to make an option to force disable Nvidia Optimus?
