### ISSUE TITLE
Path2D.Curve2D.interpolatef() broken and not linear

### ISSUE THREAD

**Issue by UsernameIsAReservedWord** [okamstudio/godot#1126]
Hi,

The Curve2D::interpolatef() methods was broken.

It was fixed with : #1124 

However, the interpolation seems not to be linear in time (it starts moving slowly, then faster near each the end of each segments).

~~Here is a tiny test case : https://github.com/UsernameIsAReservedWord/godot-test08-path2d~~

**Comment by UsernameIsAReservedWord** [comment]
It appears that this one was solved sometime in the past.

**Comment by UsernameIsAReservedWord** [comment]
My bad, I spoke too fast (the script line exhibiting the bug was commented out into the test case script).

I tested again with latest github version, and the Curve2D::interpolatef() is still "choppy". 

The interpolation "slows down" each time it approach a vertex of the curve.

If i use Curve2D::interpolate_baked() instead, it works like I expected.

The link to the new test-case :
https://github.com/UsernameIsAReservedWord/test---curve2d-interpolatef-bug

**Comment by reduz** [comment]
this is not a bug, this is exactly how bezier interpolation works. It makes
sense that interpolation is not constant for drawing, for example.

If you want to walk along the curve at constant speed, the only way this
really works is by baking it and then use cubic interpolation

**Comment by UsernameIsAReservedWord** [comment]
ok then.
I was wondering what the baking things was for, but now I understand. thanks Reduz !
