### ISSUE TITLE
Implement string interpolation

### ISSUE THREAD

**Issue by Spooner** [okamstudio/godot#1131]
Python supports interpolation, via printf (%) and string.format() - Horrid to use stuff like "fish" + str(my_int) + "frog")

Either option would be fine, but I'd recommend taking a leaf out of Boo, which uses direct interpolation: "fish $(my_int) frog" (which is also similar to how Ruby does it too).

**Comment by reduz** [comment]
I would rather adapt that library instead of using it, so Godot can keep
the no dependency upon C++ standard libraries, using the template types in
Godot

**Comment by Spooner** [comment]
You mean not using std::string at all? fmt::sprintf() and fmt::format() accepts int/float/c_str and I can get that from the Variants and outputs a std::string, but I can convert that into a String before returning them, can't I?

I don't think re-writing printf() and format() are within my willingness to waste time over, I'm afraid ;)

**Comment by okamstudio** [comment]
either that or use a C library

On Wed, Jan 7, 2015 at 11:06 AM, Juan Linietsky <notifications@github.com>
wrote:

> I would rather adapt that library instead of using it, so Godot can keep
> the no dependency upon C++ standard libraries, using the template types in
> Godot
>
>
> On Wed, Jan 7, 2015 at 10:47 AM, Bil Bas <notifications@github.com>
> wrote:
>
> > @okamstudio <https://github.com/okamstudio> I'm giving this a go using
> > https://github.com/cppformat/cppformat to implement python style
> > string.format() method and sprintf (format_string % args_array). Is that
> OK
> > to add to the project? I tried to work out how to leverage standard
> > sprintf(), but I couldn't see a way to use that with an arbitrary array
> of
> > different typed values.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/issues/1131#issuecomment-69023234>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1131#issuecomment-69025468>.
>



-- 

*OkamStudio*

**Comment by reduz** [comment]
The library looks way too complex for what is intended to do and, while the
functionality is desired, it is not worth it for having it as a dependency.

**Comment by Spooner** [comment]
Fair enough - thanks for the responses. I'll maybe look at simpler things to implement then ;)

**Comment by reduz** [comment]
No worries, I'm sure it sounds strange, but keeping engine core small and
efficient is really difficult. Godot has a huge amount of functionality
that needs to be very restrained and to the point, otherwise the engine
binary starts growing easily. This happened with previous versions of the
engine and it was quite a problem. Due to this is that we do so much NIH
programming in the core instead of using other libraries, even the C++
standard library (which produces huge debug binaries due to the high
template complexity).

The situation is different in the editor, which is not as much size
constrained, adding libraries there is fine.

**Comment by Spooner** [comment]
I'm not a fan of NIH in general, but I get your point about bloat (and I loved that I could just clone the repo and compile it on Linux with NO PAIN). I guess there are plenty of printf() sources that could be adapted to use your String class without a huge amount of effort (e.g. http://www.opensource.apple.com/source/shell_cmds/shell_cmds-170/printf/printf.c).

I might change my mind about doing that myself, but I suspect that my time might be better used in adding other things to GDScript (It felt a bit limiting when I tried doing things with it, since I'm used to Python/Boo level of functionality).

**Comment by reduz** [comment]
Allright! And yeah, gdscript is simpler than python mostly for performance
and simplicity, but if there are features missing that don't conflict with
those goals, I don't see why adding them should be a problem

**Comment by Murii** [comment]
I just hate people who complain everytime and do nothing about it.These guys made an entire engine from literarly 0.It`s open source put your head at contribution and add the features u really need.

**Comment by reduz** [comment]
Mury please tone down, no one has done any harm here, what would the point
of making something open source if everyone was expected or forced to
contribute back to use it? Also, how would it be possible to make good
quality software if users could not express their needs? Please treat other
users and developers with more respect.

**Comment by Spooner** [comment]
And reporting bugs and making suggestions and requests IS contribution to the project. Expecting the devs to jump when you ask for something is unreasonable though - either I'll do this or another contributor will or the devs will get around to it in a year or it won't happen.

**Comment by Spooner** [comment]
sprintf seems to cover this OK (and particularly adds the ability to format numbers and strings nicely). Would be nice to have direct interpolation, as in Ruby/Boo, but I think this would require deeper changes to the interpreter.
