### ISSUE TITLE
print() misses space between args

### ISSUE THREAD

**Issue by Spooner** [okamstudio/godot#1132]
In Python, print("x", "y") prints "x y", but in Godot it prints "xy".

Since, if you wanted the latter, you could just use print("x" + "y") or print(str("x", "y")), I think you should revert to the Python standard behaviour. Just different for no good reason.

**Comment by adolson** [comment]
agree

**Comment by UsernameIsAReservedWord** [comment]
disagree

I find more convenient to write :

    print("label : ",value_int," (",value_float,")")

instead of :

    print("label : "+str(value_int)+" ("+str(value_float)+")")

But anyway, it's a minor feature issue, since the only purpose of **print()** is for dev and debug purpose ... if it is changed to the python way, I'll adapt myself.

**Comment by Spooner** [comment]
Well, no, in that case it would be: print("label :", value_int, " ("+str(value_float)+")") since you are forgetting that you can use the added spaces in your example!
