### ISSUE TITLE
duplicating node with only numbers in name got extra space in name

### ISSUE THREAD

**Issue by puppetmaster-** [okamstudio/godot#1161]
![node duplicated_bug](https://cloud.githubusercontent.com/assets/10463138/5687252/1832f640-984b-11e4-80fa-47d0b510a2cc.png)

**Comment by adolson** [comment]
Related to this: It would also be nice if the duplicate function was smart enough to notice if the node being duplicated had an appended number on the name, and if there's no space, to not put one in the copy. For example: "enemy1" -> duplicate -> "enemy2" etc. I can't recall right now if it goes "enemy 2" or "enemy1 2" but I know it puts a space there that I don't want. I don't like spaces in my node names at all.

**Comment by not-surt** [comment]
Also if you like starting your numbering from 0 the next number will be 2.

**Comment by puppetmaster-** [comment]
or make it configurable...
prefix = empty, _ or space

**Comment by adolson** [comment]
I took some time tonight and fixed all of these issues. :) Hopefully reduz will merge as soon as possible.
