### ISSUE TITLE
Not fullscreen on iOS device.

### ISSUE THREAD

**Issue by dbsGen** [okamstudio/godot#1187]
I plan to port my game to iOS. But I am in trouble. 
On iphone the screen size allways 360x480 no matter what device(iPhone5, iPhone6,iPhone6Plus) used.

![screen shot](http://ww2.sinaimg.cn/large/005yyi5Jjw1eo6ro2xpclj30hs0vkjrx.jpg)

**Comment by the-mech** [comment]
have you tried to enable

stretch_mode,
stretch_aspect
and fullscreen

under display in the project settings?

**Comment by dbsGen** [comment]
@the-mech I tried it. I think there is something wrong when compile, because I print the screen size in app_delegate.h -appfinishedLunch. 

I have no idea about what make this. I try to drag all code to xcode and compile it via xcode.

**Comment by punto-** [comment]
Are you using an actual device, or a simulator? What is the actual
resolutions of the devices? What options are you using on engine.cfg? I
can't reproduce on iPad3 or iPad Air.

**Comment by punto-** [comment]
Also, did you put splash images for your phone's resolution on the xcode
project? Sometimes if you don't put the correct splash image it doesn't
report the right screen size to the app (but it's never 460x480 for me)

**Comment by dbsGen** [comment]
@punto-  Great thank you very much. By adding a splash, it work fine for me. 
You make my day. 
Close this issue.
