### ISSUE TITLE
uniform textures are not stored in 3D materialshader resource.

### ISSUE THREAD

**Issue by TheoXD** [okamstudio/godot#1201]
Had this issue before, it got fixed, but now it's back.
Any other uniform property get stored properly, but texture disappear when anything changes or scene reopens. Don't think there is a need for a test project, since I tried in a completely empty project.
This only applies to 3D shaders (not graph).  2D on the other hand works fine.

**Comment by romulox-x** [comment]
I see the same behavior.

**Comment by TheoXD** [comment]
This got fixed earlier, forgot to close...
