### ISSUE TITLE
Build of Jan 13 git doesn't work under Linux

### ISSUE THREAD

**Issue by slapin** [okamstudio/godot#1208]
At least on 869f400179a32e951a44181165de48094693e280 I see the following in editor UI:

![screenshot](http://ossfans.org/godot-bug-editor.png)

Commit 0a6f409323eda5d1ae2c968bbd482c8af1370466 works without problems.

**Comment by slapin** [comment]
OS is Debian with GNOME3, also was confurmed on Ubuntu with Unity.

**Comment by bojidar-bg** [comment]
confimed on ubuntu-gnome 14.10

**Comment by reduz** [comment]
ok found it, will push fix tonight
