### ISSUE TITLE
[Forum] Registration confirmation error

### ISSUE THREAD

**Issue by BeautifulBro** [okamstudio/godot#1209]
The Captcha doesn't seem to be displaying correctly for me on two different computers, neither in Firefox nor Explorer. Unable to read it, I cannot complete registration. What it displays is:

Confirmation of registration

Translate from l33tsp34ak to latin characters: "g4m3 3ng1n3"::
This question is a means of preventing automated form submissions by spambots.

**Comment by reduz** [comment]
http://en.wikipedia.org/wiki/Leet

**Comment by BeautifulBro** [comment]
Doh! Thanks -- sometimes you only see what you expect to see (and don't see what is there)

**Comment by UsernameIsAReservedWord** [comment]
d0 n07 f0r937 70 c1053 7h3 155u3

**Comment by mamarilmanson** [comment]
a normal way of conversation in the Philippines... XD
