### ISSUE TITLE
Some controls on the editor are overlapped by everything else

### ISSUE THREAD

**Issue by rraallvv** [okamstudio/godot#1214]
![screen shot 2015-01-13 at 7 03 41 pm](https://cloud.githubusercontent.com/assets/1840524/5731554/efec83d6-9b56-11e4-97d4-d818503fdb6a.png)

**Comment by reduz** [comment]
yes known bug, push to fix this will be made available in a couple of hours

**Comment by rraallvv** [comment]
I'm closing this.... it was fixed.
