### ISSUE TITLE
shader "use parent" setting not saved

### ISSUE THREAD

**Issue by mookiexl** [okamstudio/godot#1222]
steps to reproduce:
-create a sprite
-add a 2D shader
-uncheck shader/use parent
-save
-reload
-use parent is checked again

**Comment by Nulifier** [comment]
On the latest git build I can't reproduce this. It still says "On" next to the checkbox even when its unchecked so that may be the issue. Also it defaults to unchecked for me.

**Comment by mookiexl** [comment]
Just tried it again with latest build.
It only happens when you quit the editor completely.
If you just use "open scene" in same session it stays off. It stays off even when you use the project manager.

It also seems to only affect "main scene", if I create the sprite in a subscene, it saves correctly.

**Comment by mookiexl** [comment]
Ok, bug seems to be no longer present in current build.
