### ISSUE TITLE
[Issue]  make_dir_recursive in %appdata% not working

### ISSUE THREAD

**Issue by the-mech** [okamstudio/godot#1240]
hey,

i'm using godot on windows 7.

when i try to save some vars into a file,

no folder/file is created in %appdata%.

the console displays:

![image](https://cloud.githubusercontent.com/assets/10233279/5786893/d7f46b9c-9ded-11e4-9251-60f926fb6880.png)

I tried in normal mode and with admin rights..

Has someone else experienced the same and managed to fix that?

**Comment by reduz** [comment]
you mean make_dir_recursive in Directory is not working?

**Comment by the-mech** [comment]
@reduz yeah, exactly. I should stop opening new issues late night, when im overtired :D
