### ISSUE TITLE
Can't ask for autocomplete under mac

### ISSUE THREAD

**Issue by MangelMaxime** [okamstudio/godot#1246]
Hi guys, i just try to use the latest version of godot from github as it solve some mapping problems under mac.

The problems is I can't ask autocomplete by pressing Ctrl + Space.

**Comment by reduz** [comment]
I think someone changed this on mac to shift-space?

**Comment by reduz** [comment]
wait, meta-space

**Comment by MangelMaxime** [comment]
Shift-space did nothing.

But meta-space I can't tell as it's already a default shortcut for using search in mac.

**Comment by MangelMaxime** [comment]
You was right it's Meta+Space ( I change spotlight shortcut).

I close this issue. But it's think, this shortcut should be something else.

**Comment by reduz** [comment]
what is the shortcut in x-code?

**Comment by MangelMaxime** [comment]
It's Ctrl+Space by default.

**Comment by reduz** [comment]
oh i understand the mistake now, will make it ctrl-space for osx

**Comment by MangelMaxime** [comment]
Thanks Reduz.
