### ISSUE TITLE
Weird editor lighting

### ISSUE THREAD

**Issue by LeonardMeagher2** [okamstudio/godot#1274]
![image](https://cloud.githubusercontent.com/assets/1546044/5811072/609f9c64-a005-11e4-800b-78c864a81f3d.png)

Not sure if this has to do with some of the changes to the shading that been going on, but It happens in the build also.

I'm on Ubuntu 14.04 64bit

**Comment by UsernameIsAReservedWord** [comment]
probably related to #1185
