### ISSUE TITLE
[Request] Reload scene button

### ISSUE THREAD

**Issue by Krzycho666** [okamstudio/godot#1278]
While coworking on one sceen using some repos, there is a lack of option to reload current scene. Godot could also derect it automaticaly - then just some popup could appear to ask user if he want to reaload it.
It would save quite a bit of time when pulling some changes from server, cose then you need to close the sceen and open it again using the browser and selecting the correct one from a bunch of stuff.

**Comment by reduz** [comment]
I think this is added now
