### ISSUE TITLE
win64 official releases are not 64bits. They are all 32bits. Scons does not compile 64bits with Mingw64.

### ISSUE THREAD

**Issue by UsernameIsAReservedWord** [okamstudio/godot#1285]
Hi,

Like i have discussed with you on IRC already, none of the official win64 releases (from RC2 to stable1.0) are actual 64bit version. They are all 32bits.

Cross compilation from linux using Mingw64 does not compile to 64bits, because scons uses `i686-w64-mingw32-g++` instead of `x86-64-w64-mingw32-g++`.

## also, for windows users who compile using Visual Studio C++ 2010 express ##

Visual Studio C++ 2010 express does not support 64 bits compilation by default. It will always compile to 32bits without warning whatever `scons bits=64`.
For 64bits support, you need to install extra packages (yahoo it, or duckduckgo it to find it), and when you'll run the the vcvarsall.bat, you'll have to add extra argument : `vcvarsall.bat amd64`.

### under linux or mingw msys terminal :###
Using the ``file myapp.exe` command line.
If it replies `PE32 executable ... 80x86`, then it is 32bits.
If it replies `PE32+ exectabke ...x86-64`, then it is 64bits.

### under windows 7 or 8 64bits: ###
Run the .EXE, then Ctrl+Alt+Delete, then click "Task Manager", look for your .EXE into the Running Applications. If there is a `(32bits)`, then it is 32 bits ... if nothing, then it is 64 bits ..

Other test : right click on you .EXE, click "Properties", then "Compatibility Tab", check the "Compatibility mode" checkbox. If the combo-list contains Windows 95 or 98, it is a 32bits application. Else, it is 64bits.

**Comment by UsernameIsAReservedWord** [comment]
So I've just made some tests to see if I could provide a PR like you requested me to do @reduz.

I replaced all `i686-w64-mingw32-g++` by `x86_64-w64-mingw32-g++` into `platforms/windows/detect.py`.

Cross-compiling `scons p=windows bits=64 target=debug -j 4` works and generates a large godot.exe which is a REAL 64bit application.

Cross-compiling `scons p=windows bits=64 target=release tools=no  -j 4` works too and generates a REAL godot.exe 64bits.

on the other hand,
cross-compiling `scons p=windows bits=64 target=debug_release -j 4` **does not work** because of this error :

    tools/doc/doc_data.cpp: In member function 'void DocData::generate(bool)':
    tools/doc/doc_data.cpp:189:18: error: 'class MethodBind' has no member named 'get_return_type'
          if (m && m->get_return_type()!=StringName())
                      ^
    tools/doc/doc_data.cpp:190:29: error: 'class MethodBind' has no member named 'get_return_type'
           method.return_type=m->get_return_type();
                                 ^
    scons: *** [tools/doc/doc_data.windows.tools.64.o] Error 1
    scons: building terminated because of errors.

This error is not related to the changes I made to `platform/windows/detect.py`, because when I revert it to the original version, I get this error anyway. 
I tested it with today git HEAD.
So, something must be half-broken somewhere else, and I'm not skilled ennough to go further. 
I'm afraid you'll have to go back to Linux yourself, or to install Linux into a Virtualbox (if you have the Intel VT-x or the AMD-v option enabled into your BIOS, you'll be able to setup a multi-core VM that will works as fast as a real Linux install)

**Comment by Krzycho666** [comment]
Thanks. I was sure that it is about something like that. And you're also right about 32bits. I'm going to check if it will compile to release_debug version right now.

**Comment by mrunion** [comment]
I made a quick, cursory look at this. Keep in mind that I've only read the source code via the github web interface, and do not have Godot locally installed, nor tried to compile it.

But it seems that in /core/method_bind.h, the "get_return_types()" method is not defined unless "DEBUG_METHODS_ENABLED" is defined. I have not traced further than this yet, but it would seem that in the failing scons build command above, the "DEBUG_METHODS_ENABLED" is not being defined.

I am continuing to look and see if that's the case......

**Comment by reduz** [comment]
oh this is expected and documented, you must compile with tools=no if you
are compiling release

**Comment by Krzycho666** [comment]
scons p=windows bits=64 target=debug_release -j 4
works fine to me. Just checked it, and ran it.

**Comment by UsernameIsAReservedWord** [comment]
@reduz : yes, but the error i mentionned was with "debug_release", not "release".
I'm going to try again with current HEAD.

@Krzycho666 : thanks for testing and telling me.

**Comment by UsernameIsAReservedWord** [comment]
damn me ... i used "target=debug_release", but it must be "target=release_debug" .... switch the two words  ....

**Comment by Krzycho666** [comment]
It also works after doing the trick with replacing i686-w64-mingw32-g++ by x86_64-w64-mingw32-g++

**Comment by UsernameIsAReservedWord** [comment]
@Krzycho666 : yes it works. Thank you for testing and telling me.
I'm currently testing some minor changes to the `detect.py` script, so it can uses both `i686-w64-mingw32-g++` for 32bits and `x86_64-w64-mingw32-g++` for 64bits compilation, while keeping the possibility to fallback to the older mingw32 which uses `i586-mingw32msvc-g++` ...
... then, if i feel brave ennough, i'll try to compile under windows to see if this "command line too long" issue is solved or not ... 
 
@mrunion : thank you for looking at the source code. But the error was caused beccause I confused "release_debug" with "debug_release" ... Sorry for the false alarm.

**Comment by mrunion** [comment]
@UsernameIsAReservedWord : Yeah, I barked up the wrong tree. Oh well, sometimes you win sometimes you play again later! Glad it's sorted!

**Comment by UsernameIsAReservedWord** [comment]
OK, I've managed to fixe several issue related to this so famous `platform/windows/detect.py` script.

- Mingw64 can cross-compile actual 32bits and 64bits .exe under Linux
- Mingw32 can compile under Windows

TODO :
- make Mingw64 compile under windows too.

I'll be very happy if someone accepted to test it before I push a request.
https://github.com/UsernameIsAReservedWord/godot/blob/master/platform/windows/detect.py

**Comment by UsernameIsAReservedWord** [comment]
in relation with #1298

**Comment by marynate** [comment]
Not sure I fully understand the problem on windows here. 64bit godot always build fine under windows with Mingw64 (https://sourceforge.net/projects/godotengine/files/Builds/official/). Once there's problem with command line too long issue, and I believe I have an old PR for it (https://github.com/okamstudio/godot/pull/360)

**Comment by UsernameIsAReservedWord** [comment]
@marynate : maybe it work well with your version of `platform/windows/detect.py`, but with the version currently available in official godot source code, it contains several bugs :

- mingw64 under Linux cross-compiles fake win64 apps
- mingw under windows, the "command line too long issue" still occurs despite the included workaround, because `ar rc` command lines happen to be longer than the 32KB limit allowed by the workaround (they mentioned it into the comments here : http://www.scons.org/wiki/LongCmdLinesOnWin32 )
- scons seems to add the path to mingw32 into the `env[]` that is passed to the workaround, so if you're trying to compile with Mingw64, scons get confused and call mingw32 gcc tools instead ...


The version I'm working on :
- make mingw64 cross compile actual 64bits exe
- make the install of mingw32 optionnal if mingw64 is already available
- split too longs `ar rc` command lines into several smaller ones

If your script already solves all these problems, PLEASE PLEASE, PR it !

**Comment by UsernameIsAReservedWord** [comment]
@marynate :  i've tested these files that you provides on your sf.net :

http://sourceforge.net/projects/godotengine/files/Builds/official/godot-win64-debug-vs2010-2015-01-21.zip/download
http://sourceforge.net/projects/godotengine/files/Builds/official/godot-win64-debug-mingw-2015-01-18.zip/download

the vs2010 win64 version is not actuall win64 exe. it is a 32bits version.

If you want to know how and why, read the message i wrote to the attentions of Vs2010 users at the top of this page.

On the other hand, the mingw w64 is real w64. So, your mingw64 toolchain seems to works properly.

**Comment by marynate** [comment]
@UsernameIsAReservedWord thanks for the info! You are right, my vs2010 w64 build is indeed 32 bit. It turn out I was always using the wrong kit configuration in QT Creator for the vs2010 w64 build.
