### ISSUE TITLE
Can't import skeleton from .dae file

### ISSUE THREAD

**Issue by MangelMaxime** [okamstudio/godot#1286]
We have a basic 3D animation.

I have the following errors :

```
***ROOT VISUAL SCENE: bras
populating joint Structure001
no rest: Structure001
ERROR: _populate_skeleton: Joint has no rest..
   At: tools/editor/io_plugins/editor_import_collada.cpp:135.
populating joint Structure002
no rest: Structure002
ERROR: _populate_skeleton: Joint has no rest..
   At: tools/editor/io_plugins/editor_import_collada.cpp:135.
populating joint Structure003
no rest: Structure003
ERROR: _populate_skeleton: Joint has no rest..
   At: tools/editor/io_plugins/editor_import_collada.cpp:135.
mesh: Cylindre001
has controller
ERROR: _create_resources: Condition ' skeletons.empty() ' is true. returned: ERR_INVALID_DATA
   At: tools/editor/io_plugins/editor_import_collada.cpp:1527.
ERROR: load: Condition ' err2 ' is true. returned: err2
   At: tools/editor/io_plugins/editor_import_collada.cpp:1671.
ERROR: import_scene: Condition ' err!=OK ' is true. returned: __null
   At: tools/editor/io_plugins/editor_import_collada.cpp:2205.
```

**Comment by reduz** [comment]
if you are using blender exporter, make sure geometry is child of skeleton

**Comment by MangelMaxime** [comment]
My modeler use 3dMax... 
I think we need to be ensure the same thing.

**Comment by MangelMaxime** [comment]
He test it by adding the geometry as a child of skeleton. This time we have the skeleton import ok.

But the mesh aren't import.

Also, 3dsmax is showing error on export as this way appears to be not adapted.

**Comment by okamstudio** [comment]
oh, are you using OpenCollada? or autodesk-collada?


On Wed, Jan 21, 2015 at 1:57 PM, Maxime Mangel <notifications@github.com>
wrote:

> He test it by adding the geometry as a child of skeleton. This time we
> have the skeleton import ok.
>
> But the mesh aren't import.
>
> Also, 3dsmax is showing error on export as this way appears to be not
> adapted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1286#issuecomment-70875191>.
>



-- 

*OkamStudio*

**Comment by reduz** [comment]
https://github.com/KhronosGroup/OpenCOLLADA/wiki/OpenCOLLADA-Tools

**Comment by MangelMaxime** [comment]
We tried with the default 3ds Max exporter. (We are using 3ds Max 2015).

I will try with the OpenCOLLADA tool. It's not yet supporting the morph for 2015 is it a problem or not ?

**Comment by MangelMaxime** [comment]
Some updates here.

I used the OpenCOLLADA tool given by reduz and then follow the link after "Current head of master".
With that I was able to import a skeleton, with meshes and controller.

Now I have to understand how to import several animation ... :)

**Comment by rssqian** [comment]
I meet the same issue.
could you plz,
1) provide OpenCOLLADA tool 
2) tell me what "then follow the link after "Current head of master"" this means, checkout latest master code?

**Comment by akien-mga** [comment]
Check two comments above :)

https://github.com/KhronosGroup/OpenCOLLADA/wiki/OpenCOLLADA-Tools

The "Current head of master" has been renamed and is now just "Click here ->> Latest binaries".

**Comment by rssqian** [comment]
Thanks， I'll try it. :）
