### ISSUE TITLE
Additional UI color options

### ISSUE THREAD

**Issue by CiaraBurkett** [okamstudio/godot#1305]
While obviously not the most pressing issue, it would make sense to add more color options in the Godot UI, or defaulting to a dark gray. I find the purple UI too distracting since it's not a neutral color.

**Comment by NateWardawg** [comment]
Hi Clara, the latest source defaults to a dark skin as of about a week ago :)

**Comment by CiaraBurkett** [comment]
Awesome! Thanks for letting me know.

**Comment by not-surt** [comment]
Now that there are 2D shaders it'd be cool to be able to adjust the editor
UI colours with them.
