### ISSUE TITLE
PolygonPathFinder

### ISSUE THREAD

**Issue by Kermer** [okamstudio/godot#1308]
*SOME NEW FEATURES REQUEST*

Current PolygonPathFinder is poor. It could use some more functions like:
* creating straight from Polygon2D
* creating from TileMap
* creating from objects array (using their shapes or sprites f.e.)
* using shapes to calculate routes
* path offset

At the moment it is only useful when creating route through static, pre-defined environment; while assuming that object moving through this path is of point size (or smaller), unless the path was offseted manually.

Creating any dynamic pathfind usually ends up with strange routes because of badly interpreted connections ( there can't be more than 1 line going through 1 point? ) or overlapping polygons.

I'd say current [polygon_path_finder_demo](https://github.com/okamstudio/godot/tree/master/demos/2d/polygon_path_finder_demo) is the best example of current PolygonPathFinder capabilities :(

**Comment by reduz** [comment]
A new pathfinder has been pushed, making polygonpathfinder kind of obsolete. Check the "navpoly" demo (navigation polygon 2D).
