### ISSUE TITLE
Godot`s source code namaing convention is just wrong!

### ISSUE THREAD

**Issue by Murii** [okamstudio/godot#1318]
Hello,everyone who use Godot know that this is a good pice of software and well made.But since this project is open source many people like me for example would like to know how godot works.So we look into the source code and explore but there is one BIG problem.In Neo engine for example or Maratis the hole engine is well documenteated inside it`s source code.And the names of the variables are easy to understand what they do and why.So since every developer who makes it`s project open source wants to build a community around the project many people would want to add new features to that project.But in this case this can`t be achive since it`s extremly hard to get your head around the spaghetti :).So in the end this is an open source game engine or a "wolf cosumed in a sheep"?

**Comment by not-surt** [comment]
This would be more a whole lot more constructive if you actually said something about what is wrong with the naming convention.
I haven't looked at a lot of the code yet, but haven't had any great difficulties grokking what I have seen. There are a few style matters that aren't to my tastes and spacing is quite inconsistent but they do not hinder readability.

**Comment by Murii** [comment]
Looking is something ,adding features is totally different.I think the main devs will know what I`m talking about.

**Comment by reduz** [comment]
Main devs have no idea what you are talking about.

**Comment by punto-** [comment]
I think everyone understands the need for a coding style, and the
advantages it has to facilitate contributions, but you need to point out
which problems you have specifically with the current one.

**Comment by Murii** [comment]
For example there are not doc like : //this function is suppose to do ...
or most of the vars names inside functions does not describe what is suppose to do.

**Comment by deliciousfudge** [comment]
Like this sort of thing? https://github.com/okamstudio/godot/wiki/class_node

**Comment by Murii** [comment]
Like that but inside the source code if possible and maybe doc the inside of functions too.That would be the best!

**Comment by reduz** [comment]
Comments inside source code just get in the way.  Engine docs should be
enough for you to understand what each class is for. Most experienced
programmers don't really need to read comments to understand sources.

If there is a specific class or piece of code you don't understand, feel
free to ask about it. If there is an algorithm you are finding too complex,
ask for it to be commented.

**Comment by Murii** [comment]
Ok reduz,I'm glad you are such a great person!

**Comment by reduz** [comment]
Magnificent is the word!
