### ISSUE TITLE
Cant pass anything to CanvasItemShader

### ISSUE THREAD

**Issue by Krzycho666** [okamstudio/godot#1323]
Since setting shader's paramiters is only a available in MaterialShader, which can't be attached to CanvasItems, there is no way to pass any variables to shader in 2D - like uniforms. I tried to make a material and then use get_shader(), but returned shader hasn't got any binded values after doing it. I know that it can be done from the inspector, but I need that functionality incode.

**Comment by seadra** [comment]
+1

**Comment by wbasile** [comment]
+1! Be able to get/set shader uniforms from code is very important, and it is already present in the 3D shaders.

**Comment by Krzycho666** [comment]
@jsalem666 just found, that there are two lines missing in canvas_item.cpp ( around line 880 ):

ObjectTypeDB::bind_method(_MD("set_shader_param","param","value"),&CanvasItem::set_shader_param);
ObjectTypeDB::bind_method(_MD("get_shader_param","param"),&CanvasItem::get_shader_param);

**Comment by Krzycho666** [comment]
I'd be very glad for pushing it asap to official master...
