### ISSUE TITLE
yield() crashes with two local variales

### ISSUE THREAD

**Issue by jan-safranek** [okamstudio/godot#1324]
There seems something fishy with `yield()` and local variables. I have the simplest scene, with a button and AnimationPlayer. Animation starts when then button is pressed:

    func _on_Button_pressed():
        var anim = get_node("AnimationPlayer")
        #var foo = 1
        
        anim.play("slide")
        print("started")
        yield(Object(anim), "finished")
        print("finished")

This works as expected, godot prints "started", plays the animation and then prints "finished". Now, when I uncomment `var foo = 1`, it crashes with sigsegv (sorry, no stack trace... all I see is "started" and no "finished").

To me it seems `yield()` does not like more than one local variable. But keeping local variables is the foundantion block of coroutines!

Tested on godot 1.0, win64.

**Comment by reduz** [comment]
I think a bug on it was fixed recently, are you using github version?

**Comment by jan-safranek** [comment]
Nope, are there some nightly builds?

**Comment by Krzycho666** [comment]
the best think you can do, is to build them on your own - it's damn easy and fast. But:
http://sourceforge.net/projects/godotengine/files/Builds/

**Comment by jan-safranek** [comment]
I confirm, godot-win32-debug-vs2010-2015-01-24 from http://sourceforge.net/projects/godotengine/files/Builds/official/ does **not** crash.
