### ISSUE TITLE
A text object that supports italic/bold font + set_visible_characters 

### ISSUE THREAD

**Issue by seadra** [okamstudio/godot#1329]
What I'm trying to do is to slowly show a text (ala CRPG dialogue boxes), increasing the amount of visible characters at a constant speed each time. Label doesn't support italics/bold and RichTextLabel is missing `set_visible_characters`.

Right now, the only viable solution is to use `substr` and send them to RichText's `parse_bbcode` every frame, which doesn't sound efficient.

Will [Label](https://github.com/okamstudio/godot/wiki/class_label) support basic text features such as italic/bold?
Or will [RichTextLabel](https://github.com/okamstudio/godot/wiki/class_richtextlabel) have `set_visible_characters` member function eventually?

Also, with RichTextLabel, is there a way to specify different font files for italic and bold text for use with bbcode?

**Comment by okamstudio** [comment]
you can also load a custom bbcode into it, but make sure to set ther right
fonts in the properties for it to display properly

On Fri, Sep 11, 2015 at 12:20 PM, seadra <notifications@github.com> wrote:

> Closed #1329 <https://github.com/okamstudio/godot/issues/1329>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1329#event-407188649>.
>



-- 

*OkamStudio*

**Comment by seadra** [comment]
Thanks for the tip!
