### ISSUE TITLE
possible division error

### ISSUE THREAD

**Issue by jminix** [okamstudio/godot#1337]
when using division in gd script, i am getting some funky results.

print(19/20) will display 0
print(20/19) will display 1

var test = 19/20
print(test)     same thing

print("test "+str(19/200))  will display  test 0

is this a bug or am I missing something?

**Comment by rraallvv** [comment]
try using float numbers
`print(19.0/20)`
`print(20.0/19)`

**Comment by NateWardawg** [comment]
Yeah, that's pretty common in most other programming languages as well when it comes to multiplication and division. They tend to give you the most accurate data type of the data that you gave it. If you give it all integers it will give you an integer back and just drop the decimal without any rounding. If you give it an integer and a float, it will give you a float back. If you give it an integer and a double it will give you a double, so on and so forth.

Typically you can put it in either the numerator or the denominator, your choice :)

So, this should also work:
print(19/20.0)
print(20/19.0)

**Comment by jminix** [comment]
works great.  I am humbled by such a simple solution.  Thank you
