### ISSUE TITLE
Dict.to_json doesn't deal with non-basic objects

### ISSUE THREAD

**Issue by Spooner** [okamstudio/godot#1349]
to_json works fine for dictionary, string, array, int, real and not well for anything else.

e.g.
built in classes: { "fish": Vector2(1, 2) }.to_json() => { "fish": "1, 2" } (since any class that doesn't have a specific to_json() just uses String() operator).
user defined classes: { "fish": MyClass.new }.to_json() => { "fish": "[Reference:1234]" } (String operator hits again).

Why not have an optional to_json() method called by the Dictionary.to_json() on your own classes, if available, which converts the object into a json data string. e.g.

    class MyClass:
         var name
         var num_chickens
         func to_json():
               return  { "name": name, "num_chickens": num_chickens }.to_json()

Or, to make serialization and deserialization automagic:

    class MyClass:
         var name to_json
         var num_chickens
         func json_fields():
                return ["name", "num_chickens"]

{ "frog": my_class_instance }.to_json() would give: {"frog": { "class": "my_script.MyClass", "name": "my_name", "num_chickens": 12 } }
and Dictionary.from_json() would give you the object again (well, not the same one, but with the same data).

(I'll implement it if you agree to it).

**Comment by Spooner** [comment]
It was pointed out that I can use inst2dict(), but that doesn't recursively operate on objects it references, so doesn't really work (though it would make more sense to just make that operate recursively rather than messing with the systems I've suggested).

**Comment by reduz** [comment]
an easier way to do this might be to inherit from Resource, expose the
properties you want to be saved with export and simply use
ResourceSaver.save()

**Comment by Spooner** [comment]
I did try that method first, but abandoned it for a reason I can't remember now. Think I'll try it again.

**Comment by Spooner** [comment]
Ah, Resources don't like being subclasses when reloaded (they don't have attributes/methods then). Must be main level classes, else they don't work.

**Comment by reduz** [comment]
I'm working on a new serialization framework that should take care of this, but JSON is not and will not be expected to handle non-basic types

**Comment by Spooner** [comment]
OK.
