### ISSUE TITLE
Input. function missing

### ISSUE THREAD

**Issue by OlexiyKravchuk** [okamstudio/godot#1354]
in the class (Input) present functions ...
Input.get_mouse_pos () # returns in the local coordinates of the window
Input.warp_mouse_pos (Vector2 ()) # returns the global coordinates of all display

but there missing ...

Input.set_mouse_pos () # put in the local coordinates of the window
Input.get_global_mouse_pos (Vector2 ()) # takes global coordinates the entire display

**Comment by OlexiyKravchuk** [comment]
more detail the problem described in this topic ... https://www.facebook.com/groups/godotengine/permalink/569698656500066/

**Comment by reduz** [comment]
Fixed in the last push, please test!

Also, this was tested to work on Windows and X11, but not OSX, if you are running OSX please let me know if it works for you.

**Comment by reduz** [comment]
calling warp_mouse() in the respective context will use the coordinates of that context now

**Comment by OlexiyKravchuk** [comment]
Thank you Juan I will look at it as soon as I have the opportunity to experience it personally to give an account here!

**Comment by OlexiyKravchuk** [comment]
I read this topic on Facebook ...
https://www.facebook.com/groups/godotengine/permalink/612451315558133/
In version 1.1 PK2 was deleted Input.get_mouse_pos (), I think this is not worth doing, and it turned out bad, because ...

1) many broken after removal.

2) And I think that if this method caused some questions, in 2D engine (which I have not seen in practice), it simply meant that it was not worth using, but in 3D it is a lot of good parts.

3) an alternative method of finding the position of the cursor, very cumbersome, and instead cause a single line one method, now I have to create a block of code, running processes, or the virtual function _ input, it is not very efficient and redundant.

4) If I need to find out the position, I have to use the function of the input process, but what do I do if I need to use, fixed process function?

**Comment by reduz** [comment]
There is now a direct alternative, use:

get_viewport().get_mouse_pos()

this way mouse pos is always obtained from the right viewport context

**Comment by OlexiyKravchuk** [comment]
Excellent thank you, I'll check it out at the first opportunity!

By the way, in the unit (control) or node (Canvas point) is also added on, along with the functions of "warp mouse ()"?
