### ISSUE TITLE
[feature request] add mouse wheel up/down to button_mask

### ISSUE THREAD

**Issue by UsernameIsAReservedWord** [okamstudio/godot#1357]
Hi,

Given that the mouse wheel is treated as `BUTTON_WHEEL_UP` and `BUTTON_WHEEL_DOWN`, it would be cool if they were also added to the `mouse_button_mask`.

This way, it would be possible to detect mouse wheel actions using `Input.is_mouse_button_pressed(BUTTON_WHEEL_UP/DOWN)`.

**Comment by reduz** [comment]
as far as i know the wheel is simply an instant press/release  event (and sometimes just a press in some OSs), how would it work with that?

**Comment by UsernameIsAReservedWord** [comment]
Would it be possible to inject a fake release event that would be treated during the next frame ?

(I'm not 100% sure, but I think that it was what I was doing directly using the Win32 api few years ago ... but maybe it's even easier with the godot event pump system ?)

**Comment by UsernameIsAReservedWord** [comment]
If someone come by this issue and wonder why it is closed, please, read #1640 to understand why it's not a bug neither a missing feature.
