### ISSUE TITLE
Critical error with ObjectDB

### ISSUE THREAD

**Issue by gokudomatic** [okamstudio/godot#1360]
The last commit b3a6cc097d5bc60ee6e7ba30b177bed3a8aadc71 compiles properly on Xubuntu 14.10 64 but the binary crashes immediately with the following error:
> ERROR: cleanup: ObjectDB Instances still exist!
>    At: core/object.cpp:1715.

**Comment by rraallvv** [comment]
That's weird, that commint has nothing to do with the Linux build, what was the last commit that did work ok?

**Comment by reduz** [comment]
that error needs to be fixed, but if it appears, it's simply that the
application quit

**Comment by gokudomatic** [comment]
I cleaned, removed all files in bin and recompiled. Now it's ok. I'm not sure if I did a mistake, but the error doesn't come anymore.
