### ISSUE TITLE
2d Circular shape bounce not as expected

### ISSUE THREAD

**Issue by jitheeshsk** [okamstudio/godot#1363]
2d circular shape on hitting boundaries with rectangular shape does not work as expected. The ball spins and comes to halt, or at times changes direction randomly,

It would also help if the degrees of freedom can be limited or constrained, like remove angular constraints from a body

![boundary](https://cloud.githubusercontent.com/assets/6497623/6188557/389a3582-b3b8-11e4-9430-0b046c620f60.png)

**Comment by okamstudio** [comment]
I can't figure out much from what you say, care to send a test project?

On Fri, Feb 13, 2015 at 11:11 AM, jitheeshsk <notifications@github.com>
wrote:

> 2d circular shape on hitting boundaries with rectangular shape does not
> work as expected. The ball spins and comes to halt, or at times changes
> direction randomly,
> [image: boundary]
> <https://cloud.githubusercontent.com/assets/6497623/6188557/389a3582-b3b8-11e4-9430-0b046c620f60.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1363>.
>



-- 

*OkamStudio*

**Comment by jitheeshsk** [comment]
Hello the said problem is showed in the below video. Gravity is set as 0
http://youtu.be/hVZrb700mZA

The test project can be downloaded from
https://www.dropbox.com/s/x92tfi2a0irbzya/New%20Game.zip?dl=0

Think something got to do with collision. I'm a noob :)

**Comment by jitheeshsk** [comment]
The issue is fixed in the latest build. Please close this
