### ISSUE TITLE
Android template build fails at navigation_polygon.cpp

### ISSUE THREAD

**Issue by mookiexl** [okamstudio/godot#1364]
Compilation fails with this message:

>In file included from scene\2d\navigation_polygon.cpp:3:0:
core\math/triangulator.h:25:16: fatal error: list: No such file or directory
 #include `<list>`
                ^
compilation terminated.

>=====
scons: *** [scene\2d\navigation_polygon.android.opt.o] Error 1
scons: building terminated because of errors.

Versions before 2D pathfinding compiled and worked correctly.

**Comment by reduz** [comment]
sorry, working on it!

**Comment by mookiexl** [comment]
OK, latest commit fixed it. Thanks.
