### ISSUE TITLE
[request] Key down/up event

### ISSUE THREAD

**Issue by dbsGen** [okamstudio/godot#1365]
It is usefull to make action game or others. 
Now I have to check the key state of the previous frame to make sure that.But it does not work, when someone pressed fast enough.

Edit:

After that, I look into the cpp code. I see I can override MainLoop to get the InputEvent. But I have no idea about how to do that.

**Comment by punto-** [comment]
You can get all input events by calling set_process_input() and adding a
_input(event): method on your node script. The Input class is just a helper
that keeps track of states using those same events. Here are some more
details: https://github.com/okamstudio/godot/wiki/tutorial_input_events

**Comment by dbsGen** [comment]
punto, thanks! It works.
