### ISSUE TITLE
EditorScenePostImport : children nodes added by the script are ignored

### ISSUE THREAD

**Issue by UsernameIsAReservedWord** [okamstudio/godot#1374]
Hi,

I don't know if it is a bug or a missing feature, but it would be cool if `EditorScenePostImport` allowed to insert new children nodes into the scene.

I wanted to create some children nodes from inside the EditorScenePostImport script when importing a collada scene.

When I add AnimationPlayer nodes, or a simple TestCube into the scene, it will not appear into the final scene-tree displayed into the editor.

However if I do a `parent.print_tree()` from inside the post-import script, it will diplay the new child into its tree ... so it's like if new children were removed by a POST-post-import filter .... 

On the other hand, `node.create_convex_collision()` works fine and adds successfully children nodes to MeshInstances nodes.

Is it bug ? Is it related to the "update logic strategies" system which prevent adding new nodes ? is it me ?

here are minimal test-case files : https://github.com/UsernameIsAReservedWord/bug-EditorScenePostImport

**Comment by reduz** [comment]
It's acutally simpler than this. It's common that some nodes create
sub-nodes, like SpinBox (the line edit), MenuButton (PopupMenu),
ScrollContainer and Tree (Scrollbars), etc. And you don't see them in the
editor either. Same thing with the scenes you instance.

The nodes you see in the editor are the nodes owned by the root node of the
scene. If you want to see a node you create there, just set that node as
it's owner:

somenode.set_owner( scene_root_node )

Keep in mind this must be done when the node is a direct child to it in the
same subscene, so you have to add_child() to some children or grandchildren
before doing set_owner()

**Comment by UsernameIsAReservedWord** [comment]
oh great ! now it works indeed ! Thanks @reduz !
