### ISSUE TITLE
sprintf() doesn't halt on error properly

### ISSUE THREAD

**Issue by Spooner** [okamstudio/godot#1393]
The sprintf code, which is accessed via "string % array" (Which I implemented) doesn't halt the interpreter on errors. When a parsing error occurs, such as if there are too many values in the array, it just prints out the error message nicely, then returns an empty string...

Not at all sure what I did wrong...

**Comment by reduz** [comment]
you can make a version of the function that takes an extra parameter for
error, and if implemented with %,
you can pass the error pointer

**Comment by Spooner** [comment]
Ah yes, that makes sense and then I can fail in % code (which fails OK if the two vars are wrong types, so I guess I can fail there instead). I'll take another look at it in the next day or two. Sorry for not thinking of that...
