### ISSUE TITLE
Add OpenGL state cache to avoid performance penalties

### ISSUE THREAD

**Issue by rraallvv** [okamstudio/godot#1412]
Since state changes in OpenGL may quickly degrade performance on mobile platforms, maybe it could be added a state cache in the rasterizer to keep track of those changes

**Comment by reduz** [comment]
This is already there for 3d, but could be improved considerably for 2d

**Comment by rraallvv** [comment]
I was thinking something like

	class GLStateCache {
		static void bindBuffer(GLenum target, GLuint buffer) {
			if (bind_buffer != buffer) {
				glBindBuffer(target, buffer);
				bind_buffer = buffer;
			}
		}
	}

to be used like this

	GLStateCache::bindBuffer(GL_SOME_BUFFER, 0);

instead of just calling 

	glBindBuffer(GL_SOME_BUFFER, 0);

The problem is that the whole game engine would have to be changed to use the cache for those states that are being tracked.

**Comment by reduz** [comment]
this already happens at a higher level:

https://github.com/okamstudio/godot/blob/master/drivers/gles2/rasterizer_gles2.cpp#L6246

**Comment by reduz** [comment]
the renderer works like this:

1) states tracked are material, geometry, lights, skeleton, etc.
2) rendered elements are sorted to minimize state changes
3) render loop only changes state when needed, this is generally small

With GLES3 this can be done a lot more efficient thanks to UBOs and VAOs,
instancing support and the ability to defer rendering.

**Comment by rraallvv** [comment]
I see, the steps you describe mimize the state changes, although there are still a few redundant changes that popped out in the Xcode’s profiler analysis, I’ll try to see whether those changes affect performance somehow, if there is a noticeable effect I’ll post it here.

![screen shot 2015-02-21 at 11 50 21 am](https://cloud.githubusercontent.com/assets/1840524/6314853/0e906e6e-b9c1-11e4-8619-bb07d728fbc3.png)

I’m closing this then.

**Comment by haikarainen** [comment]
@rraallvv I'm considering implementing this in another project, however I'm doubtful about any potential benefits. I have a hunch that redundant OpenGL calls are already optimized away in the driver.

Did you notice any performance increase by tracking state changes?

**Comment by rraallvv** [comment]
@haikarainen, when I did some profiling in my project, Xcode instruments showed redundant OpenGL calls, but I really didn't tried to do a more rigorous test, like for instance adding lots of nodes to a scene to see if there was a noticeable improvement.
