### ISSUE TITLE
StringName/Nodepath works with single quote only

### ISSUE THREAD

**Issue by Spooner** [okamstudio/godot#1417]
The documentation says:
’Hello’, “Hi”	Strings
@"Node/Label"	Node Path or StringName

However, @"whatever" gives an EOL error. @'whatever' does work as expected. Either docs should be fixed or, ideally, @ should not care about the type of quotes used.

**Comment by reduz** [comment]
i think this was fixed a few days ago

**Comment by Spooner** [comment]
Sorry, I should have checked out the latest version before I posted...I'll update and re-check.

**Comment by Spooner** [comment]
Yep. Working fine.
