### ISSUE TITLE
Visual Shader Editor; Certain shaders break on project load.

### ISSUE THREAD

**Issue by Ace-Dragon** [okamstudio/godot#1427]
An example of this is in this file
http://www.mediafire.com/download/ij4zgoaqracxfps/Texture.zip

And this image
![broken_shader](https://cloud.githubusercontent.com/assets/10081256/6336345/98354304-bb67-11e4-8dce-b15272867672.jpg)

---------------------------------------------------------------------------------
Open the file and you'll notice what appears to be a texture mapped to a rectangular object, but here's the thing...

Open the exp_shader file from the resource browser and take a look at the node tree, you will find that originally, it was using the RGB channels of the vertex color data to blend together three textures. However, it seems that this setup only works if you don't exit out of the project after creating, or otherwise you get the broken result as seen when the file is re-opened.

This was verified using a Win64 machine using an ATI 9xxx GPU, using a bleeding edge Feb23 64 big MingW build from the Godot sourceforge page. If this can be fixed, that would be good, thanks.

**Comment by Ace-Dragon** [comment]
So now I did a new approach that omits use of the ramps completely and it works (no shader breaking on load)
![broken_shader working](https://cloud.githubusercontent.com/assets/10081256/6336850/3e514726-bb6b-11e4-9f4b-4d3ad4482f23.jpg)

Still, it looks like there's a genuine issue that concerns shaders making use of ramp converters, otherwise the first setup would work like intended because there's no errors given by Godot itself on the initial creation and because all connections are valid.

**Comment by reduz** [comment]
does this still happen? I am testing it and can't break it

**Comment by reduz** [comment]
any news about this still not working?

**Comment by Ace-Dragon** [comment]
Closing this, this is fixed in the newer builds

**Comment by reduz** [comment]
hooray!
