### ISSUE TITLE
[Request (Visual Shader Editor)]; Add generic mix node with fac. input

### ISSUE THREAD

**Issue by Ace-Dragon** [okamstudio/godot#1428]
I ask because when looking through at the available options for combining textures, it seems like a strange omission to not have the ability to just do a plain mix that can then use a texture or vertex colors as the factor (in a single node at least).

I can see the proposal being done in two ways, you add a fac. input to the color ops. node along with a new 'mix' blending option or you make a separate node type just for plain mixing.

Hope you find it a good idea.

**Comment by reduz** [comment]
there is VectorInterpolate

**Comment by Ace-Dragon** [comment]
So it seems the mix function is there, it's just used in its own node type. That simplifies things a bit.

**Comment by rjungemann** [comment]
There is no "VectorInterpolate" node in the visual node patcher.
