### ISSUE TITLE
"No OcculerPolygon2D on this resource on this node" crash

### ISSUE THREAD

**Issue by Krzycho666** [okamstudio/godot#1463]
After pressing 'ok' on "No OcculerPolygon2D on this resource on this node. Create and assign one?", the godot crashes. It works fine if a new Occuler made on my own.

**Comment by reduz** [comment]
weird.. where did you test this?

**Comment by Krzycho666** [comment]
Ubuntu 14.04, from current version (440cc5e4b6)

**Comment by reduz** [comment]
does this still happen? i can't reproduce

**Comment by reduz** [comment]
assume working
