### ISSUE TITLE
swapped coords in 2d light normal mapping

### ISSUE THREAD

**Issue by Krzycho666** [okamstudio/godot#1467]
It seems to me, that y coord is swapped with -y and vice versa in 2d lighting normals. Correct me if I'm wrong please.

**Comment by reduz** [comment]
yeah, using regular normal maps that are meant for 3D you have to do:

NORMAL = tex(normaltex,UV) * vec3(2,-2,1) + vec3(1,-1,0);

because in 2D the Y is flipped, will hopefully make a tutorial with this
soon

**Comment by Krzycho666** [comment]
Well.... it's correct after transforming normals as suggested ;) But it's quite annoying when working with node based shaders. Shouldn't it be transformed default already?

**Comment by okamstudio** [comment]
maybe the best would be to do like the 3D shaders and just add another
output NORMALMAP that does the conversion..


On Mon, Mar 2, 2015 at 2:13 PM, Krzycho666 <notifications@github.com> wrote:

> Well.... it's correct after transforming normals as suggested ;) But it's
> quite annoying when working with node based shaders. Shouldn't it be
> transformed default already?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1467#issuecomment-76754031>.
>



-- 

*OkamStudio*

**Comment by reduz** [comment]
node based shaders now have a NormalMap output
