### ISSUE TITLE
2D light direction / normals problem (?)

### ISSUE THREAD

**Issue by Krzycho666** [okamstudio/godot#1468]
It seems like 2d light has some direction or something, but there is no way to control it. The light texture is displayed only in the half in some direction. Are normals wrong interpreted or something? Because there is no such problem when disabling normal texture. It looks, like normals is problem here.

**Comment by Krzycho666** [comment]
This is what I got for distance 10000
![scrn1](https://cloud.githubusercontent.com/assets/6615905/6454260/cd173a10-c147-11e4-8095-bb39e6b9446c.png),
and for distance 0
![scrn2](https://cloud.githubusercontent.com/assets/6615905/6454267/e0c74e6a-c147-11e4-93c3-c7cadfe260a9.png)

It doesn't work as it should to me, or I don't understand how you designed it.

**Comment by reduz** [comment]
normals are still not final.. will continue working on them during the week

**Comment by reduz** [comment]
this should be fixed by now

**Comment by unfa** [comment]
I still have this issue. Linux 64-bit, Godot 2.0 stable.
