### ISSUE TITLE
Camera moving while moving node

### ISSUE THREAD

**Issue by Krzycho666** [okamstudio/godot#1469]
It's pretty annoying, when moving an object around the working area in editor, because camera slides with mouse when the object is near viewport border. It's almost impossible to set objects position exactly when you want to. Please let user to decide whenever he wants to move camera or not.

**Comment by reduz** [comment]
ah thanks for reporting this, I always want to fix it and forget about it

**Comment by Krzycho666** [comment]
It seems to be fixed. Thanks ;)
