### ISSUE TITLE
Set PolygonOcculer2d same as drawn polygon

### ISSUE THREAD

**Issue by Krzycho666** [okamstudio/godot#1470]
There is no option to set the PolygonOcculer2d geometry exactly the same as drawn Polygon2D. Of course there is an option to set material to PolygonOcculer2d, so there should be no reason to use Polygon2d anymore, but there is a Texture in Polygon2d, which is easier and faster in use. It should be unified somehow here, because is almost the same, but it works in a different way.

**Comment by reduz** [comment]
this makes sense, added to the 1.2 rewrite plan spreadsheet
