### ISSUE TITLE
No way to move camera in editor

### ISSUE THREAD

**Issue by Krzycho666** [okamstudio/godot#1471]
There is no way to move camera in editor when no scrollbars are displayed ( when there is no object out of the current view area ). It is very usefull to center the viewport while editing stuff - the GL space is "infinite", and the scrollbars just limit it much.

**Comment by tonymtbird** [comment]
if you select a node you can go to view (in the editor) and either center selection, or frame selection.

**Comment by Krzycho666** [comment]
fixed
