### ISSUE TITLE
Godot Windows-Binaries don't run on WinXP

### ISSUE THREAD

**Issue by theuserbl** [okamstudio/godot#1483]
As I have seen in an Virtual Machine with XP, the Godot Windows binaries don't run there. On Windows 7 and up they do.
The support of WinXP ends on April 2014, but I think, there are still a lot of XP-machines out there, so it would be make sense to support them with Godot.

**Comment by reduz** [comment]
There are no plans to support XP, Godot uses a lot of Vista+ APIs that make
life much easier.

**Comment by theuserbl** [comment]
Hmmm... isn't one of the goals of Godot to run on most platforms as possible? And to run in the future on Windows, Linux, MacOSX, PlayStation 4, XBox One, Nintendo Wii, Smartphones, etc?
And Windows XP have still a market share of ca 20%
http://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0

That is the reason, why Godot have - like the Java platform - a small platformdependent part and a big platformindependent part (like the Godot Editor).

> Godot uses a lot of Vista+ APIs that make life much easier.
And supporting only ONE platform would make the life MORE easier (for the developer, who creates Godot. Not for the people who using it).

Btw. Runs Godot additional NOT on Windows 10 Preview in VirtualBox. But it runs on Linux and Windows7 on real Hardware.
So Godot don't like WinXP and (don't like to be in a Virtual Machine or running on Win10).

**Comment by reduz** [comment]
Nope it's not a goal. The goal of the main development trunk is to run it
on the platforms that matter. If anyone else wants to contribute support,
it's welcome but it's not the aim of the developers because it's too much
work to do that.

**Comment by GungnirInd** [comment]
On a side node, Godot runs fine on Win10 natively (both official builds and master cross-compiled on Linux), it just really doesn't like the virtualized graphics that VirtualBox uses, from what I can tell.

**Comment by seadra** [comment]
Is this issue even serious?
Windows XP is officially declared by dead Microsoft. It is just going fade into history. So let it fade into history.

**Comment by Ace-Dragon** [comment]
I agree with those who say Windows XP isn't worth supporting anymore, most of the commercial software that's out there no longer support it and even Blender will no longer run on it (and it's an application that doesn't actually need a new machine to use).

**Comment by jultan** [comment]
Please, let WinXP rest in peace !!!  ;-P

**Comment by reduz** [comment]
Closing this, WindowsXP will not be supported, sorry. No one should use Windows XP.
