### ISSUE TITLE
Array comparison is not working as expected

### ISSUE THREAD

**Issue by akien-mga** [okamstudio/godot#1485]
There seems to be something wrong with array comparison in GDScript, as shown by this example:
```
var test = [1, 2]
var test2 = test
print(test == test)
print(test == test2)
print(test == [1, 2])
```
The output is:
```
True
False
False
```
when all tests should be true.

**Comment by akien-mga** [comment]
This issue affects both 1.0-stable and the current master branch.

**Comment by seadra** [comment]
This is probably how it is supposed to be, assuming that arrays are reference values.
To compare the *contents* of two arrays, you would need a loop.

**Comment by akien-mga** [comment]
On IRC @reduz pointed me to https://github.com/okamstudio/godot/blob/master/core/variant_op.cpp#L281 which seems to indicate that the equality test would compare the contents of the arrays using a loop. But for some reason it does not work as expected.

**Comment by punto-** [comment]
At least the second test should be true I think, if they're both the same
object..

**Comment by reduz** [comment]
fixed

**Comment by rokasv** [comment]
I want the results of the array comparison in the original post, since the comparison is between the array references rather than the values.

How do I compare the arrays to get the "broken" original results?
