### ISSUE TITLE
pass giving ; or <NewLine> required errors at end of file

### ISSUE THREAD

**Issue by WatIsDeze** [okamstudio/godot#1488]
When putting the following code in a script, at the end of a file without an empty newline give the following parser error:

error(line, 1)Expected ';' or <NewLine>.

```
func _do_something():
	pass
```
Replacing the pass with a return, or adding a new line after pass solved the problem. I inquired in IRC, and I recon this to be a parsing bug.

Running OsX 10.9.5, and using the latest git code (at the date of writing this).

Screenshot attached to see the problem at hand with my current script.
![screen shot 2015-03-08 at 11 38 20](https://cloud.githubusercontent.com/assets/10252874/6545439/bf8830b8-c587-11e4-9378-849a65bb93af.png)

**Comment by silverkorn** [comment]
I haven't tried much of GDScript yet but isn't it supposed to have an empty new line to close each function/extends/statement definitions?

You can look at some of the demos' `.gd` files which all seems to have these empty lines.

I guess `return` works because it exit immediately the context you were at without continuing to parse, this might be why it "solved" the problem.

**Comment by WatIsDeze** [comment]
GDScript, to my knowledge, does not enforce newlines at the end of a file. You are correct that however, new lines usually are being used at the end of files.

As for the pass, it exits the same context, because the context is the function in this case. What is however going on, is probably a minor parsing issue in the GDScript parser.

**Comment by silverkorn** [comment]
> GDScript, to my knowledge, does not enforce newlines at the end of a file. You are correct that however, new lines usually are being used at the end of files.

Most of the demos have 2 new lines at their end of file.
But you're right, this one does not end with any new line (though it ends with a comment, I wonder if you try this if it works, maybe there's a correlation there with the parsing bug): 
https://github.com/okamstudio/godot/blob/master/demos/3d/kinematic_char/cubio.gd

**Comment by WatIsDeze** [comment]
That file has the same problem to be precise, it fails to edit and/or run properly, same error as shown in the issue.

**Comment by silverkorn** [comment]
I guess @reduz / @okamstudio will give it a look when possible.
