### ISSUE TITLE
Godot can no longer compile since latest commit 09489e3

### ISSUE THREAD

**Issue by theuserbl** [okamstudio/godot#1492]
The errors are all in scene/2d/tile_map.cpp:

scene/2d/tile_map.cpp: In member function 'void TileMap::_update_dirty_quadrants()':
scene/2d/tile_map.cpp:398:56: error: no matching function for call to 'TileMap::_fix_cell_transform(Matrix32&, TileMap::Cell&, Vector2, Size2&)'
      _fix_cell_transform(xform,c,shape_ofs+center_ofs,s);
                                                        ^
scene/2d/tile_map.cpp:398:56: note: candidate is:
scene/2d/tile_map.cpp:218:6: note: void TileMap::_fix_cell_transform(Matrix32&, const TileMap::Cell&, Vector2&, const Size2&)
 void TileMap::_fix_cell_transform(Matrix32& xform,const Cell& c,Vector2& offset,const Size2 &sc) {
      ^
scene/2d/tile_map.cpp:218:6: note:   no known conversion for argument 3 from 'Vector2' to 'Vector2&'
scene/2d/tile_map.cpp:411:55: error: no matching function for call to 'TileMap::_fix_cell_transform(Matrix32&, TileMap::Cell&, Vector2, Size2&)'
     _fix_cell_transform(xform,c,npoly_ofs+center_ofs,s);
                                                       ^
scene/2d/tile_map.cpp:411:55: note: candidate is:
scene/2d/tile_map.cpp:218:6: note: void TileMap::_fix_cell_transform(Matrix32&, const TileMap::Cell&, Vector2&, const Size2&)
 void TileMap::_fix_cell_transform(Matrix32& xform,const Cell& c,Vector2& offset,const Size2 &sc) {
      ^
scene/2d/tile_map.cpp:218:6: note:   no known conversion for argument 3 from 'Vector2' to 'Vector2&'
scene/2d/tile_map.cpp:428:58: error: no matching function for call to 'TileMap::_fix_cell_transform(Matrix32&, TileMap::Cell&, Vector2, Size2&)'
     _fix_cell_transform(xform,c,occluder_ofs+center_ofs,s);
                                                          ^
scene/2d/tile_map.cpp:428:58: note: candidate is:
scene/2d/tile_map.cpp:218:6: note: void TileMap::_fix_cell_transform(Matrix32&, const TileMap::Cell&, Vector2&, const Size2&)
 void TileMap::_fix_cell_transform(Matrix32& xform,const Cell& c,Vector2& offset,const Size2 &sc) {
      ^
scene/2d/tile_map.cpp:218:6: note:   no known conversion for argument 3 from 'Vector2' to 'Vector2&'
scons: *** [scene/2d/tile_map.x11.tools.64.o] Error 1
scons: building terminated because of errors.

Btw: If you are interested in the warnings, too, then I can post them, too. If you want.

**Comment by marynate** [comment]
Fixed: https://github.com/okamstudio/godot/pull/1491
