### ISSUE TITLE
Gradients rendeirng off on Os X 10.9.5 with Ati Radeon HD5750 1gb.

### ISSUE THREAD

**Issue by WatIsDeze** [okamstudio/godot#1497]
I'm curious if anyone else has the same problem, it is probably driver related but a nasty one nonetheless.

A while ago with the 1.0 stable release I was noticing a similar problem with the button controls, so it has been around for a long time it seems. Although certainly Os X/driver specific in my opinion. Here are some example screenshots of how this affects the light demo:

![screen shot 2015-03-10 at 12 59 32](https://cloud.githubusercontent.com/assets/10252874/6575481/6824e5ce-c72f-11e4-9473-402001ff0f64.png)
![screen shot 2015-03-10 at 13 00 23](https://cloud.githubusercontent.com/assets/10252874/6575480/68230b3c-c72f-11e4-874f-5c9c70f7f1da.png)

**Comment by reduz** [comment]
i think this is fixed
