### ISSUE TITLE
Multiple Area nodes with gravity bug

### ISSUE THREAD

**Issue by soloparatolos** [okamstudio/godot#1498]
Only one Area node with gravity works at the same time. Priority seems to make nothing.

**Comment by soloparatolos** [comment]
Inacurate:

 It seems there is a bug in area(3d), when changing area gravity and set 'gravity point', the center gravity point is always on the scene origin.

-kubecz3k

**Comment by kubecz3k** [comment]
yea, here is a link to the new issue: https://github.com/okamstudio/godot/issues/1507
