### ISSUE TITLE
Script Editor Not Showing Non-English Characters

### ISSUE THREAD

**Issue by Eltii** [okamstudio/godot#1506]
If you type any non English characters they do not show up ( exp : Arabic )
theres nothing to do with Arabic in the script editor BUT the problem is compiling gives u an error that doesnt give u any clue about some other language characters ...

**Comment by mohaalak** [comment]
change the default font of editor . in wiki there is a link to shiw how.
but RTL languages is not supported so there is no much use it shows the
characters but they are nit in a correct way. سلام  will shows  س ل ا م . I
am currently working on this issue.

**Comment by Eltii** [comment]
oh ok thanks :D
its good enough for now that it shows ي ا س ي ن or م ح م د ill change the font
just that once i entered some Arabic letters by mistake and i kept getting an error it took me a while to discover that theres some Arabic characters right there by using another editor .

**Comment by mohaalak** [comment]
for more info see this #982 
please close this issue for now
