### ISSUE TITLE
3DArea gravity point is related to absolute (0,0,0) point

### ISSUE THREAD

**Issue by kubecz3k** [okamstudio/godot#1507]
When creating area with it's own gravity, and checking 'Gravity Point', the origin of gravity is always set to absolute 0,0,0 point. 
Here is minimal sample project illustrating this bug: 
https://dl.dropboxusercontent.com/u/168251/godot/some/issues/gravity_point.7z

**Comment by bojidar-bg** [comment]
That's because your Gravity Vector is (0,0,0) I guess :smile:

**Comment by kubecz3k** [comment]
Gravity Vector is (0,-1,0), and it defines the direction of the gravity not the gravity point...

**Comment by bojidar-bg** [comment]
It is the direction only if "Gravity Point" is unchecked... Otherwise it is the point to which things are attracted. Try changing it to something like (100,0,0) to see this :smile:

**Comment by kubecz3k** [comment]
Oh I guess this one makes sense! Thanks! :)
