### ISSUE TITLE
No sound in GNU/Linux distributions that use *just* ALSA

### ISSUE THREAD

**Issue by shackra** [okamstudio/godot#1511]
I opened one of my projects to check something, and I noticed that the game background music wasn't audible anymore. When I had Pulseaudio, the music and sound were played without problem, but now that I get rid of it, I cannot hear anything.

I compiled Godot from the source code hosted here in Github two days ago.

**Comment by shimpe** [comment]
not a solution to your problem, but perhaps interesting to know: official godot for me requires jack to get audio

with source code builds from github i can use pulseaudio (i haven't checked if jack is also still supported)

**Comment by shackra** [comment]
> or annoy Juan and Ariel to fix what is not working for you.

Psss, @reduz and @punto- !

**Comment by shackra** [comment]
thank you!

**Comment by reduz** [comment]
please test though

**Comment by shackra** [comment]
did the test, there is no sound! D:

However, I saw Godot detecting that in my machine there's no Pulseaudio and switched to ALSA.

But again, no sound D:

**Comment by reduz** [comment]
if it said that, it means the alsa driver initialized correctly.. there
must be a different reason why audio is not being heard... may be related
to your setup?

**Comment by shackra** [comment]
> may be related to your setup?

I can hear my music with Clementine and videos from the web browser without problem!

**Comment by reduz** [comment]
may be related to your setup.. try doing this:

sudo fuser -fk /dev/snd/pcm*

then run godot and let me know if there is audio

**Comment by shackra** [comment]
Nop. Still no music!

To be sure, I played the song with smplayer, everything works fine. Despite the switch, Godot emits no sound :(

**Comment by UsernameIsAReservedWord** [comment]
No offense to you Shackra, but your OS looks quite special.

When mainstream Linux distro rely on full Desktop manager, you uses a tiling window manager that poses you problem with Godot.
When mainstream Linux distro rely on Pulseaudio that was working fine with Godot, you remove it to find out you have no more sound with Godot.

What is this Linux distro that you use and that goes backward in time instead of evolving ?
And what does it at that is so special that we should favor it in spite of mainstream Linux distro ?

**Comment by Calinou** [comment]
> What is this Linux distro that you use and that goes backward in time instead of evolving ?

Software monocultures are never a good thing. This isn't Windows.

**Comment by reduz** [comment]
I think his problem is more like ALSA' s fault.  ALSA has always been an
enormous and bloated piece of shit. A terrible example of overdesign . I
say this as audio developer (worked making audio apps and devices using
embedded linux for some years), it's just bad.

**Comment by shackra** [comment]
@UsernameIsAReservedWord sure, I use [Parabola GNU/Linux-libre](http://www.parabola.nu/https/), I can install and remove anything I want from it according to my particular needs. Parabola removes proprietary software from Arch Linux, a *mainstream GNU/Linux distro* that do not ship ALSA, Pulseaudio, or both, by default.

I removed Pulseaudio because it was failing once every hour while playing movies, forcing me to close the application, open it again and play the movie where it was left before the error.

@reduz how can I help you debugging Godot with that piece of shit? feel free to put more debug output in Godot and I'll report it back to you after testing!

**Comment by UsernameIsAReservedWord** [comment]
@shackra : well, Pulseaudio was probably not configured properly if it posed that much problems. It usually works well with most other distro.

I've looked at https://github.com/thestk/rtaudio and found they have made some little updates to their code relating to ALSA. Maybe it would worth a try to compile Godot with those updated Rtaudio files and see if it improves or solve your audio problems ?

**Comment by shackra** [comment]
re-open, pls!

**Comment by shackra** [comment]
> Ok, will do a round of some weeks of bugfixing. Please update your favorite issues so they are easier to find on github! Add a comment or create new ones if not there.

Well :)

**Comment by reduz** [comment]
I wish i could do much about this, but I honestly have no idea why alsa
fails for you. Alsa-only backend seems to work fine for me if I try.
It seems it has to do with your configuration but I have no way to tell

**Comment by shackra** [comment]
Well... I don't have anything fancy for ALSA regarding it's configuration, I use the stock default
configuration.

Juan Linietsky writes:

> I wish i could do much about this, but I honestly have no idea why alsa
> fails for you. Alsa-only backend seems to work fine for me if I try.
> It seems it has to do with your configuration but I have no way to tell
>
>
> On Wed, Jul 22, 2015 at 4:59 PM, Jorge Araya Navarro <
> notifications@github.com> wrote:
>
>> Ok, will do a round of some weeks of bugfixing. Please update your
>> favorite issues so they are easier to find on github! Add a comment or
>> create new ones if not there.
>>
>> Well :)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/okamstudio/godot/issues/1511#issuecomment-123845942>.
>>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/okamstudio/godot/issues/1511#issuecomment-123846839

-- 
Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by ronchaine** [comment]
It is not just him, I run Arch without pulse (since it doesn't play nice with my sound card), and there is no audio with ALSA.  fuser /dev/snd/* shows godot process there, but no audio.  I don't know how to debug further, though.

**Comment by ronchaine** [comment]
Actually, I think I can hear continuous faint static.

**Comment by reduz** [comment]
Alsa without Pulse works for me, so there isn't much I can do. How about
you try the following:

fuser -fk /dev/snd/pcm*

to make sure nothing is using the audio device

then try running Godot?

Does it work this way?

**Comment by ronchaine** [comment]
Nope, I ran it through an equalizer and it didn't show any signal either.  I can try to debug this myself, no guarantees I find anything though, I usually try to avoid ALSA API like a plague.

**Comment by ronchaine** [comment]
Ok, this works both ways.  Loading pulse after forcing alsa to fail also leads to pulse loading but outputting no audio.  I have no idea where to continue looking.

**Comment by OvermindDL1** [comment]
Have you checked the sampling is right from alsa to the hardware, sometimes it has been a bit off for me causing issues.  I went pulseaudio a year back with no issues since so I cannot test easily at the moment to see if I could replicate it again.
