### ISSUE TITLE
Cutout-Animation wiki page displays incorrect image for the section "Batch Setting Transition Curves"

### ISSUE THREAD

**Issue by jgcoded** [okamstudio/godot#1513]
The image displayed here:
https://github.com/okamstudio/godot/wiki/Cutout-Animation#batch-setting-transition-curves

is the same image displayed in the section right above it:
https://github.com/okamstudio/godot/wiki/Cutout-Animation#moving-sprites-above-and-behind-others

I believe the image in the Batch Setting Transition Curves was mixed up.

**Comment by reduz** [comment]
fixed
