### ISSUE TITLE
Screen capture upside down

### ISSUE THREAD

**Issue by jotson** [okamstudio/godot#1529]
The PNG file saved with the following code is saved upside down (vertically flipped). Also the alpha in shadows appears to be saved incorrectly.

```GDScript
var capture = get_viewport().get_screen_capture()
if !capture.empty():
	capture.save_png("screenshot.png")
```

Here's how the scene looks on my screen while the game is running. This is correct:

![Actual game screen](https://dl.dropboxusercontent.com/u/7063628/godot-screencap/screenshot-actual.png)

Here's an example image using the code above. The lowest layer in the scene is the water and ground which are 100% opaque. The alpha from the shadows in this screenshot are not blending correctly with the lower layers in the scene. You can see the transparency problem better if you download the PNG and view it in an image editing program.

![Sample RGBA PNG](https://dl.dropboxusercontent.com/u/7063628/godot-screencap/screenshot-rgba.png)

I can fix the alpha so that it is correctly blended by changing the code but it is still flipped:

`capture.converted(Image.FORMAT_RGB).save_png("screenshot.png")`

![Sample RGB PNG](https://dl.dropboxusercontent.com/u/7063628/godot-screencap/screenshot-rgb.png)

**Comment by jotson** [comment]
A line that flipped the screen capture was commented out in abbea4d945bbb1114570c3b6c7f649e01ca8ebb8 `RasterizerGLES2::capture_viewport()`:

`//r_capture->flip_y();`

If I uncomment that line, screen captures come out the right way for me. I don't understand enough why that was commented to feel confident making a pull request.

**Comment by reduz** [comment]
This is kinda stupid, but it's incompatibility between desktop gl and
mobile gl. Just needs an ifdef i think

**Comment by jotson** [comment]
Just discovered that this only happens when `stretch_mode = viewport`. The problem does not happen when `stretch_mode = 2d` so I'm using that now instead. May be related to #1571 .

**Comment by reduz** [comment]
this is getting weirder and weirder then...

**Comment by ZodmanPerth** [comment]
I'm still getting this issue on 3.5.1.  I'm targeting GLES3.  Changing the stretch mode does nothing; the saved image is flipped in Y.

I'm working around the issue with:
```
var data = texture.get_data()
data.flip_y()
```

It would be much nicer for everyone if someone would put in that `ifdef`...

**Comment by ZodmanPerth** [comment]
Good to know, thanks.
