### ISSUE TITLE
RakNet Integration

### ISSUE THREAD

**Issue by vkbsb** [okamstudio/godot#1532]
We should try to integrate https://github.com/OculusVR/RakNet into godot.

Multiplayer support would be awesome.. :)

**Comment by GungnirInd** [comment]
Godot already has networking support; it's not particularly well documented right now, but there are a couple of examples on the forum of basic multiplayer systems, and the UDP chat demo also helps illustrate how it works.  The networking system is also getting improved in version 1.3, according to the roadmap on the wiki.

If you really need RakNet for some reason, there's an add-on module that adds support for it, though I'd recommend trying the built-in system first: https://github.com/antarktikali/godot-raknet-example

**Comment by vkbsb** [comment]
Nice thank you..!

**Comment by reduz** [comment]
i think someone made a module integrating raknet
