### ISSUE TITLE
Nicer Boot Logo Handling

### ISSUE THREAD

**Issue by philiplb** [okamstudio/godot#1539]
Hi,

I just set the boot logo with a 1280x720 JPEG. And now I ended up with a 5MB engine.cfg containing the image in a serialized way. What I expected: "res:\\.....jpg" in it, some kind of reference.

**Comment by reduz** [comment]
this needs to be hacked a little, the problem is that at the time logo is
shown, engine did not initialize, so no PNG or JPG loaders are present.
will eventually fix this one way or the other, so thanks for reporting it

**Comment by philiplb** [comment]
Ok, cool, thanks for the response. :)

**Comment by philiplb** [comment]
Nice. :)
