### ISSUE TITLE
Crash in Visual shader editor

### ISSUE THREAD

**Issue by honix** [okamstudio/godot#1540]
2015-03-16 build

- Create CurveMap in VSE
- Make some keypoints
- Try to delete someone by holding mouse and press delete
- Crash

**Comment by honix** [comment]
**(1.1 beta1)**

Yep, it fixed now. It works when i select point and press delete, then point removes. But still crash when i press delete + **still hold left mouse button**. May be its a ui problem, when under mouse object disappeared, and crash godot. Thanks!

**upd:** Same problem with colorRemap!

**Comment by reduz** [comment]
this is fixed
