### ISSUE TITLE
android apk is broken

### ISSUE THREAD

**Issue by jminix** [okamstudio/godot#1546]
I have compiled several working custom android builds.  Most recent attempt has resulted in a broken apk.  Compiling under Ubuntu 14.04 32 bit.  Compilation succeeds and apk generation is successful, however when running on phone it immediately displays "Unfortunately, [app] has stopped."  My previous builds still work.  I have been staying current with master.  Is anyone else having this difficulty?

**Comment by jminix** [comment]
found the problem.  I was renaming "libgodot.android.so" instead of "libgodot_android.so".  I thought all the recent merges is what broke it.

**Comment by Brayacon** [comment]
where can you rename it
