### ISSUE TITLE
Exported game fails, run from editor works, Godot 1.0 Stable.

### ISSUE THREAD

**Issue by PLyczkowski** [okamstudio/godot#1556]
These are the errors I get in the exported game:

![shot_150323_115857](https://cloud.githubusercontent.com/assets/7307968/6778571/05132502-d154-11e4-929c-28d279218397.png)

Godot 1.0, stable export templates.

**Comment by bojidar-bg** [comment]
You are using stable templates with the dev version, right?

**Comment by PLyczkowski** [comment]
Nope, with the stable 1.0.

**Comment by PLyczkowski** [comment]
Latest build exports ok though. Maybe it has to do with the fact that I changed some settings in newer build, that were not available in 1.0 stable. Closing.
