### ISSUE TITLE
Trying to build export templates on windows fails.

### ISSUE THREAD

**Issue by PLyczkowski** [okamstudio/godot#1557]
Here are the errors:

![shot_150323_120429](https://cloud.githubusercontent.com/assets/7307968/6778655/d5d038b0-d154-11e4-9cac-943bf67afdff.png)

**Comment by marynate** [comment]
should be fixed in PR: https://github.com/okamstudio/godot/pull/1555

**Comment by PLyczkowski** [comment]
Yup, fixed, closing.
