### ISSUE TITLE
Ubuntu 14.04 64-bit: not compiled. xinerama not found.. x11 disabled.

### ISSUE THREAD

**Issue by vladikoles** [okamstudio/godot#1558]
AMD Radeon HD6450

scons platform=x11

scons: Reading SConscript files ...
Package xinerama was not found in the pkg-config search path.
Perhaps you should add the directory containing `xinerama.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xinerama' found
xinerama not found.. x11 disabled.
sh: 1: i586-mingw32msvc-gcc: not found
sh: 1: x86_64-w64-mingw32-gcc: not found
sh: 1: i686-w64-mingw32-gcc: not found
No valid target platform selected.
The following were detected:
	server

Please run scons again with argument: platform=<string>
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.

**Comment by marcosbitetti** [comment]
I'm having the same issue.
In this moment Juan appears to work in window code...

**Comment by Mikeb85** [comment]
You need to install the xinerama-dev (what it's called may depend on your distro) headers...  Seems they pulled in a new dependency...

**Comment by marcosbitetti** [comment]
you mean x11proto-xinerama-dev ?

**Comment by reduz** [comment]
i'm not on debian/unbutu sof if you let me know which is the new apt line
required, I can add it to the wiki

**Comment by vladikoles** [comment]
tried to solve the problem: x11proto-xinerama-dev installed.
no improvement.

**Comment by ndee85** [comment]
I can confirm I have the same issue on linux mint

**Comment by marcosbitetti** [comment]
sorry! I checked a wrong package,  ^_^. Try:
sudo apt-get install libxinerama1 libxinerama-dev
scons clear
scons platform=x11

**Comment by marcosbitetti** [comment]
oh.... f#k one more error, but I supose is not from xinerama:

tools/editor/io_plugins/editor_import_collada.cpp:1363:7: error: 'cout' is not a member of 'std'
       std::cout << "has normals" << std::endl;
       ^
tools/editor/io_plugins/editor_import_collada.cpp:1363:37: error: 'endl' is not a member of 'std'
       std::cout << "has normals" << std::endl;
                                     ^
tools/editor/io_plugins/editor_import_collada.cpp:1365:7: error: 'cout' is not a member of 'std'
       std::cout << "normals source: "<< normal_src_id.utf8().get_data() <<std::endl;
       ^
tools/editor/io_plugins/editor_import_collada.cpp:1365:75: error: 'endl' is not a member of 'std'
       std::cout << "normals source: "<< normal_src_id.utf8().get_data() <<std::endl;
                                                                           ^
tools/editor/io_plugins/editor_import_collada.cpp: In member function 'void ColladaImport::create_animation(int, bool)':
tools/editor/io_plugins/editor_import_collada.cpp:2183:18: warning: unused variable 'cn' [-Wunused-variable]
   Collada::Node *cn = collada.state.scene_map[at.target];
                  ^
scons: *** [tools/editor/io_plugins/editor_import_collada.x11.tools.64.o] Error 1

**Comment by UsernameIsAReservedWord** [comment]
@marcosbitetti : the two faulty lines have been disabled in current version of editor_import_collada.cpp.

**Comment by marcosbitetti** [comment]
ok. A little "pull" in repo and all work.
@vladikoles this packages work?

**Comment by vladikoles** [comment]
sudo apt-get install libxinerama1 libxinerama-dev
scons platform=x11

Yes! All ok. Normal compilation.
