### ISSUE TITLE
Latest windows build crashes when opening project.

### ISSUE THREAD

**Issue by PLyczkowski** [okamstudio/godot#1560]
Errors:

![shot_150323_161823](https://cloud.githubusercontent.com/assets/7307968/6783115/59d8e148-d178-11e4-8ad1-061c5e3915e9.png)

**Comment by UsernameIsAReservedWord** [comment]
what compiler ?

**Comment by PLyczkowski** [comment]
Scons, following these instructions - https://github.com/okamstudio/godot/wiki/compiling_windows

Is Scons a compiler? : ) If it's not, then the default one it uses.

**Comment by dyrverE** [comment]
The very same thing happens on Linux 64-bit, compiled just now using gcc 4.9.2 unless it prefers clang 3.6.0. And distribution Arch Linux, if it matters much.
