### ISSUE TITLE
Tilemap accept only .xml tileset

### ISSUE THREAD

**Issue by MangelMaxime** [okamstudio/godot#1573]
I am following this [tutorial](https://github.com/okamstudio/godot/wiki/tutorial_tilemap).

And so I have export the tileset with the extension .res but when I try to load it in the TileMap it do nothing. However, if I export it with the .xml extension it's working properly.

Is it intended ?

I am using Godot 1.0.

**Comment by bojidar-bg** [comment]
Maybe you can try building the newest version from git, in case it is fixed (somehow)?

**Comment by MangelMaxime** [comment]
You are rigth completly forgot to test it.
