### ISSUE TITLE
[CRASH] Adding tiles without a NavigationPolygon to a tilemap where some of the tiles has crashes the editor

### ISSUE THREAD

**Issue by Hjorthenify** [okamstudio/godot#1581]
Hi. 
I've wanted to implement pathfinding to my game and I noticed by looking at the source code, that a tilemap looks for a parent node of the type "Navigation2D".
I went on and added navigation polygons on the walk-able tiles of my map(its a top-down game) and exported the tiles as a .xml tileset. 
Then I added a tilemap as a child of a Navigation2D node. 

I can add the tiles containing a NavigationPolygon to the map just fine, but my game crashes when I try to add a tile without one. 
Here's a picture of my setup: 
![udklip](https://cloud.githubusercontent.com/assets/11670799/6857118/e4709da8-d404-11e4-85cb-a3ab8a0b75ea.PNG)

I am using my own compilation which I build the 22/03/15. 

EDIT: 
I am running the 64-bit build on a windows 7 laptop.

**Comment by reduz** [comment]
what do you mean add a tile without one?

**Comment by reduz** [comment]
i think this is fixed, please test
