### ISSUE TITLE
setget and yield() vanished from wiki documentation ?

### ISSUE THREAD

**Issue by SuperUserNameMan** [okamstudio/godot#1583]
Hi,

I'm not 100% sure it was really there at some time in the past, but it seems that the "setget" keyword documentation has vanished from the wiki gdscript documentation.

**Comment by silverkorn** [comment]
If no nobody answers you, you can always clone the wiki and search.
`git clone https://github.com/okamstudio/godot.wiki.git`

I've looked at Juan's latest activities and he has not touched something that might have impacted this kind of information within the last 7 days.

**Comment by okamstudio** [comment]
I think I might have erased an old version of the gdscript doc when i
checked out github on windows, due to the case insensitivity.. do you think
you could check if anything changed in the gdscript file in the latest
weeks?


On Mon, Mar 30, 2015 at 11:33 AM, Danny Boisvert <notifications@github.com>
wrote:

> If no nobody answers you, you can always clone the wiki and search.
> git clone https://github.com/okamstudio/godot.wiki.git
>
> I've looked at Juan's latest activities and he has not touched something
> that might have impacted this kind of information within the last 7 days.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1583#issuecomment-87703360>.
>



-- 

*OkamStudio*

**Comment by silverkorn** [comment]
Deleted initially at this commit: `766e9f19bba424ea8776ddd10b99eab3affb9a8d` (__texscreen stuff__, a week ago)

There was a madness with this one:
- __texscreen stuff__ (deleted the markdown file);
- __Revert "texscreen stuff"__ (fixed the markdown file);
- __Revert "Revert "texscreen stuff""__ (deleted back the markdown file :laughing: )

**Comment by okamstudio** [comment]
do you know what can i do to revert this? I can't figure out how to do it
from github


On Mon, Mar 30, 2015 at 1:01 PM, Danny Boisvert <notifications@github.com>
wrote:

> Deleted initially at this commit: 766e9f19bba424ea8776ddd10b99eab3affb9a8d
> (*texscreen stuff*, a week ago)
>
> There was a madness with this one:
>
>    - *texscreen stuff* (deleted the markdown file);
>    - *Revert "texscreen stuff"* (fixed the markdown file);
>    - *Revert "Revert "texscreen stuff""* (deleted back the markdown file [image:
>    :laughing:] )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1583#issuecomment-87735430>.
>



-- 

*OkamStudio*

**Comment by silverkorn** [comment]
The GitHub Web interface for Wikis is quite limited, I suggest doing something like this:

`git clone https://github.com/okamstudio/godot.wiki.git`
`cd godot.wiki && git checkout 46095dfff6a5beb640231536082fddb03c6808b6`

(this is the commit right before the initial deletion of GDScript.md)

There you could copy the content of the `GDScript.md` and add it back through the GitHub Web Interface for Wikis.

**Comment by reduz** [comment]
nope, for some reason can't get this to work.. can you download the file and upload it somewhere?

**Comment by silverkorn** [comment]
Sure, there:
https://gist.github.com/silverkorn/7935e3c7fb434dec0473 ([RAW](https://gist.githubusercontent.com/silverkorn/7935e3c7fb434dec0473/raw/45483aa56ad22e6000f287b0de73cf6d75d0689a/GDScript.md))

**Comment by UsernameIsAReservedWord** [comment]
@reduz : You probably read me crying on IRC about it : We've lost the doc for `yield()` too.

**Comment by reduz** [comment]
thanks! fixed now
