### ISSUE TITLE
Error with Front image of CubeMap (maybe a storage problem)

### ISSUE THREAD

**Issue by marcosbitetti** [okamstudio/godot#1584]
I try to make a cube map, using a version compiled with last commits, and CubeMap tool appears broken! When I load image on Front slot, the editor raise a error:
ERROR: texture_set_data: Condition ' texture->format != p_image.get_format() ' is true.
   At: drivers/gles2/rasterizer_gles2.cpp:951.

The others images of cube are fine.

This is the original image file

![front](https://cloud.githubusercontent.com/assets/85936/6879433/cbdaa6e2-d4d3-11e4-8a02-857d3fbdc4b7.png)

**Comment by UsernameIsAReservedWord** [comment]
I get the error you mention, only when I try to mix different format of textures in my cubemap.

are others cube sides textures of the same format than this one ? (8bits 512x512 pixels) 
do they all contain a "512, 0 offset" ? (Gimp complains about this image contains a 512,0 offset)

**Comment by marcosbitetti** [comment]
Thanks @UsernameIsAReservedWord 
Appears that my laziness don't help me this time :P
The problem is really in PNG data, generated by imagemagick tool...  that I made from myself.

I correct my script and work fine now. https://gist.github.com/marcosbitetti/cb9a6539476cb0741b77
