### ISSUE TITLE
script node

### ISSUE THREAD

**Issue by draxdeveloper** [okamstudio/godot#1586]
Ok, i was thinking about node made to receive a script resource, so i can, for example make a jump script to the a game and even use it in another game, with just small changes.
Of course, i can just make a simple node and put the "jump" script on it... But the script node could have some exclusive resources
1 - since the idea of a script node it's to add a "sub-script" to the node, the notion of self can be the get_parent (and you have to use other path to refer to the script itself) so if you just type get_pos it's the parent position
2 - it can have a handle to activate or deactivate the whole script, so i can just deactivate the jump of a char by deactivating the jump script
3 - maybe some inheritance of the parent script?

**Comment by reduz** [comment]
you can put an empty node as a child and assign a script to it, and do it
as many times as you wish.. it's pretty much the same way as using
behaviors in unity

**Comment by draxdeveloper** [comment]
Yeah, i had think about it...
But i can deactivate a node?

**Comment by reduz** [comment]
you can change processing of stuff individually (input events, _process
callback, etc)  with set_process(), set_process_input(), etc. In the worst
case, just remove the node from the scene with remove_child() and add it
back with add_child()

**Comment by draxdeveloper** [comment]
or i can create a trigger myself

2015-03-30 14:37 GMT-03:00 Juan Linietsky <notifications@github.com>:

> you can change processing of stuff individually (input events, _process
> callback, etc) with set_process(), set_process_input(), etc. In the worst
> case, just remove the node from the scene with remove_child() and add it
> back with add_child()
>
>
> On Mon, Mar 30, 2015 at 2:33 PM, David Paiva <notifications@github.com>
> wrote:
>
> > Yeah, i had think about it...
> > But i can deactivate a node?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/issues/1586#issuecomment-87763856>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1586#issuecomment-87766132>.
>



-- 
David Aguiar de Aquino Paiva
