### ISSUE TITLE
[1.1 rc2]:platform3d Particle shows bad

### ISSUE THREAD

**Issue by vipsbpig** [okamstudio/godot#1588]
In godot 1.1beta1  ,I found the platform3d demo shows a wrong particle display in bullet scene .It seems alpha not working .. Particle system updated lately . Is demo out of date? I am sorry for my bad english .

**Comment by Calinou** [comment]
Indeed, all particles show up as white cubes while running the demo.

**Comment by sniper-shot92** [comment]
the particle emitter's color phases is still broken in godot 1.1 rc1 :(

**Comment by vipsbpig** [comment]
I try the godot 1.1 rc2 ,it compare to 1.0 ,it still appear wired..here is the pic between them
![qq 20150506174719](https://cloud.githubusercontent.com/assets/1953549/7491201/99af5f5e-f419-11e4-80d1-4fa859db5336.png)
![qq 20150506175313](https://cloud.githubusercontent.com/assets/1953549/7491200/99aec030-f419-11e4-99a7-1bc70304f59b.png)
![qq 20150506175452](https://cloud.githubusercontent.com/assets/1953549/7491202/99b0495a-f419-11e4-8079-1c73c8d29583.png)
![qq 20150506175515](https://cloud.githubusercontent.com/assets/1953549/7491203/99b3cab2-f419-11e4-8ce9-adfdd798e85e.png)



.

**Comment by OlexiyKravchuk** [comment]
I have also been informed about this issue in a theme here ... https://github.com/okamstudio/godot/issues/1760#issuecomment-98533258? in fact it appeared in the beta 1.1 version.

**Comment by ricpelo** [comment]
I can confirm this issue with HEAD and latest versions of Navmesh Demo and Platformer 3D.

**Comment by reduz** [comment]
hm guess it's because PartlceMaterial was removed, will have to fix it

**Comment by OlexiyKravchuk** [comment]
I also noticed that there is no (particles material) there anymore, and maybe it's a wise move to merge all the material in one standard and the mechanism works the same everywhere.

And by the way it is now possible to apply shaders to the particles?
