### ISSUE TITLE
Bullet Shower demo crashes after repeated collision with bullet objects

### ISSUE THREAD

**Issue by Ace-Dragon** [okamstudio/godot#1592]
To reproduce...

 - Open and play 'Bullet Shower' from the Godot demo pack
 - Run into as many bullets as you can, when the face switches states for the third or fourth time, the demo will crash

The console also will not show any error in particular, just an expletive and the word "no error"

This bug confirmed on a Win64 MingW debug build from the 25th of March. Hopefully this can be fixed.

**Comment by bojidar-bg** [comment]
Can't reproduce... maybe you can complie today's version and test again?

**Comment by Ace-Dragon** [comment]
Well I just tried the latest version of the demo in the beta and the game will now crash if I even touch a bullet.

Something must be going on with the sprite changing code or something.

**Comment by UsernameIsAReservedWord** [comment]
I confirm it crashes also on a 32bits MSVC2010 debug build.

**Comment by UsernameIsAReservedWord** [comment]
I tried again with today's source code.

According to MSVC2010 debugger :

in viewport.cpp, on line 406 :
````
    int rc = ss2d->intersect_point(point,res,64,Set<RID>(),0xFFFFFFFF,0xFFFFFFFF);
````
rc value is : 128 962 976

it should be 64 maximum.

**Comment by Wend1go** [comment]
Godot 1.1Beta from godotengine.org also affected

**Comment by gra-frogger** [comment]
same error in my pong game

ERROR: set_stream_peer: Condition ' p_peer.is_null() ' is true.
   At: core/io/packet_peer.cpp:228.

**Comment by bojidar-bg** [comment]
@gra-frogger are you using git version of godot?

**Comment by gra-frogger** [comment]
my game have the same effect on 1.0 stable and 1.1 beta downloaded from site

**Comment by bojidar-bg** [comment]
@gra-frogger can you comple godot yourself using the git version? The 1.1 beta is a bit old nowdays.
