### ISSUE TITLE
Instanced scene with an unshaded material gets lit by light and canvasmodulation

### ISSUE THREAD

**Issue by WatIsDeze** [okamstudio/godot#1598]
Instanced scene with an unshaded material gets lit by light and canvasmodulation
![screen shot 2015-04-01 at 17 45 51](https://cloud.githubusercontent.com/assets/10252874/6945002/1a61efe8-d897-11e4-8aa1-569c218c5e32.png)
![screen shot 2015-04-01 at 17 46 01](https://cloud.githubusercontent.com/assets/10252874/6945003/1a628ebc-d897-11e4-8cf8-b0e19bd445f7.png)

**Comment by reduz** [comment]
try with a newer version of Godot, the unshaded property no longer exists. The replacement enum seems to work fine.

**Comment by reduz** [comment]
i think this is fixed
