### ISSUE TITLE
[Feature] Replace Godot's script editor with Emacs

### ISSUE THREAD

**Issue by shackra** [okamstudio/godot#1599]
I've been using the Godot's integrated script editor for a while (before [the free edition went published by Okam Studio](http://www.godotengine.org/wp/godot-is-now-really-free/)), but it is lacking of very essential features like an integrate psychoanalyst and games like Snake and Tetris to entertain you after many hours editing GDScript code... all this features and more are available already in Emacs!

So, the idea is to get rid of the stock editor in Godot and integrate Emacs, thus, having a operating system that lacks of good game engine and text editor!

One of the many benefits we'll get from integrating Emacs in Godot would be the possibility of using Emacs lisp for writing game code instead of GDScript. We all know that GDScript syntax lacks of `{` and `}` to delimit blocks of code, and things get ugly if you want to obfuscate your code in order to force your employee to not fire you (because you are the only guy that understand that obfuscate code!), Emacs lisp is not racist because it do not treat *"white spaces"* in any special way, you can even write your code in one line if you want!! This is a big plus for those wanting to keep their jobs safe obfuscating their work!

I've reading about integrating Emacs in bread toaster, refrigerators, kitchens and many other kind of home appliances, the integration with Godot seems to be easy and smooth, [here is the link for the developers to read](https://en.wikipedia.org/wiki/April_Fools'_Day).

**Comment by UsernameIsAReservedWord** [comment]
I HATE april fools .....

I vote for banning you from the web every april 1st, and to replace april 1st by february 30th.

**Comment by GungnirInd** [comment]
Hey, everyone knows Lisp is far more user-friendly than anything Python-like could ever hope to be.  There might be a bit of resistance at first from Vim fans, but I think that they'll eventually agree that this is truly the best direction to take the script editor.

Nicely written, Shackra :P

**Comment by kubecz3k** [comment]
vim is better

**Comment by adolson** [comment]
Vim > *

**Comment by Qwertie-** [comment]
#nano4lyfe

**Comment by johannesgunnar** [comment]
I prefer Microsoft's Notepad

**Comment by sanderboer** [comment]
I was honestly excited about this news.
=(
I edit my unity scripts in emacs with omnisharp code completion. I like it like that.

**Comment by sanderboer** [comment]
ps vim sucks

**Comment by WatIsDeze** [comment]
A method of using GDScript in an external editor(with autocompletion, thus basically providing a process that editors could call in to) may be a nice idea after all?

This is thus totally different than the support it has at this moment for opening files in an external editor.

That is to skip the April fools jibber :P

**Comment by shackra** [comment]
Today is not April fool's day :)

**Comment by UsernameIsAReservedWord** [comment]
hooray !

**Comment by Angluca** [comment]
vim +1

**Comment by yurumi** [comment]
Love emacs --» I modified python-mode.el. Many rough edges as I'm not familiar with elisp but usable...

**Comment by caiocutrim** [comment]
vim +1 or neovim +1 :)

**Comment by loohoo** [comment]
vim +1

**Comment by akien-mga** [comment]
Ok, that issue was fun back then but I think we can stop bumping it pointlessly, so locking.
