### ISSUE TITLE
Transform.looking_at()  - reversed Z axis

### ISSUE THREAD

**Issue by kubecz3k** [okamstudio/godot#1601]
Correct me if I'm wrong but I'm thinking that Transform.looking_at(Vetor3 targetPoint, Vector3 upVec) method should rotate z possitive object to face a targetPoint... Right now its rotating object to face it's back to target point... Or I'm doing something wrong
Visual reference: https://dl.dropboxusercontent.com/u/168251/godot/some/issues/lookatIssue.png
TestProject: https://dl.dropboxusercontent.com/u/168251/godot/some/issues/LookAtIssue.7z

**Comment by reduz** [comment]
looking_at targets negative z,  OpenGL/GLU were used as reference for this,
as cameras point to -Z too.

**Comment by kubecz3k** [comment]
Thanks for reply @reduz Closing because it's intended behaviour
