### ISSUE TITLE
Objects can crash Godot if their script contains remove_and_delete_child() in multiple loops

### ISSUE THREAD

**Issue by Ace-Dragon** [okamstudio/godot#1603]
I'll let the project do the talking
http://www.mediafire.com/download/g34cr3uxtmq5rpr/Test.zip

Basically, this contains a turret object that opens and starts spewing out bullet objects, the bullet objects then have a script that deletes them when they hit another object.

The bug in question has to do with having the function known as *remove_and_delete_child()* in multiple **if** statements. As it stands, the project will crash as soon as a bullet hits the cube, but if I changed the script to set a variable in those loops and just use remove_and_delete_child() in one place, then it will work like it should.

You will need to play the project to see it, as it would be difficult for others to confirm due to the setup needed.

This bug has been confirmed on a Win7 64 bit machine with an Ivy Bridge i7 CPU, an ATI 9xxx GPU, and 16 gigs of RAM. This using the new Godot 1.1 beta version.

**Comment by reduz** [comment]
this function will go away now. It's unnecesarily dangerous and prone to crash. Simply calling free() on the child does the same and the debugger can catch potential errors
