### ISSUE TITLE
The accelerometer does not adapt for default orientations across different android devices.

### ISSUE THREAD

**Issue by Martho42** [okamstudio/godot#1604]
The x and y axes are switched between some android devices, depending on the default orientation. E.g. on device A the x axis is up and down whereas on device B the x axis is left and right, while both devices are in the same orientation. In Java, you can test for the default orientation and correct your program to match it. You can see this in the following link: http://stackoverflow.com/questions/5877780/orientation-from-android-accelerometer

**Comment by Martho42** [comment]
I believe I fixed it. I'm figuring out how to make a pull request, but for now ill just post the solution here. In the file: platform/android/java/src/com/android/godot/Godot.java I changed this:

	@Override public void onSensorChanged(SensorEvent event) {
		float x = event.values[0];
		float y = event.values[1];
		float z = event.values[2];
		GodotLib.accelerometer(x,y,z);
	}

To this:

	@Override public void onSensorChanged(SensorEvent event) {
		
		Display display = ((WindowManager) getSystemService(WINDOW_SERVICE)).getDefaultDisplay();
		int displayRotation = display.getRotation();
		
		float[] adjustedValues = new float[3];
		final int axisSwap[][] = {
		{  1,  -1,  0,  1  },     // ROTATION_0 
		{-1,  -1,  1,  0  },     // ROTATION_90 
		{-1,    1,  0,  1  },     // ROTATION_180 
		{  1,    1,  1,  0  }  }; // ROTATION_270 

		final int[] as = axisSwap[displayRotation]; 
		adjustedValues[0]  =  (float)as[0] * event.values[ as[2] ]; 
		adjustedValues[1]  =  (float)as[1] * event.values[ as[3] ]; 
		adjustedValues[2]  =  event.values[2];
		
		float x = adjustedValues[0];
		float y = adjustedValues[1];
		float z = adjustedValues[2];
		GodotLib.accelerometer(x,y,z);
	}

I had to swap some of the axes in my game code after making this change, however now it behaves consistently across all my devices.

**Comment by reduz** [comment]
i think PR was merged, so closingt his
