### ISSUE TITLE
rand_range function gives the same every time the first value.

### ISSUE THREAD

**Issue by DimaKiva** [okamstudio/godot#1605]
For example
func _ready():
____print(rand_range(0, 10))

Obtain
0.207684

Godot 1.1 Beta

**Comment by not-surt** [comment]
Why would you want different results from the same seed?

**Comment by DimaKiva** [comment]
I did not find this other applications, but to do what he tried to do.

**Comment by Martho42** [comment]
func _ready():
     randomize()
     print(rand_range(0, 10))

There, all better.

**Comment by DimaKiva** [comment]
Wow. Martho42, thank you, it works. But it's strange.

**Comment by reduz** [comment]
this is normal and expected behavior, call randomize() to change seed.
