### ISSUE TITLE
Label out of window bounds in "scene not saved" window

### ISSUE THREAD

**Issue by WalasPrime** [okamstudio/godot#1607]
1.1beta1

Cosmetic bugs I guess, labels out of bounds

Reproduce:
1. Create a new project
2. Add a node of any type
3. Press "Play the edited scene (F6)"
4. A window appears with a label out of bounds

Additionaly:
5. Press Yes to save the scene
6. After saving there is an alert that no main scene was defined (label also out of bounds) (which is the behaviour of the normal Play button, not the Play edited scene button)

**Comment by michaeldesu** [comment]
Agree. The same thing occurs when clicking the key icon when using the animator (as shown below)
![text-overshoot](https://cloud.githubusercontent.com/assets/11791450/6990780/bc35c624-dab7-11e4-960e-ef9ed070c601.png)
