### ISSUE TITLE
Material Shader Graph problems [Beta 1.1]

### ISSUE THREAD

**Issue by Obaran** [okamstudio/godot#1610]
1. If I save scene where is material ShaderGraph, after reopen scene or project, all textures are dissapear (in material shader graph are there, but not displayed in scene editor on 3D model). I must load my material, and it not load all texture. Then I create new materialSG and after this my saved mSG load all textures (displayed in scene editor).

2. If i select Clear in materialSG (in inspector), Godot crash.

3. Sometimes the Vertex or Light I can't click on it.

4. Add module > Vector Length, add input and try add output or move with VLength, Godot crash.

EDIT:
New
5. UV2 - after connect UV2 to the Texture uniform or Vectors etc.. textures are dissapear from 3D model and form material. If UV2 is disconetcted or not used, everything is back.

**Comment by reduz** [comment]
i think this is all fixed now, let me know if you find otherwise
