### ISSUE TITLE
Did you forget the tool keyword?

### ISSUE THREAD

**Issue by Ijatsu** [okamstudio/godot#1615]
Hello,

I tried to make a tool script according to the example in the gdscript wiki.
Whenever I try to execute this code via the "run script" command from the scene menu, godot tells me:

"Couldn't instance the script:
...
did you forget the tool keyword?"

The script I use is the same as the one in the wiki and is not attached to a node.

**Comment by TheoXD** [comment]
"tool" keyword is not just for executing scripts through "run script", it is used for post-import scripts and allow nodes to run in editor.  But when you try to run a script using "Scene->RunScript" it must extend EditorPlugin, and it must contain a function called _run()
