### ISSUE TITLE
CanvasItemMaterials and ShaderParams

### ISSUE THREAD

**Issue by Ijatsu** [okamstudio/godot#1616]
Hello,

I might do things bad.
I observed the cubio demo and I wanted to test things on my own using CanvasItemMaterials on Sprite.

The CanvasItemMaterials have Shader Params, on my own project (using v1.1 of course) I see that the API allows me to create ones but I can't add shader params via the editor, which leads to error when trying to script shaders.

**Comment by TheoXD** [comment]
To me this sounds more like a question, not an issue.
In order for shader params to show in the inspector, you must add some uniforms to the shader graph/script.

**Comment by Ijatsu** [comment]
Thanks a lot :)
