### ISSUE TITLE
IMPORT:: Collada importer cannot merge in newly added objects to existing scenes

### ISSUE THREAD

**Issue by Ace-Dragon** [okamstudio/godot#1620]
So essentially, assume that you're working on a scene in Blender and you export it to Collada, you import it into Godot, it loads in fine, and you set up the scene tree by assigning objects as static bodies, good right?

Now say you want to add more objects into the mix, you re-export the scene, you select the *Keep existing; Merge new* option, but...

Godot will successfully import the changes done to the existing objects, but the new objects will not exist, Godot apparently does not know they are now in the scene file, the only way to import them is to overwrite everything and redo the scene tree setup.

So, I'm wondering if this is something that can be fixed and/or added to Godot's importing capabilities, as it would make working with large pieces of 3D scene geometry a lot easier. It would also need to recognize if an object was deleted from the file and remove it from the scene (which is also doesn't do as of now).

If this can be done for version 1.1, that would be great

thanks.

**Comment by reduz** [comment]
i think this works now, also bettercollada got some fixes that should help reimport materials properly
