### ISSUE TITLE
touch on fist scene,second scene get the touch event

### ISSUE THREAD

**Issue by lengyue524** [okamstudio/godot#1622]
I have two scene which are scene1 and main
There is a button on scene1.
Click button and change to main.
On change to main,I found ScreenTouch event execute on the main.It's strange.
I only touch the button on scene1.
I tried accept_event() and get_tree().set_input_as_handled() to consume event but they didn't work.
what should I do?
Follow is the code attach to the button.
```
extends Button

# member variables here, example:
# var a=2
# var b="textvar"

func _ready():
	# Initalization here
	#set_process_unhandled_input(true)
	pass

#func _unhandled_input(event):
#	print(str("_unhandled_input",event))
#	get_tree().set_input_as_handled()
#func _pressed():
#	get_node("/root/global").goto_scene("res://main.scn")
func _input_event(event):
	print(str("start",event.type,event.pressed))
	if (event.type == InputEvent.MOUSE_BUTTON and event.pressed):
		get_node("/root/global").goto_scene("res://main.scn")
		accept_event()
	if event.type == InputEvent.SCREEN_TOUCH:
		accept_event()
```

**Comment by reduz** [comment]
if you are using _input_event(), try calling accept_event()

**Comment by reduz** [comment]
closing, since i think all you have to do is accept_event(), let me know if I misunderstood
