### ISSUE TITLE
Exported game error - Linux [Beta 1.1.0]

### ISSUE THREAD

**Issue by TheBlade** [okamstudio/godot#1623]
When trying to execute a compiled program (exe + pack) from Godot Engine Beta 1.1.0, here is the error that appears:

ERROR: get_executable_path: Could not get executable path from / proc / self / exe, using argv [0]
    At: drivers / unix / os_unix.cpp: 414.
ERROR: try_open_pack: Condition 'ver_major> 1 || (== 1 && ver_major ver_minor> 0)' is true. returned: ERR_INVALID_DATA
    At: core / io / file_access_pack.cpp 156.
error: Could not load game path '.'
Godot v1.0.stable.7eb5d049c2 Engine (c) 2008-2015 Linietsky Juan Ariel Manzur.

As you can see, it seems that there is an inconsistency between the data file and the compiled executable.

Best Regards ...

**Comment by reduz** [comment]
are you using the export templates from this same version too?

**Comment by TheBlade** [comment]
Good question!
I must admit that I have not verified this option. I download again and I confirm if it has corrected the problem. (My God ... Juan Linietsky wrote me! Woow!)

**Comment by TheBlade** [comment]
Thank you for your help. This will correct the problem out. Sorry to have bothered you for a problem so "simple". This will have taught me something more about this great engine. I'll be careful in the next update.

A great message of encouragement to all the team. Thank you for all the work you do. You provide us with quality products and do it with passion.

I went back to reading the wiki ...

Thank you again ...
Best Regards
