### ISSUE TITLE
Can't add_child

### ISSUE THREAD

**Issue by Mavhod** [okamstudio/godot#1629]
I create hierarchy with:
- parent
 - child1

In child1 had this script:
```
extends Node

func _ready():
	var parent		= get_node("..")
	var nodeTest	= Node.new()
	nodeTest.set_name("nodeTest")
	parent.add_child(nodeTest)
	print(parent.get_name(), " child = ", parent.get_child_count())
	var i
	for i in range(parent.get_child_count()):
		print(parent.get_child(i).get_name())
```

When run output showed:
```
parent child = 1
child1
```

It not add child in to parent node.

**Comment by reduz** [comment]
when you are in "_ready" the children are locked (because children are being iterated to give you that notification). 
try doing
parent.call_deferred("add_child",nodeTest) instead

**Comment by Mavhod** [comment]
Ok, I understood.

Actually my work is load scene and at it into the parent node, and it had a script with function _ready, it must consider about call orders with other nodes.

Thanks reduz.

**Comment by jrkirby** [comment]
Can we put this in the documentation somewhere? I was following https://github.com/okamstudio/godot/wiki/tutorial_scripting_2, didn't know this, and was wondering why I was unable to add nodes and crashing the game.

**Comment by raould** [comment]
It would be great if somehow some day the Godot engine didn't lock the list but instead made a duplicate for the iteration it is doing internally, so that when our scripts try to do things in _ready() they just work.

**Comment by pallavnawani** [comment]
And what would happen if you deleted child nodes in _ready() while Godot is busy iterating over the list copy?

**Comment by reduz** [comment]
The list is only locked for parent nodes, the current node and it's
children can use add_child fine

**Comment by JarLowrey** [comment]
For me, the engine said `... System.NullReferenceException ... Node.cs:386 @ void Godot.Node.AddChild(Godot.Node , Boolean )()` in my C# project. It ended up being that I was not calling `base._Ready()` and that I had to forgotten to assign a value to a timer in _Ready (`timerProp=GetNode("Timer") as Timer;`)

**Comment by manekinekodesu** [comment]
We need some kind of error notification for this. Just lost an hour trying to figure out what's going on. I was able to compile & run the code fine even though child node was never actually added.
