### ISSUE TITLE
SSL: unable to get local issuer certificate

### ISSUE THREAD

**Issue by MrJustreborn** [okamstudio/godot#1630]
It seams Godot can't get the local certificates to verify a host.
> I'm using Manjaro Linux 64bit

similar to #1626
```
Cause: unable to get local issuer certificate
CERT STR: /C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
VALID: 0
CONNECTION RESULT: -1
SSL! TURNED ON!
```

**Comment by reduz** [comment]
did you set a file with certificates?

**Comment by MrJustreborn** [comment]
I thought OpenSSL would use my System-Path.
Where can I specify a file? - I didn't find anything in the Wiki.

**Comment by reduz** [comment]
no.. some platforms such as Windows, iOS, Android, etc don't give you
access to system wide certificates..
also many times you want to use a self signed cert or trim to a list of
trusted CAs when you do domain validation.

if you are in linux, you can find the standard certificates files at:
/etc/ssl/certs/ca-certificates.crt
in PEM format

just copy this to your project, add it to the export filters (*.crt) and
add the file in project settings

**Comment by reduz** [comment]
will try to remember make a tutorial about this, so please don't close the
issue if it works for you

**Comment by MrJustreborn** [comment]
I totaly overseen the certification setting in the project settings, now it works!

**Comment by reduz** [comment]
Just in case for anyone searchig, I added an SSL tutorial
https://github.com/okamstudio/godot/wiki/tutorial_ssl
