### ISSUE TITLE
MateralShaderGraph UV2 not working [Beta 1.1]

### ISSUE THREAD

**Issue by Obaran** [okamstudio/godot#1633]
In MateralShaderGraph editor, UV2 not working and add gray color into model (all textures and effect are dissapear)

**Comment by reduz** [comment]
i can't seem to reproduce, could you elaborate a little more?

**Comment by Obaran** [comment]
I create video (i think it is more then thousands of words) with problem and UV2 problem (from around 1:04min) too 
https://youtu.be/DyDYeXt5MBg
