### ISSUE TITLE
MateralShaderGraph after load scene or MSG, textures are not loaded [Beta 1.1]

### ISSUE THREAD

**Issue by Obaran** [okamstudio/godot#1634]
After load new scene, project or load MSG, textures are not visible. Model is grey but textures are in MSG tex windows. After create new MSG and load back MSG with textures, textures are displayed on model.

**Comment by reduz** [comment]
is this for textures built-into the graph, or for uniforms?
Also is this for 2D or 3D?

**Comment by Obaran** [comment]
For 3D and for uniforms, there is video for sure.
https://youtu.be/DyDYeXt5MBg?t=1m3s
