### ISSUE TITLE
RAM usage gradually increases with the presence of sprites with bones

### ISSUE THREAD

**Issue by fauri** [okamstudio/godot#1637]
System: Windows 8.1 x64

I found this after left my computer stopped for a while. When I returned, I realized that the system was slower. I checked the task manager and saw that Godot was using more than 2GB of RAM.

After closed everything and reopen the project, while monitored the memory, I noticed the RAM usage keeps growing gradually, even without performing any action on Godot. After start trying to isolate the issue, I concluded that the guilty was the 2D bone system.

**Comment by reduz** [comment]
that sucks, can you make a small demo of a scene that causes this behavior and also tell me what you are doing to trigger it? I can't seem to reproduce it

**Comment by fauri** [comment]
Regards, Juan, thanks for replying. The gBot project (https://github.com/ndee85/gBot) is a good example of what is happening.

The memory only starts to increase when the "2D" tab is active (with the presence of bones). If you switch tabs ("3D" or "Script"), the RAM remains the same, but, if return to the "2D" tab, the memory increases again.

Cheers!

**Comment by fauri** [comment]
Today, I performed the same test on Ubuntu 14.10. Same problem.

If all the bones are removed (with the "clear bones" option), the problem stops.

**Comment by fauri** [comment]
I made a video to demonstrate:https://www.youtube.com/watch?v=0TVKpYr2_s4

**Comment by reduz** [comment]
this is definitely fixed now
