### ISSUE TITLE
GDscript function "free()" doesn't show up in the built-in help nor the auto-complete 

### ISSUE THREAD

**Issue by Ace-Dragon** [okamstudio/godot#1664]
So I know now that it's a real function, but you might not get the impression it is because the auto-complete doesn't have it when you start typing it and searching for it in the built-in help doesn't give any results.

Right now, with *remove_and_delete_child()* gone, people might otherwise end up wondering if there's no way to remove individual nodes in Godot.

Should be an easy one to fix.

**Comment by reduz** [comment]
great point, will add it
