### ISSUE TITLE
Visual Shader Editor; Reminder on issue of case where shaders may break

### ISSUE THREAD

**Issue by Ace-Dragon** [okamstudio/godot#1665]
All that you need to know is right here
https://github.com/okamstudio/godot/issues/1427

With Godot in beta, it would be nice to get this fixed for good.

**Comment by reduz** [comment]
I kept insisting, but you didn't answer to me if this was fixed

**Comment by Ace-Dragon** [comment]
Closing this because it's all fixed now

**Comment by okamstudio** [comment]
awesome :D

On Wed, Apr 29, 2015 at 6:07 PM, Ace-Dragon <notifications@github.com>
wrote:

> Closed #1665 <https://github.com/okamstudio/godot/issues/1665>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1665#event-293450763>.
>



-- 

*OkamStudio*
