### ISSUE TITLE
Reading lines from a text file crippled text, with no Latin letters

### ISSUE THREAD

**Issue by OlexiyKravchuk** [okamstudio/godot#1669]
When you try to read a text file which has a large text of letters, all read well, but if in the middle of the text, one character is not the Latin alphabet, then it may happen that two options I found
1) all of the text is empty,
2) tex is not empty but in a place where non-Latin character appears several different characters and half of the text of the entire text is not present
if not added at the end of a Latin symbol, the text after that character is lost, the option "1)" occurs when more than one character in the middle of the text, as well as in the case of certain characters in the middle of this example, "Ї"

**Comment by UsernameIsAReservedWord** [comment]
is your text file utf8 encoded ? if not, what default charset is used by your OS ? what is your OS and what text-editor did you use ?

**Comment by OlexiyKravchuk** [comment]
I did the same steps ...
1) using a script to create a text file in a specify a directory, and recorded in it text string that I created in the script,
2) Check the originlny file, run the project, and he read it and displayed good
3) open a file using a simple notepad and put in the middle my character,
4) Repeat start and it gave such a result

I use 32bit windows, and a simple notebook (it is impossible to set the desired encoding :()

**Comment by TheoXD** [comment]
If it doesn't work for you - doesn't necessarily mean there is anything wrong with godot. Here's what you do: You search google for any Unicode font (they usually include every character ever existed). Next, you change editor font in Settings->EditorSettings->Font . Next, you apply your font to any Label or LineEdit or Button. Now you're all set. I just did that and everything works, I can store Ukrainian characters and read them back, all from gdscript.
P.S. how large texts are we talking about? You overcomplicated everything that it makes it look like a completely different issue. Unicode fonts are large, 20mb in filesize, this is why it's not included by default.

**Comment by UsernameIsAReservedWord** [comment]
@OlexiyKravchuk : it seems to me that Windows Notepad saves to ANSI by default.
If TheoXD solution does not suffice, maybe you could look if the "Save as ..." dialog box of your Notepad does have Encoding option. And if not, maybe try using Notepad++ (http://notepad-plus-plus.org) instead.

**Comment by OlexiyKravchuk** [comment]
Thanks for the tips! Yes maybe it is a problem that forced the encoding uses a "notepad" by applying it to a file when I save the file after editing.
But for reference only. I did not expect to see the inside of the window Godot, after reading my character, I expected to see the text of the same as when the first start. Because I do not have any additional font, I did not even try to import it in Godot, I just tested how it record and how it is read if there is no characters of the Latin alphabet, I was only interested in operability with this on board, and the presence of the visual image I did not care for this specific case of the experiment. I do not worry about it because I know that the characters are there, no matter if they have a visually visible image to draw them on the screen, or no. I was interested in is the fact of working capacity in the first place, because the creation of the visible bodies of characters, I plan to do later in the complex.
PS probably correct encoding solve my problem, I'm going to move forward ...
PPS I hope my question does not look too strange, I would like to emphasize that in this case, I considered only the technical side of the problem, rather than visual, visibility ...

**Comment by TheoXD** [comment]
Notepad notifies you if there is any possible information loss because of encoding. When creating new file from gdscript it automatically sets the proper encoding. Maybe it saved text file as windows-1251 or something.. Just use utf-8 standard, because it's widely used.

**Comment by OlexiyKravchuk** [comment]
I conduct an audit, and the assumption is true, it is because of the coding, I change ANSI to UTF-8 and everything works as expected, thanks again!
