### ISSUE TITLE
Lighting Broke in Demos. hash b36e41cb7117757011e6f1ccc476ccc806219a58

### ISSUE THREAD

**Issue by antonyjones67** [okamstudio/godot#1671]
Surface 2 Pro I5 Intel Graphics Chipset.. Windows 8.

Problem seen in Kinematic_Char and Platformer. Tile blocks look black. When you turn off Mipmapping the textures become visible again.

**Comment by antonyjones67** [comment]
Looks like it is broken on my Gateway I5 GPU Nividia 650 as well.

**Comment by antonyjones67** [comment]
I'm sorry I may have given you a bad hash. I need to keep trying hashes. The above hash does seem to work. But the latest does not. I will keep trying different hashes.

**Comment by antonyjones67** [comment]
Author:		Juan Linietsky <reduzio@gmail.com>
Date:		4 days ago (4/6/2015 5:48:20 PM)
Commit hash:	b36e41cb7117757011e6f1ccc476ccc806219a58
Parent(s):	5d99e15e43

Added a PVRTC encoder for iOS

Contained in branches: master
Contained in no tag

This looks like it is the correct hash.

**Comment by TheoXD** [comment]
Yes I've also noticed, also SP2 xD
