### ISSUE TITLE
Unable to overwrite files

### ISSUE THREAD

**Issue by Crowley9** [okamstudio/godot#1672]
I recently learned about Godot and tried following the first tutorial. However, I was unable to do the simplest things and after a bit of investigation the problem seems to be that for some reason Godot is unable to overwrite scene and script files after they have been initially created. The .tmp files for those are created and updated, but the original file remains as it was upon creation. The command prompt window keeps showing the following message when I try to save a file in Godot:

ERROR: close: Condition ' rename_error ' is true.
At: drivers/windows/file_access_windows.cpp:133

I am running this under Windows XP with Service Pack 3.

**Comment by reduz** [comment]
Godot does not support Windows XP

**Comment by reduz** [comment]
Godot uses many "sane" Windows APIs that are not  present on windows XP, one of them is used for atomically renaming files that are being written to disk. Supporting Windows XP is too much work, and Microsoft does not offer support for it.
