### ISSUE TITLE
Font import fails when project on d drive

### ISSUE THREAD

**Issue by kbdavidson** [okamstudio/godot#1675]
Problem - fonts only import if project is located on C: drive.  This was present in 1.0 and is still an issue in 1.1.

To reproduce:
1) Create a new project on the D: drive
2) Import>Font
3) Set source path to c:/windows/Fonts/times.ttf by browsing with the .. button and selecting times.ttf. 
4) Set dest to test.fnt
5) Click import - gives "Couldn't save font" error and this is shown in console:
loadfrom: c:/Windows/Fontstimes.ttf
FT_Stream_Open: could not open `c:/Windows/Fontstimes.ttf'

(Note the missing delimiter between Fonts and times.ttf)

Repeat above but create the project on the C: drive
5) Click import - font imports successfully and following is shown in console:
loadfrom: C:/Windows/Fonts/times.ttf
W: 3 P: 3
W: 5 P: 5
...
total_chars: 191
Atlas size: 256,256

Note this issue is also mentioned by someone else in http://www.godotengine.org/forum/viewtopic.php?f=11&t=1615 .

**Comment by reduz** [comment]
will check these when back to windows

**Comment by eon-s** [comment]
If the font is on the same drive as the project, import works.
Sounds like it is using absolute path without changing/adding drive letter on windows
