### ISSUE TITLE
Alt + F4 doesn't close the editor on GNU/Linux

### ISSUE THREAD

**Issue by Calinou** [okamstudio/godot#1677]
When you press Alt + F4, the exit confirmation will appear, but once you click Quit, the editor will not exit. This can be reproduced several times.

**Comment by reduz** [comment]
i can't reproduce. What window manager are you using?

**Comment by TeddyDD** [comment]
For me it is the same. I'm using Linux Mint 17.1 with Cinnamon. (however closing editor from menu works well)

**Comment by GungnirInd** [comment]
I can reproduce; also on Mint 17.1 with Cinnamon 2.4.8.  Scene > Quit and the close button in the titlebar both work as expected.

**Comment by Calinou** [comment]
I'm using Xfce 4.10 with Xfwm.

**Comment by FEDE0D** [comment]
I'm using Linux Mint 17 with Mate 1.8.1. Closing with ALT+F4 is useless

**Comment by reduz** [comment]
Alt-f4 will just show the exit confirmation dialog.. It doesn't close even
after accepting it?

**Comment by FEDE0D** [comment]
Nope. Accepting the dialog does nothing.

**Comment by reduz** [comment]
can you try this again? I made the exit procedure cleaner, so this might work better now

**Comment by Calinou** [comment]
No, it still doesn't work. Even quitting it with the `X` button (window manager) is troublesome and throws some error messages:

```
freed code id 3
freed code id 5
freed code id 4
freed code id 6
freed code id 2
ERROR: set_stream_peer: Condition ' p_peer.is_null() ' is true.
   At: core/io/packet_peer.cpp:228.
freed code id 1
ERROR: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1733.
ERROR: clear: Resources Still in use at Exit!
   At: core/resource.cpp:345.
```

**Comment by jmf** [comment]
I am using Archlinux with i3 window manager and I can reproduce this, too.
When pressing alt-f4 (or the i3wm equivalent), the same dialog like when using Scene > Quit pops up. 
Scene > Quit dialog works, the one that pops up when pressing alt-f4 doesn't work.

**Comment by reduz** [comment]
it was some weird bug, alt-f4 takes your window out of focus
