### ISSUE TITLE
A possible scope problem

### ISSUE THREAD

**Issue by marcosbitetti** [okamstudio/godot#1681]
A make a sub-class, and I intend that it uses a main class export variable, but it's raises a error.

   	class BlockData:
   		var aabb = AABB()
   		var mesh = MeshInstance.new()
   	
   		func _init(pos):
   			mesh.set_custom_aabb( AABB(pos,Vector3(block_size,block_size,block_size)) )
   			print(mesh.get_aabb())
  	
   	export(Image) var override_mat_image
   	export(Vector2) var distribuiton = Vector2(0.2,0.2)
   	export(float) var block_size = 10

**Comment by UsernameIsAReservedWord** [comment]
I think the example you provided is incomplete.

**Comment by marcosbitetti** [comment]
Well, I correct  the markdown.
The code is just it. BlockData can't instanciate because block_size is undefined for class. But, accessible by ordinary functions.

**Comment by marcosbitetti** [comment]
A new problem that appears origin in same issue.
In commented lines has a variable called mesh_data, this variable is result of Copy and Past from caller function of this function.
My wrong to loose it, but... when I compile the editor can't detect that variable don't exists in function. And game freeze on screen!
Compiler can't see that this variable is out of this function, think it is a real variable and enter on a infinite loop search for unexistent value.

    func copy_vertices( mesh_index, surface, pos, scale):
    	var data = mesh_data_store[mesh_index]
    	var i = data.get_face_count()
    	while i>0:
    		i -= 1
    		var v0 = data.get_vertex( data.get_face_vertex(i,0) )
    		var v1 = data.get_vertex( data.get_face_vertex(i,1) )
    	#	var v2 = data.get_vertex( data.get_face_vertex(i,2) )
    	#	var uv0 = data.get_vertex_uv( mesh_data.get_face_vertex(i,0) )
    	#	var uv1 = data.get_vertex_uv( mesh_data.get_face_vertex(i,1) )

**Comment by reduz** [comment]
I think it does not make sense that you can access an export variable, since your original script can be instantiated a lot of times with different values, and the _init() function of your subclass has no way to know which one to takes values from

you can use a constant and that will work

**Comment by reduz** [comment]
assuming this is not a bug i guess, let me know if i misunderstood
