### ISSUE TITLE
[Bug] GDScript: Causing a call to a setter within the setter crashes Godot

### ISSUE THREAD

**Issue by philiplb** [okamstudio/godot#1685]
If I do something like this:

```
var percentage setget set_percentage

func set_percentage(new_percentage):
	self.percentage = clamp(new_percentage, -1.0, 1.0)
```

The setter calls himself again. This causes a hard crash. What I'd expect: An GDScript exception with Godot pointing to the evil line.

![godotcrash](https://cloud.githubusercontent.com/assets/1672238/7127919/71943876-e24b-11e4-81f4-6e4db6c0164a.png)

**Comment by reduz** [comment]
yes this should crash...
just do not use self and it will work, i think this issue in fact can be
detected by the compiler directly

**Comment by philiplb** [comment]
I mean an hard crash like in the now added screenshot above. Confused me for a moment. :)
I've a feeling that this should actually never happen by design?

**Comment by reduz** [comment]
Yeah it should be detected too

**Comment by philiplb** [comment]
Nice, thx. :)
