### ISSUE TITLE
Translation: can't select the language

### ISSUE THREAD

**Issue by Ijatsu** [okamstudio/godot#1687]
Hi,

I don't know if it's a bug or an undocumented change.
In 1.1 the "default" variable doesn't appear in the "locale" field after translations have been imported, in 1.0 the variable was present for language selection.
Nothing in the 1.1's project settings seems to let us change the language.

**Comment by reduz** [comment]
yes it was removed, Godot detects the locale from your computer and tries to use that. If not found, it will try to use the "fallback" locale.

If you really want to start in a specific language, use the "test" locale field.

**Comment by Ijatsu** [comment]
It worked as you say, but it feels odd. I conclude that the legit way to change the language is only by code.

By the way, the fact it tries to find the language is neat!
Thanks :)
