### ISSUE TITLE
[Bug?] Meshes imported as 3D mesh (.obj) have visible UVs

### ISSUE THREAD

**Issue by GlaDOSik** [okamstudio/godot#1692]
Test blend file, exported .obj file and test Godot project are here:
https://www.dropbox.com/s/gki3a4l73ywhgsf/VisibleUVs.zip?dl=0

It's a simple unwrapped sphere exported to obj. UVs aren't visible only if option Include UVs isn't checked in Blender exporter.

![uvs](https://cloud.githubusercontent.com/assets/3484686/7145397/5186953c-e2ec-11e4-8119-790a1168a11e.jpg)

**Comment by reduz** [comment]
Yes, this is unavoidable. Try exporting normals to your OBJ file and tell Godot to not generate them and it will work
