### ISSUE TITLE
no light in "2d isometric light" demo with release version of godot

### ISSUE THREAD

**Issue by SuperUserNameMan** [okamstudio/godot#1697]
Hi,

I tried with official export templates, as well as with compiled latest github.

When you run the "2d isometric light" demo using godot_relase, 2d lights do not appear.
They only appear with godot_debug version.

**Comment by SuperUserNameMan** [comment]
oh sorry, forgot to mention tested on Windows8.1, 64bits and 32bits versions.

GPU = Radeon R4

**Comment by Wend1go** [comment]
Hi SuperUserNameMan
What do you mean with "release version"? This feature was not yet present in the official 1.0stable release version.
Have you tried downloading the 1.1beta?

**Comment by SuperUserNameMan** [comment]
@Wend1go : 

by "release version" i mean when Godot is compiled with scons "target" option set to "release" :

`scons p=windows target=release tools=no`

The export template that we can download from the website contains a debug version and a release version of godot for each supported platforms.

Indeed I tried with official 1.1beta1 templates, as well as with latest source code available on github.

**Comment by okamstudio** [comment]
that's interesting, will have to check


On Fri, Apr 17, 2015 at 7:31 AM, SuperUserNameMan <notifications@github.com>
wrote:

> @Wend1go <https://github.com/Wend1go> :
>
> by "release version" i mean when Godot is compiled with scons "target"
> option set to "release" :
>
> scons p=windows target=release tools=no
>
> The export template that we can download from the website contains a debug
> version and a release version of godot for each supported platforms.
>
> Indeed I tried with official 1.1beta1 templates, as well as with latest
> source code available on github.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1697#issuecomment-93961061>.
>



-- 

*OkamStudio*

**Comment by reduz** [comment]
could reproduce... which is weird, will have to see what's going on
