### ISSUE TITLE
Loading old scene

### ISSUE THREAD

**Issue by honix** [okamstudio/godot#1698]
Like godot a lot, but sadly have some problems. :)

So, my problem is by steps:

- Open scene and do some changes (like add new node)
- Save it
- Open it again
- Boom, this screen-shoot below, and scene still no changes (no new node)

Problem solved by restarting engine

It is april 11 build, but i had same problem in 1.1 beta
ps - project traveled version to version, i think it creates problem 
![default](https://cloud.githubusercontent.com/assets/11596541/7188833/2d88d58a-e483-11e4-9bbf-d94c2d951c14.PNG)

**Comment by reduz** [comment]
.. is a mystery..

**Comment by honix** [comment]
This screen shows how console look when i just open project

![default](https://cloud.githubusercontent.com/assets/11596541/7189039/ae46c79e-e484-11e4-84b0-c90e3da1221e.PNG)

**Comment by reduz** [comment]
No idea what might be going on, can you make a small demo or give more info
that shows what is happening?

**Comment by honix** [comment]
Aha! 

I think i find it. I had a line in code that preload( same scene it is ). Comment it and save/open problem gone
![default](https://cloud.githubusercontent.com/assets/11596541/7189240/45b8b514-e486-11e4-8469-4c4128960438.PNG)

**Comment by honix** [comment]
I used it for restarting game

**Comment by okamstudio** [comment]
try using an autoloaded scene or script

On Thu, Apr 16, 2015 at 4:18 PM, honix <notifications@github.com> wrote:

> I used it for restarting game
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1698#issuecomment-93819171>.
>



-- 

*OkamStudio*

**Comment by honix** [comment]
Yep! I have one global script to operate scenes and global vars. Then i just need to move preload() from mainScene to global.

Thanks for help!
