### ISSUE TITLE
Support for Opus audio codec

### ISSUE THREAD

**Issue by Calinou** [okamstudio/godot#1706]
<http://www.opus-codec.org/>

> Opus is a totally open, royalty-free, highly versatile audio codec. Opus is unmatched for interactive speech and music transmission over the Internet, but is also intended for storage and streaming applications. It is standardized by the Internet Engineering Task Force (IETF) as RFC 6716 which incorporated technology from Skype's SILK codec and Xiph.Org's CELT codec.
>
> Opus can handle a wide range of audio applications, including Voice over IP, videoconferencing, in-game chat, and even remote live music performances. It can scale from low bitrate narrowband speech to very high quality stereo music. Supported features are:
>
> * Bitrates from 6 kb/s to 510 kb/s
> * Sampling rates from 8 kHz (narrowband) to 48 kHz (fullband)
> * Frame sizes from 2.5 ms to 60 ms
> * Support for both constant bitrate (CBR) and variable bitrate (VBR)
> * Audio bandwidth from narrowband to fullband
> * Support for speech and music
> * Support for mono and stereo
> * Support for up to 255 channels (multistream frames)
> * Dynamically adjustable bitrate, audio bandwidth, and frame size
> * Good loss robustness and packet loss concealment (PLC)
> * Floating point and fixed-point implementation

Opus compression performs better than Vorbis compression, which is the main rationale to implement it.

As far as I know, Godot does not support Opus, neither the Opus container (.opus) which is preferred nor Ogg Opus (.ogg). Please correct me if I'm wrong.

**Comment by reduz** [comment]
I wonder if Opus uses more or less Cpu than Vorbis...

**Comment by Calinou** [comment]
Opus FAQ says:

>  Opus is using too much CPU for my application. What can I do?
> -------------------------
> First don't panic and don't start writing assembly just yet.
>
> It's possible that you're just not using the right set of options.
>
> If you're targeting an embedded/mobile platform, chances are the fixed-point build will be faster, so make sure you're using --enable-fixed-point or defining FIXED_POINT in the build system.
>
> Opus also has a complexity option that can trade quality for complexity. The default is highest quality and highest complexity. You can control this using OPUS_SET_COMPLEXITY() (see doc for details). If all else fails and you need to optimize the Opus code, see the next question.

**Comment by reduz** [comment]
but question is, can it use less cpu than Vorbis? Otherwise there is not
much of a point adding it..

**Comment by Ace-Dragon** [comment]
I'm really not sure if it would be worth adding this, as this format is currently unknown to most of the music/sound making software that is out there (compared to .ogg which is far more common and is supported by all of the major OS's).

Though it took .ogg a number of years before its use became widespread, .opus might be able to do the same in 5 years or so.

**Comment by punto-** [comment]
I think it's still worth it if the files are smaller or if it uses less
CPU, just because it'll be an option to export to in platforms that care
about installation size or CPU usage. Musicians don't need to know what
goes inside the final package :p

**Comment by seadra** [comment]
Opus 1.1 improved the decoding speed by ~70% and 1.1.1 tree has further ARM optimizations, and they only started doing optimizations recently --it will only get better. I vaguely remember a benchmark mentioning Opus decoding being ~30% slower *at the same bitrate* (opus usually requires a [lower bitrate](http://en.wikipedia.org/wiki/Opus_(audio_format)#Quality_comparison_and_low_latency_performance) for the same quality) from their mailing list.

I should add that the compression Opus uses is best plus it's completely free.

**Comment by freemanfromgodotengine** [comment]
I would welcome a new codecs/formats but rather for the SamplePlayer, because it feels a bit limited with WAV and ADPCM compression only.
If Opus can be used in that area, go for it.

**Comment by okamstudio** [comment]
SamplePlayer needs uncompressed or ADPCM compressed samples, Opus, Vorbis,
etc are extremely inefficient for this

On Sun, Apr 19, 2015 at 12:27 PM, freemanfromgodotengine <
notifications@github.com> wrote:

> I would welcome a new codecs/formats but rather for the SamplePlayer,
> because it feels a bit limited with WAV and ADPCM compression only.
> If Opus can be used in that area, go for it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1706#issuecomment-94288002>.
>



-- 

*OkamStudio*

**Comment by freemanfromgodotengine** [comment]
okamstudio: 
> SamplePlayer needs uncompressed or ADPCM compressed samples, Opus, Vorbis,
> etc are extremely inefficient for this"

You are right that it's inefficient in CPU usage, but when compromise in storing space vs decoding speed is needed and mono files (ADPCM) are not an option that can be used, I would not mind to be able to use Vorbis/MP3/Opus/Flac or something else in SamplePlayer, even if it more CPU's power hungry.

**Comment by trollworkout** [comment]
According to Hydrogen Audio, Vorbis codec is unstable and may at times become CPU intensive and according to same site Opus has more even althorithmic decoding time < 22ms. Opus 1.1 brings decoding closer to MP3/Vorbis. Most major browsers all support or will support Opus as it's part of the HTML5 standard. So WebGL/HTML5 games will have it covered. Opus has lowest bitrate perfect for multiplayer chat and also has highest lossless audio quality perfect for game music. 

I would say if you have the time then do add Opus support . I'd even go as far as replacing Vorbis with Opus.  Opus is a codec that does it all.

**Comment by reduz** [comment]
There is a pending rewrite of the audio stream subsystem as it currently
does not allow the same stream to be played more than once simultaneously..
Oncr that is done, adding opus can be a good idea, otherwise the code will
have to be rewritten later

**Comment by trollworkout** [comment]
Having Opus def a good thing as is so versatile but tbh I just found out Godot so I'm still learning so many features  I can't complain.

**Comment by seadra** [comment]
Audio stream rewrite has recently landed, so I guess this is a good time to bump this issue.

**Comment by reduz** [comment]
Yeah it should be possible to add Opus soon, though must fix Theora first
which broke due to this

**Comment by reduz** [comment]
By the way is there any alternative to Theora that can be software decoded
on mobile, and is not very CPU intensive?

**Comment by seadra** [comment]
Not sure about software decoding on arm, but [many ARM SOCs](http://wiki.webmproject.org/hardware/socs) have hardware VP8 decoding support

**Comment by reduz** [comment]
Godot already supports the native playback of codecs in Android and iOS,
but those just open a player and return when playback is done.. theora is
mostly used for cpu decoding because it can be rendererd to textures to do
some effects

**Comment by okamstudio** [comment]
By the way, I think the audio API is ready for implementing OPUS. Is anyone
interested in doing this?


On Thu, Sep 10, 2015 at 1:47 PM, Juan Linietsky <notifications@github.com>
wrote:

> Godot already supports the native playback of codecs in Android and iOS,
> but those just open a player and return when playback is done.. theora is
> mostly used for cpu decoding because it can be rendererd to textures to do
> some effects
>
> On Thu, Sep 10, 2015 at 1:45 PM, seadra <notifications@github.com> wrote:
>
> > Not sure about software decoding on arm, but many ARM SOCs
> > <http://wiki.webmproject.org/hardware/socs> have hardware VP8 decoding
> > support
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/issues/1706#issuecomment-139306440
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1706#issuecomment-139306954>.
>



-- 

*OkamStudio*

**Comment by vnen** [comment]
I would like to do this for the task seems interesting to me. But, to be honest, I would do this as a learning exercise as I have no experience in this field.

So, if there is anyone more apt who wants to do this (maybe already done it), I could hand the task over.

**Comment by vnen** [comment]
I got Opus codec working on Godot, hopefully soon will be able to open a PR. I just want to make sure it works in every platform (Emscripten is giving me a headache).

**Comment by RealProgrammers** [comment]
How many Dhrystones does it need for, say, the 504Mbit/S mode? Or if another takes more, I need to know the amount of power I need and how the quality differs between floating-point and fixed point.
