### ISSUE TITLE
Light2d shows clipping when displayed on top of tilemaps

### ISSUE THREAD

**Issue by Cybolic** [okamstudio/godot#1722]
Moved from issue #1682.

Lights turn off or clip at certain zoom levels.
It seems to be related to display scaling and/or tile quadrant size.

**Comment by Cybolic** [comment]
Possibly related as moving the editor view over tile quadrant edges seem to also trigger it;
Shadow maps seem to drop resolution quite a bit under some circumstances: https://www.youtube.com/watch?v=GWLItyLemRU

**Comment by WatIsDeze** [comment]
Same problem showing up here, although I can't test it. This even happened in-game once, while most of the time it only shows up in the editor.

**Comment by reduz** [comment]
will be testing this asap

**Comment by WatIsDeze** [comment]
I've got a screenshot, where it does this in fullscreen(thus resizing my window), but actually works fine when using the default 640x480 resolution.

![screenshot_2015-04-23_16-36-34](https://cloud.githubusercontent.com/assets/10252874/7299579/1798498c-e9d7-11e4-81a0-9c5588c4f391.png)
