### ISSUE TITLE
A bug in the function "unproject position (Vector3)".

### ISSUE THREAD

**Issue by OlexiyKravchuk** [okamstudio/godot#1725]
Function "Vector2 unproject position (Vector3 world_point)" calculates incorrectly when camera is directed his back to the object, but the point is still calculated on the screen when you look in the opposite direction of the 3D object.

**Comment by reduz** [comment]
i can't reproduce (or may not understand), can you make a simple demo scene showing how this fails?

**Comment by OlexiyKravchuk** [comment]
I do not know how transfer the file, I still do not know how to use git hub, I attempt such a service
http://www.ex.ua/89855656
  I hope it will work to give you a demo.

I added to the windows management demo GUI object it is attached at the 3D space above cube around and I added frames for see well it. Overview mode and rotate the camera to 180 degrees and you will see double.
PS there is only one center, but you will see the two in front above test cube and behind you in an empty space, but only the one that over a cube real, and what is behind this is a bug.

**Comment by reduz** [comment]
i'm not sure what to do with that site, can't figure out how to get the file

**Comment by OlexiyKravchuk** [comment]
excuse me for a long time no response, so I did the instructions in the screen shot.
http://snag.gy/YSXIi.jpg

**Comment by reduz** [comment]
![exmail](https://cloud.githubusercontent.com/assets/6265307/7373193/724f3ef8-eda1-11e4-9653-366a5d229b86.png)

All I see when I click in the above link is this

**Comment by OlexiyKravchuk** [comment]
Oh, I see, it was strange, I'll try to find another service to give you a file, but I do not know what I can use for this, but I'll try to find something ...

**Comment by OlexiyKravchuk** [comment]
I found a new one service and register there, I hope it will, without strangeness. =)
https://www.dropbox.com/s/4hmqktuw4jrp6zq/window_management.7z?dl=0

**Comment by reduz** [comment]
OK, I see what you mean now, but this issue is impossible to avoid due to this being a linear transform, there is no "invalid" position when behind the camera. I added a function to the camera: is_position_behind(), so you can easily tell if what you are un projecting should not be visible.
The code in your demo was changed to his:

```python
	var pos = get_global_transform().origin
	if (get_viewport().get_camera().is_position_behind( pos )):
		NAME_BILLBOARD.hide()
	else:
		NAME_BILLBOARD.show()

		NAME_BILLBOARD.set_pos(get_viewport().get_camera().unproject_position(get_global_transform().origin))
```

**Comment by vitorbalbio** [comment]
@Calinou Maybe someone should document it here?
https://docs.godotengine.org/pt_BR/stable/classes/class_camera.html#class-camera-method-unproject-position

Having been getting problems with it for a while until i find this.
