### ISSUE TITLE
Ray Cast in physics 2d fails sometimes

### ISSUE THREAD

**Issue by Biliogadafr** [okamstudio/godot#1726]
Sometimes raycast produce incorrect results. In my case I'v tried to check if enemy can see the player if ray hits him. Sometimes it doesn't see him, when should. Sometimes it can see him through walls(harder to reproduce, but I can do setup in game if you want).  So sometimes ray doesn't hit object when it should, and sometimes it goes through walls.

This is simple scene which reproduce bug in godot 1.1beta1:
https://github.com/Biliogadafr/Godot-Tests/tree/master/RayCastTest
This is how it looks:
![raycastbug](https://cloud.githubusercontent.com/assets/10543859/7284018/400b056a-e943-11e4-981d-9a877b66530a.gif)
When no line is drawn then raycast doesn't produce a result. (ray from center of the scene to icon with circle collider)

**Comment by Biliogadafr** [comment]
Also I would like to note that RayCast2D node behaves exactly the same.

**Comment by reduz** [comment]
I guess it's time to write a raycast tutorial..

**Comment by okamstudio** [comment]
I owe my apologies to you, this was a serious bug, thanks enormously for
taking the time to report it
