### ISSUE TITLE
In code editor sometimes whole line is selected when it should not

### ISSUE THREAD

**Issue by Biliogadafr** [okamstudio/godot#1727]
I often have a problem when I do some quick copy/paste of variable from some lines around. I do this whith 'double click' -> ctrl+c -> 'click' -> ctrl-v.     But if I do this fast (usually I do), it selects the whole line and replace it with clipboard contents.   
Godot 1.1beta1
![codeeditbug](https://cloud.githubusercontent.com/assets/10543859/7284210/ad5b1f6e-e944-11e4-907c-6ea42418e8d7.gif)

**Comment by reduz** [comment]
this is a feature, triple click selects the whole line.. but maybe should check if the mouse moved a bit

**Comment by Biliogadafr** [comment]
Yes. It's a good feature. I just expected that it will work if 3 clicks is done on one line, not 2 clicks on one line and 1 on the other :).
