### ISSUE TITLE
Script editor

### ISSUE THREAD

**Issue by BBric** [okamstudio/godot#1732]
- 'Window > Close' don't allow to close without saving.
- 'File > Save As' don't save the current tab, it can even save with the content of a closed file.
- 'Window > Alt<tab>' and 'Window > Move left/right' don't works on Linux (or rarely).

**Comment by BBric** [comment]
Move left/right works now, but not the tab change (with the digital pad or the top keys).

**Comment by okamstudio** [comment]
I'll check again today. I'm not sure how to improve this better, as some
OSs use shortcuts for that stuff for their own

On Tue, Apr 28, 2015 at 3:38 PM, BBric <notifications@github.com> wrote:

> Move left/right works now, but not the tab change (with the digital pad or
> the top keys).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1732#issuecomment-97165420>.
>



-- 

*OkamStudio*

**Comment by okamstudio** [comment]
or some keyboard layouts need that (alt+number)

On Tue, Apr 28, 2015 at 3:44 PM, Juan Linietsky <juan@okamstudio.com> wrote:

> I'll check again today. I'm not sure how to improve this better, as some
> OSs use shortcuts for that stuff for their own
>
> On Tue, Apr 28, 2015 at 3:38 PM, BBric <notifications@github.com> wrote:
>
>> Move left/right works now, but not the tab change (with the digital pad
>> or the top keys).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/okamstudio/godot/issues/1732#issuecomment-97165420>.
>>
>
>
>
> --
>
> *OkamStudio*
>



-- 

*OkamStudio*
