### ISSUE TITLE
Physics2D: "apply_impulse()" doesn't wake up rigid body sometimes.

### ISSUE THREAD

**Issue by Biliogadafr** [okamstudio/godot#1740]
Test scene can be found here: https://github.com/Biliogadafr/Godot-Tests/tree/master/PhysWakeUpTest
At is almost the same like in this issue: https://github.com/okamstudio/godot/issues/1739
But in this case balls are trying to jump on RigidBody (instead of character) and first 'jump' happens after 5 seconds (instead of 3) after scene is started... well... actually it doesn't.

**Comment by marcosbitetti** [comment]
I have the same issue, and solve it manualy wakeup object.
