### ISSUE TITLE
Shader Graph fails on display UV

### ISSUE THREAD

**Issue by marcosbitetti** [okamstudio/godot#1742]
![1 1](https://cloud.githubusercontent.com/assets/85936/7339478/de2ce230-ec46-11e4-9580-40b0a1e8e0f2.gif)

The UV dont repeat in this view.
It's show wrong in editor, but when I compile that run fine!
And sometimes that I reimport image its work fine again, until I not add a new node.

**Comment by reduz** [comment]
i think this depends solely on the image resource texture repeat flag, can you make a small test scene for me to debug?

**Comment by marcosbitetti** [comment]
https://github.com/marcosbitetti/Godot_Shader_Test_Project
In this scene all runing fine. But when i try to edit shader the issue begin

**Comment by reduz** [comment]
wow you found a really old bug, glad I could fix it
