### ISSUE TITLE
visual artifact in RichTextLabel menu

### ISSUE THREAD

**Issue by GameCy** [okamstudio/godot#1746]
Version 1.1.beta1.42d41a3fbc

Problem:
The "RichText" menu is drawn on top of the Lock/Unlock object icons

How to reproduce
Create a new RichTextLabel. While it is selected, a small menu appears (parseBBCode, clear) on top, next to the Lock Object icon.

Setup:
On windows Vista, ATI Radeon HD5450

**Comment by reduz** [comment]
oh this menu is gone in github, so this bug no longer applies i guess
