### ISSUE TITLE
draw_primative problem

### ISSUE THREAD

**Issue by otorp** [okamstudio/godot#1749]
I was trying to draw a triangle with this:

extends Node2D

func _draw():

	draw_primitive(Vector2Array([Vector2(0,100),Vector2(100,300),Vector2(90,0)]),ColorArray([Color(1,0,0),Color(1,0,0),Color(1,0,0)])) 
	pass

func _process(delta):
	update()
func _ready():
	set_process(true)

which doesnt  draw anything and romullox_x kindly provided workaround:

extends Node2D
var myColorArray = ColorArray()

func _draw():
	for color in [Color(1,0,0),Color(1,0,0),Color(1,0,0)]:
		myColorArray.push_back(color)
	draw_primitive([Vector2(0,100),Vector2(100,300),Vector2(90,0)], myColorArray)
pass

func _process(delta):
	update()
func _ready():
	set_process(true)

**Comment by romulox-x** [comment]
I fixed the problem in this PR.
https://github.com/okamstudio/godot/pull/1750
