### ISSUE TITLE
Dynamic preload

### ISSUE THREAD

**Issue by BBric** [okamstudio/godot#1758]
It could be useful to preload classes dynamically.

At present :
```GDScript
var s = "A.gd"
var t = preload(s) # Parser Error: Expecting string constant as preload argument
```

Example:
```GDScript
var s = ["A.gd", "B.gd", "C.gd"] # could be generated dynamically with Directory
for i in s:
    Globals.set(i.replace(".gd",""), preload(i))
```

**Comment by reduz** [comment]
then it would not be a preload, use load() instead :)

**Comment by BBric** [comment]
Arf, i was used to use load() with images and i had forgotten this form. It works like expected, sorry.
