### ISSUE TITLE
Problem after importing projects from 1.0 to 1.1 beta 1.

### ISSUE THREAD

**Issue by OlexiyKravchuk** [okamstudio/godot#1760]
I noticed when I opened the project (kinematic_char) 3D in 1.1 beta1 that cubes lifts and mushroom on top of the level, completely invisible at first I thought they were gone completely, but then faced with an invisible platform lift, and it works just invisible mesh (is not visible in any editor or in the running scene), also have a problem with (3D particles) of materials no longer work there, and the particles look like simple white squares, I spent testing on different computers this occurs everywhere the same.

**Comment by reduz** [comment]
i screwed up and forgot to initialize a variable. If you have an object that breaks, check the extra_cull_margin property and make sure it's 0

**Comment by OlexiyKravchuk** [comment]
1) I checked in elevators and mushroom these values are (16384) but Cubio is equal to (1) and it is visible, but it would not have (0) What's wrong with Cubio?
2) I have checked and other objects with which the particle was broken, and the test object, it was three nodes of particles with different materials, and their property was so ... the first was (0), the second (1), the third (0) all these three objects are almost identical, but in the past they had different materials, and they are now completely white, even those who have assets equal to (0), is this normal?

**Comment by OlexiyKravchuk** [comment]
In addition, I made an attempt to change this value everywhere on (0), where it was not equal to this, and it had no effect, no in the editor or in playing mode, even after I save and a complete restart.

**Comment by reduz** [comment]
you need the new version in github, otherwise it will make no difference. I
just tested doing what you mention and it seems to fix everything

**Comment by OlexiyKravchuk** [comment]
I just checked everything again, and the problem with the particles of 3D still is, now as before the white squares, and after the method call to show () when they are hidden in the scene, they become square spots on the objects, but the squares of the particle in space do not appear.

By the way for a long time wanted to say that (particle 3D) ignored the pause mode and continue to work ...
