### ISSUE TITLE
Analysis of Godot Engine's Source Code by PVS-Studio static code analyzer

### ISSUE THREAD

**Issue by InkViziT0r** [okamstudio/godot#1768]
Development team of proprietary PVS-Studio C/C++ static analyzer presents their report on the source code of Godot engine in the article, which contains the review of the most suspicious code fragments they discovered.

You can read article on the official site:
http://www.viva64.com/en/b/0321/

**Comment by InkViziT0r** [comment]
I have not found bugtracker on project's site and therefore wrote here.

**Comment by swenner** [comment]
This is the official bugtracker. :-)

Very interresting report. Some of the issues should probably be filed as separate issues.
