### ISSUE TITLE
currently-selected editor tab is saved in the scene file

### ISSUE THREAD

**Issue by adolson** [okamstudio/godot#1770]
The currently-selected editor tab get saved into each scene. Example:

```diff
diff --git a/jstest.xscn b/jstest.xscn
index f38d216..6507dbb 100644
--- a/jstest.xscn
+++ b/jstest.xscn
@@ -165,7 +165,7 @@
                                <resource  resource_type="Script" path="res://jstest.gd">  </resource>
                                <dictionary  shared="false">
                                        <string> "__editor_plugin_screen__" </string>
-                                       <string> "Script" </string>
+                                       <string> "2D" </string>
                                        <string> "__editor_plugin_states__" </string>
                                        <dictionary  shared="false">
                                                <string> "2D" </string>
```

If you save the file on the Script tab, it changes the scene file, but it doesn't automatically return you to the Script tab when you re-open the scene in the editor.

What is the intended behavior?

**Comment by reduz** [comment]
yeah, all this code will be rewritten in 1.2 though

**Comment by fazjaxton** [comment]
I would much prefer that this information was not stored in the scene file.  I would like to be able to version-control a scene, and .gitignore the separate file that the editor layout is stored in.

**Comment by akien-mga** [comment]
+1 for not registering the currently-selected editor tab (or currently selected script file in the Scripts tab) in the scene. It's annoying when trying to have clean git commits that this info gets stored in the main scenes that you load to edit your code.

**Comment by akien-mga** [comment]
The feature discussed here has been removed in e9bbb97a, so the bug report can be closed IMO.
