### ISSUE TITLE
[Feature Request] (area), and (area 2D), no layers.

### ISSUE THREAD

**Issue by OlexiyKravchuk** [okamstudio/godot#1771]
The forum here (http://www.godotengine.org/forum/viewtopic.php?f=11&t=1911&p=9138#p9138), as a result of the conversation found out that (area 2D) and (area) do not have the properties of layers it is so obvious that they are would be there in demand.

**Comment by reduz** [comment]
good point.. wonder why...

**Comment by reduz** [comment]
will have to add

**Comment by reduz** [comment]
added, closing
