### ISSUE TITLE
[1.1rc1] Delete animations keyframes

### ISSUE THREAD

**Issue by honix** [okamstudio/godot#1780]
Just resave my project in 1.1rc1 and all animation key-frames was deleted. Then at run do a massive errors in animation.cpp

ps. Work fine on 25 april build. All scenes saved in .xml format

**Comment by Zamaroht** [comment]
I'm having the same issue. The main consequence I noticed is that the 'Autoplay On Load' feature seems to be broken.
For example, try to open the 2d/splash example. If you run it right after you open it, it runs fine. If you select any AnimationPlayer, disable Autoplay, then enable it again, all the animations stop working. They work fine in the editor though.

**Comment by okamstudio** [comment]
are you saving to xml? a push was submitted that fixes an issue with this


On Sun, May 3, 2015 at 8:47 PM, Nicolas Laurito <notifications@github.com>
wrote:

> I'm having the same issue. The main consequence I noticed is that the
> 'Autoplay On Load' feature seems to be broken.
> For example, try to open the 2d/splash example. If you run it right after
> you open it, it runs fine. If you select any AnimationPlayer, disable
> Autoplay, then enable it again, all the animations stop working. They work
> fine in the editor though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1780#issuecomment-98557636>.
>



-- 

*OkamStudio*

**Comment by reduz** [comment]
i think this is fixed, please try again on github

**Comment by Zamaroht** [comment]
I have just compiled using the last commit and can confirm it is working correctly now.

**Comment by guilhermefelipecgs** [comment]
For me is fixed as well.
