### ISSUE TITLE
[1.1rc1] Export templates for X11 release are bigger than the debug versions

### ISSUE THREAD

**Issue by swenner** [okamstudio/godot#1781]
linux_x11_64_debug is 6MB, linux_x11_64_release is 26.9 MB.

The release version should be smaller. I think the symbols do not get stripped or the files are swapped or both.

The bug applies to the 32 bit version too.

**Comment by freemanfromgodotengine** [comment]
I can confirm.
Linux 64-bit export:
* Debug version - **23.6** MB
* Release version - **43.9** MB

Windows 64-bit export:
* Debug version - 39.6 MB
* Release version 40.8 MB

Android's export are both the same size.

Looks like "debug" button got a reversed action for Linux.
 :)

**Comment by reduz** [comment]
guess either not being stripped or a problem with upx, will have to check this

**Comment by swenner** [comment]
This bug is still present in 1.1rc3.
