### ISSUE TITLE
Incorrect wording on 1.1 rc1 Website announcement

### ISSUE THREAD

**Issue by NateWardawg** [okamstudio/godot#1782]
Hey Juan, I was just reading the announcement on the website.

1) For "it’s your change to", "change" should be "chance".

2) "1.0 stable." should be "1.1 stable"

**Comment by NateWardawg** [comment]
For quick reference so there's no confusion, it's this one
http://www.godotengine.org/wp/godot-1-1-rc1/

**Comment by akien-mga** [comment]
Confirmed.

**Comment by reduz** [comment]
fixed
