### ISSUE TITLE
error saving a scene with animationplayer

### ISSUE THREAD

**Issue by GrandFunkR** [okamstudio/godot#1785]
After getting saved an xml scene containing an animationplayer node, opening again the scene an error is returned and the animationplayer no longer has an empty track.

ERROR: _set: Index track out of size (tracks.size()).
   At: scene/resources/animation.cpp:69.
ERROR: _set: Index track out of size (tracks.size()).
   At: scene/resources/animation.cpp:69.
ERROR: _set: Index track out of size (tracks.size()).
   At: scene/resources/animation.cpp:69.

**Comment by honix** [comment]
Link to same problem - https://github.com/okamstudio/godot/issues/1780

**Comment by reduz** [comment]
i think this is solved, please test on github

**Comment by GrandFunkR** [comment]
solved. TY
