### ISSUE TITLE
[1.1rc1] Exported GDscript float parameters with bounds are exported as integer

### ISSUE THREAD

**Issue by swenner** [okamstudio/godot#1787]
export(float, 0.0, 10.0) var speed = 0.3

Can only be set to integer values.

Setting no bounds works fine:
export var speed = 0.3

**Comment by reduz** [comment]
yes because increment is by default 1.0, add a third parameter with your desired increment

**Comment by swenner** [comment]
Okay, thank you for the clarification. Where can I find the documentation for the export keyword?

**Comment by guilhermefelipecgs** [comment]
https://github.com/okamstudio/godot/wiki/gdscript#exports

**Comment by swenner** [comment]
Thank you!
