### ISSUE TITLE
wrong project is played if a  data.pck file exist in the project folder [1.1rc1]

### ISSUE THREAD

**Issue by swenner** [okamstudio/godot#1788]
If you press run (F5) in the editor and in the same folder of you scene file a data.pck file exist, then the pck file is loaded insted of the scene you are currently editing.

The data.pck file should be ignored in the editor

**Comment by reduz** [comment]
the editor does not allow exporting the pck inside the project folder, so this is generally not a problem.. for this to happen I guess you moved it there yourself

**Comment by okamstudio** [comment]
oops closed the wrong issue, well, this should still not be an issue

On Mon, May 4, 2015 at 11:18 AM, Juan Linietsky <notifications@github.com>
wrote:

> Closed #1788 <https://github.com/okamstudio/godot/issues/1788> via 6f8bd89
> <https://github.com/okamstudio/godot/commit/6f8bd899311d459b9e391b4acf72ccfa5cc1d806>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1788#event-296284726>.
>



-- 

*OkamStudio*
