### ISSUE TITLE
use a text (instead of binary) representation for scene files

### ISSUE THREAD

**Issue by swenner** [okamstudio/godot#1791]
It would be great if the scene files would be in a text representaion (json, xml, ...) so that they can be better managed by a version control system.

The file could be turned into the current binary format for export afterwards.

**Comment by TeddyDD** [comment]
You can save scene as xml

**Comment by swenner** [comment]
Oh, I didn't know that. Thanks a lot.

This issue can be closed.

**Comment by guilhermefelipecgs** [comment]
Or you can save with xscn too.

**Comment by swenner** [comment]
What's the advantage of xscn?

**Comment by guilhermefelipecgs** [comment]
I think that is the same but I prefer to use xscn to scenes and xml to resources for organization purpose. The file generated should be equal for both cases.

**Comment by swenner** [comment]
Thanks!
