### ISSUE TITLE
Wrong use of | instead of ||

### ISSUE THREAD

**Issue by ricpelo** [okamstudio/godot#1805]
In scene/gui/text_edit.cpp, lines 492 and 563, I see:

    if (cc== '"' | cc == '\'') {

Use of | in that context seems to be wrong. It need to be replaced by ||.

**Comment by ricpelo** [comment]
Pull request to solve the issue:

https://github.com/okamstudio/godot/issues/1805

**Comment by Dickby** [comment]
That doesn't make any diffenence, in this case.

**Comment by SuperUserNameMan** [comment]
@Dickby : do compilers optimize it the same way ? (I mean, with `( A || B )`, evaluation of B is skipped if A is true. Do they do the same with `( A | B )` ?

**Comment by Dickby** [comment]
@SuperUserNameMan : Good Point. I have to check that.

**Comment by Dickby** [comment]
My apologies ,my first comment was wrong. 
gcc doesn't optimize it the same way. I haven't checked other Compilers.
