### ISSUE TITLE
Compiler errors when "theora=yes" caused by memcpy

### ISSUE THREAD

**Issue by ricpelo** [okamstudio/godot#1806]
When I compile with "theora=yes" in order to enable Theora support, I get the following compile error message:

    drivers/theoraplayer/video_stream_theoraplayer.cpp:391:38: error: 'memcpy' was not declared in this scope
    memcpy(ptr, f->getBuffer(), imgsize);
                                       ^

I can workaround this issue on Linux adding the following line:

    #include <string.h>

but I don't know if this could be the solution for all the other platforms.

**Comment by punto-** [comment]
I think the correct way to solve it would be to use "copymem" and implement
that as memcpy whenever it's available. I was lazy and put memcpy there
because it was a lot faster than the default implementation of copymem.

**Comment by ricpelo** [comment]
I prepared a PR with your solution, @punto-  ;).
