### ISSUE TITLE
Unable to convert String to float using float(String)

### ISSUE THREAD

**Issue by ricpelo** [okamstudio/godot#1809]
According to https://github.com/okamstudio/godot/wiki/class_float, I can convert a String into a float using the function:

    float float(String from)

However, if I try this simple example:

    var f = float("25")

I get the following error message:

    Invalid call. Unexisting 'float' constructor.

**Comment by ricpelo** [comment]
However, using ```var f = "25".to_float()``` works as expected.

**Comment by ricpelo** [comment]
Mmmh, ```var f = int("25")``` doesn't work, neither... Maybe I misunderstood the documentation?

**Comment by ricpelo** [comment]
OK, tested: ```float(int from)``` and ```float(bool from)``` works, but ```float(String from)``` doesn't. So it does ```int(String from)```.

**Comment by reduz** [comment]
Hmm.. I see i clearly made a mistake. Let me fix it..
