### ISSUE TITLE
Fullscreen doesn't work in OS X

### ISSUE THREAD

**Issue by ricpelo** [okamstudio/godot#1811]
Setting Scene -> Project Settings -> display -> fullscreen to "on", doesn't do anything in OS X. Pressing F5 or F6 runs the project/scene windowed.

It works well on Linux, though.

(I'm using OS X Yosemite (10.10.3).)

**Comment by ricpelo** [comment]
Tested on git HEAD.

**Comment by reduz** [comment]
i'm not very sure how this works in OSX, and don't have a  mac to test, do
you think you could help out fix this?

**Comment by ricpelo** [comment]
I'm a totally newbie in OS X programming :(. Do you have any clues? I can try some tweakings and compile in my Mac to see what it does. Do you know in what files may I start to look at?

**Comment by punto-** [comment]
There's a window manager demo to test all that stuff, one of the buttons
makes the window fullscreen. See what function that button is calling (from
OS probably). When you use settings (or command line) to go fullscreen, the
actual call would happen on OS_OSX::initialize (on platform/osx/os_osx.cpp,
see examples on OSWindows::initialize and OS_X11::initialize). See if
that's happening. initialize() should call the same thing that gets called
on the WM demo I guess. Fullscreen on OSX was kinda tricky, there was more
than one way to do it, but I think you can test all of them on that demo.

**Comment by ricpelo** [comment]
I think I get it! I tried using toggleFullScreen: method and it works (at least, in my OS X Yosemite). I'll send you a PR soon.

**Comment by ricpelo** [comment]
Mmm, I speak too early... My PR fixes window_management demo, but setting Scene -> Project Settings -> display -> fullscreen to "on" still does nothing: when I press F5 or F6, the project/scene still runs windowed.

**Comment by punto-** [comment]
Well, the point is that the code on "set_window_fullscreen" (whatever works
there) needs to also run form OS_OSX::initialize when fullscreen is
requested via the configuration or command line.. that's what the other OSs
do and probably osx is not doing..

**Comment by ricpelo** [comment]
Yes, I'm working on it now, and I think I get it, but I'd like to do some more testing.
