### ISSUE TITLE
All Uses-Permission (AndroidManifest) was written. Can't be changed via Editor

### ISSUE THREAD

**Issue by KelinciFX** [okamstudio/godot#1813]
So, I build an Apk (of course I'm in Android Platform), All uses-permission for AndroidManifest was written like crazy. I do any change by selecting what I need via check button (bool type) inside Editor. But, my change was always be ignored.

I don't know if this happen on Godot v1.0 Stable. I just test it inside Godot v1.1Beta1 and v1.1RC1 on Android Build. Let's have the image below :

![uses-permission_overloaded_androidmanifest_gdt-1 1beta1 1 1rc1_bug_01](https://cloud.githubusercontent.com/assets/12244526/7465978/8159b830-f30d-11e4-9fea-76d6ad1ce3a1.png)

![uses-permission_overloaded_androidmanifest_gdt-1 1beta1 1 1rc1_bug_02](https://cloud.githubusercontent.com/assets/12244526/7465982/8b586ebc-f30d-11e4-94fe-ac18f041f97e.JPG)

**Comment by okamstudio** [comment]
yeah, the ones used are actually placeholder properties, Android ignores
them

On Mon, May 4, 2015 at 11:06 PM, KelinciFX <notifications@github.com> wrote:

> So, I build an Apk (of course I'm in Android Platform), All
> uses-permission for AndroidManifest was written like crazy. I do any change
> by selecting what I need via check button (bool type) inside Editor. But,
> my change was always be ignored.
>
> I don't know if this happen on Godot v1.0 Stable. I just test it inside
> Godot v1.1Beta1 and v1.1RC1 on Android Build. Let's have the image below :
>
> [image: uses-permission_overloaded_androidmanifest_gdt-1 1beta1 1
> 1rc1_bug_01]
> <https://cloud.githubusercontent.com/assets/12244526/7465978/8159b830-f30d-11e4-9fea-76d6ad1ce3a1.png>
>
> [image: uses-permission_overloaded_androidmanifest_gdt-1 1beta1 1
> 1rc1_bug_02]
> <https://cloud.githubusercontent.com/assets/12244526/7465982/8b586ebc-f30d-11e4-94fe-ac18f041f97e.JPG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1813>.
>



-- 

*OkamStudio*

**Comment by KelinciFX** [comment]
Is this fixable or we just left it as is? (^_^)

**Comment by KelinciFX** [comment]
Nevermind... My mistake. Now, I do understand what that placeholder means... I think this issue could be marked as Solved. Yay..!! Thank you very much.
