### ISSUE TITLE
editor_settings.xml is mercilessly wiped out when opened in Godot < 1.1beta

### ISSUE THREAD

**Issue by adolson** [okamstudio/godot#1815]
If you launch an older Godot build, such as the 1.0 release, it will completely destroy the editor_settings.xml file, all the while printing out a warning that the file is too new, and to use a newer version of Godot in the terminal output.

Perhaps newer versions of Godot should have their own versioned config (editor_settings_1.1.xml, for example), which, if not already present, could be copied from the first existing previous version (just decrement the minor and major version numbers from current version down to 1.1, and finally, editor_settings.xml, until one is found, if any). Then this annoyance can be avoided going forward.

**Comment by SuperUserNameMan** [comment]
#1689
