### ISSUE TITLE
Sprite.set_flip_h() now requires bool?

### ISSUE THREAD

**Issue by adolson** [okamstudio/godot#1816]
I'm not sure when this changed, but 0 and 1 used to be automatically interpreted as boolean values by the set_flip_h function. For example, this line of code was working in older versions of Godot:

obj.set_flip_h( randi() % 2 )

But now, it must be cast to bool or the game dies when that line is hit, like so:

obj.set_flip_h( bool(randi() % 2) )

It's obviously an easy fix, but seems unnecessary since it was previously working and makes sense that it was working with 0/1 integers. I'm going to assume this applies to other functions with bool arguments, though I did not test more yet.

Was this change intentional? If it was, what was the reasoning behind it? And maybe - for cleaner code's sake - we could add a randb() which returns a random bool?

obj.set_flip_h( randb() )

**Comment by reduz** [comment]
Yeah, users were having bugs resulting from not as strict parameter checking, so for function arguments strictness was increased. 

That said, I think forcing the int -> bool conversion is probably too much, and should make an exception for this.
