### ISSUE TITLE
[Feature request] An option to clear the output console.

### ISSUE THREAD

**Issue by guilhermefelipecgs** [okamstudio/godot#1825]
I think an option to clear the output is useful.

**Comment by BBric** [comment]
And a toggle in the settings for doing it automatically when a scene is played.

**Comment by NateWardawg** [comment]
Both of these would be really nice to have. To have the options directly on the console and to not have to go into the editor settings would be nice too.

**Comment by ScyDev** [comment]
Yes please! Anooyed me many, many times.

Workaround: use the -d option when starting Godot from a terminal. You'll have all the output there and can reset the terminal to clear the old output (at least on Ubuntu I can).

**Comment by StraToN** [comment]
Here is my proposal for a button on top right of output console to clear it out. Clearing currently need a click on this button for now, but I'll work on a way to make this automatic on Running the scene. What do you prefer ?
- a checkbox "Clear console on Run" above the console (Unity3d-like)
- an option in the parameters

Tell me what you think.

**Comment by BBric** [comment]
The first is the more complete, but with the second checked  the first could also not be visible, thus both. :)

**Comment by StraToN** [comment]
Quoting reduz : 
"seems fine to me, you can add the clear option on start in the editor settings and use the EDITOR_DEF() macro to read it at the right place"

Thus, here is the planning : 
- [x] Get a "Clear" button working
- [ ] Put a CheckButton "Clear on Play" working, clearing the output at each run (Play/F5, Debug/F6)
- [ ] Create and show an option in Godot parameters ("Always clear output on Play ? Yes/No"
- [ ] Add a condition to display the CheckButton above the output only if the preceding parameter is set to "No"

**Comment by StraToN** [comment]
I suggest closing this Feature Request ;)

**Comment by ChipChance** [comment]
I'd like to request that this be re-opened. I'd like a command like console.clear() to clear the console (NOT just the OUTPUT window, but rather the CONSOLE window.)

Also, is there a project option to clear the console whenever a project is run? I'd like to see that too.

**Comment by StraToN** [comment]
I suggest a new feature request instead, on godotengine/godot or godotengine/godot-proposals (is that right yet @akien-mga ?). What you're asking is a different feature, even if related.

However I suspect a won't do in this case since I don't think Godot can control clearing on the standard output - only writing, like any other software. 

Concerning the option to clear the console whenever a project is run, a small search in Editor settings would have told you it is already there.
![image](https://user-images.githubusercontent.com/1289207/57122540-355b6600-6d7e-11e9-88ab-e27dc667ecbf.png)

**Comment by akien-mga** [comment]
A feature request was opened: #28632

@StraToN We don't advertise godot-proposals just yet, it's still in the design phase.
