### ISSUE TITLE
RigidBody 3d Edge Collisions

### ISSUE THREAD

**Issue by travisapple** [okamstudio/godot#1827]
I have a simple box collision shape and then I slide a capsule (or sphere) over the top of it. Everything works well until the capsule gets to the edge of the box and tries to slide off the side. The capsule gets stuck and slides along the edge and not off the side as expected. An example project that shows this behavior can be found here:

http://dreamsage.com/fps1.zip

Tested on Win7 64 on v1.1 RC2

**Comment by guilhermefelipecgs** [comment]
Your problem happens because you set the scale in the capsule shape, godot will not work correctly with this, instead, set the radius and height like this:
![captura de tela de 2015-05-06 09 31 43](https://cloud.githubusercontent.com/assets/1387165/7493022/bbab35b0-f3d3-11e4-8fa6-017e756b8657.png)

**Comment by guilhermefelipecgs** [comment]
Reference here:
https://github.com/okamstudio/godot/wiki/tutorial_physics_2d#transforming-shapes

This limitation apparently is valid for 3D too.

**Comment by bojidar-bg** [comment]
close?
