### ISSUE TITLE
Fail in Shader Graph in last build (bc3c14a76b988a50e65328a932316c2e630a7ae6)

### ISSUE THREAD

**Issue by marcosbitetti** [okamstudio/godot#1832]
In editor all works, but on F5 shader is miss
![captura de tela - 06052015 - 06 35 18](https://cloud.githubusercontent.com/assets/85936/7491002/6c77aae0-f3bb-11e4-9182-befba40268b8.png)

**Comment by marcosbitetti** [comment]
news, after I open project at this night I see the ALL nodes of vector operations is missing!
Before
![captura de tela - 06052015 - 22 52 34](https://cloud.githubusercontent.com/assets/85936/7507219/f8e9e2b8-f442-11e4-82a8-15c891757b99.png)

After
![captura de tela - 06052015 - 19 43 00](https://cloud.githubusercontent.com/assets/85936/7507220/ff7f1558-f442-11e4-98ed-00b556f4520d.png)

**Comment by reduz** [comment]
huh, wtf..  how do I reproduce this? could you make some simple steps for
this?

**Comment by marcosbitetti** [comment]
I import the textures
Start to configure normally a graph, connect, use vector operators and save it. (this video sequence, made in old version of Godot, show step by step of setup https://youtu.be/E7xLikNc7Ic?t=1m31s )
The result on IDE is Ok.
F5 fails!!!
When I save, and reopen it, the vector nodes don't appears.

I suppose that the problem is on read or write of scene file, I use .scn

**Comment by marcosbitetti** [comment]
for comparations, using code interface works fine
![captura de tela - 08052015 - 23 07 34](https://cloud.githubusercontent.com/assets/85936/7548223/66ff9956-f5d7-11e4-878e-ebba13aa608f.jpg)

**Comment by reduz** [comment]
ah I think I know what's going on
