### ISSUE TITLE
[1.1rc2.0995a230f6] Input.get_mouse_pos() is missing

### ISSUE THREAD

**Issue by mizahnyx** [okamstudio/godot#1838]
Hi all,

First, thanks all the contributors and coders of this project for such an amazing engine.
I downloaded 1.1rc2 precompiled binaries and tried to run a project I had that used Input.get_mouse_pos() to provide a trackball effect. The code didn't ran, and while perusing the Input class help on the Godot IDE I noticed that Input.get_mouse_pos() was missing from the class. Is that intended? How should I replace it then? It's a bug? Or an API upgrade?

Thanks in advance,
    Sam "Mizahnyx".

**Comment by reduz** [comment]
https://github.com/okamstudio/godot/wiki/tutorial_mouse_coords

**Comment by reduz** [comment]
it was deprecated due to users making 2D games misunderstanding how it works

**Comment by mizahnyx** [comment]
Thank you for the clarification! I will clean my code to not use them anymore! Sorry for the nuisance! Thanks for all the work involved!

**Comment by Kasara** [comment]
Also from me a thank you - had exact the same question

**Comment by reduz** [comment]
OK, just for future reference, use:

```python
get_viewport().get_mouse_pos()
```
as a direct replacement.
