### ISSUE TITLE
Godot1.1rc2 breaks layers settings from earlier versions of the engine.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [okamstudio/godot#1842]
Godot1.1.rc2 breaks earlier versions of the Engine of layer's settings for PhysicsBody2D in RigidBody2D properties.
Layers were set correctly to multiple layers and were working as expected in the previous version beta1 as well as 1.1rc1. After opening the project in 1.1.rc2 all rigidbodies2D layers settings had been reset to layer 1. 
How to replicate this bug:
* Create a project in pre 1.1rc2 version of the engine. Using UI create a RigidBody2D node and set it's PhysicsBody2D to layers 1,2,3 and 4 for example. Save the project.
The project may looks like mine:
https://github.com/freemanfromgodotengine/my_repository/blob/master/gfx/ProjectinGodot1.1rc1.png

* Open the project in Godot1.1.rc2. 
Look at The RigidBody2D node, that it has a new subproperty called Collision in PhysicsBody2D property and now Layers is set only to layer 1 and a Mask layer 1 (also new feature not present in previous version of Godot).
Something like this:
https://github.com/freemanfromgodotengine/my_repository/blob/master/gfx/ProjectinGodot1.1rc2.png

**Comment by reduz** [comment]
yes, you have to set them again using the new version, as it doesn't work
the same way. I kind of dislike breaking compatibility but the way layers
worked before was not as useful for most people

**Comment by freemanfromgodotengine** [comment]
I don't mind layers working differently in new version.
I just expect, that previously set layers setting will be recognized in new version.
If it was set to 1,2,3 and 4, let in new version the settings be left the same way.
Is it not possible?
