### ISSUE TITLE
1.1rc2 - fullscreen game doesn't seem to have focus

### ISSUE THREAD

**Issue by adolson** [okamstudio/godot#1847]
If I launch a game in fullscreen and then try to click something in the game with my mouse, the click actually goes "through" the game, to Godot in the background, bringing it into focus. This is the Linux version, not sure if it does the same on Windows or Mac.

**Comment by ricpelo** [comment]
Which Linux distro? Which desktop environment?

**Comment by adolson** [comment]
Debian 8, GNOME

**Comment by ricpelo** [comment]
Sorry, I'm unable to reproduce this issue in my Ubuntu 14.04 & GNOME :(. Fullscreen works as expected. Maybe a video driver problem?

**Comment by SuperUserNameMan** [comment]
I've tried to reproduce with Windows, and found no problem

**Comment by adolson** [comment]
Can you try this project in Godot 1.1rc2 and see if you replicate the issue or not? At the game's title screen, when I click on an option, it goes through to Godot.

https://gitlab.com/shine-upon-thee/santa-sniper

**Comment by SuperUserNameMan** [comment]
there is still no problem under Windows 8.1 with 1.1rc2.current_head

**Comment by adolson** [comment]
Here's a video of the behavior: https://youtu.be/QdTHBkFw5u0

**Comment by freemanfromgodotengine** [comment]
Game works without problems under Xubuntu 14.04 64-bit (XFCE window manager).

**Comment by VikTymZ** [comment]
it must be something to do with your WIndows Manager have you change the default setting??, 
doesn't have that issue on my Fedora 22 Beta (XFCE).

**Comment by adolson** [comment]
No, I haven't changed anything. All of my hundreds of Steam games work
fine. I am using GNOME, not XFce. This is a fresh Debian 8.0 install, with
the NVIDIA drivers installed from the repo and working fine, as I said, in
my hundreds of Steam games and all other fullscreen applications (VLC,
YouTube and Netflix in Chrome, etc).

**Comment by bojidar-bg** [comment]
@adolson I remember that in some versions of GNOME 3 (I'm on ubuntu-gnome) there was some bug with fullscreen youtube videos, and I think it can be related. I back then, fixed that issue by installing https://extensions.gnome.org/extension/851/flash-fullscreen-fix/ ...

**Comment by reduz** [comment]
I tried but can't reproduce either

**Comment by adolson** [comment]
OK, I'll just close it since I'm the only one seeing it. If it persists and I get sick of it, I'll just investigate myself and go from there.
