### ISSUE TITLE
oneway platforms propel character over them

### ISSUE THREAD

**Issue by SuperUserNameMan** [okamstudio/godot#1854]
Hi,

I'm testing all the demos of the current head, and I've just discovered the "one way paltforms" into the "platformer 2d" and into the "kinematic character 2d" demos.

I've found that when you jump too close to a "one way platform", the platform propels you over the top of it.

This behavior surprised me because I was expecting them to have a passive bahavior. Like for instance, if you jump near a table, the table should not propels you over the to of it. The table should become "solid" only once your feet jumped higher than it.
With current bahavior, the table will propels you over the top of it as soon as your head will cross it. 
I think it's a bug or a wrong feature.

Here is an animated GIF showing the beahvior into the 2d platformer demo :

![godot_demo_2d_platformer_20150507_1838](https://cloud.githubusercontent.com/assets/9801802/7521247/9b06803e-f4ec-11e4-81ce-66cffd8335c6.gif)

**Comment by okamstudio** [comment]
the platformer demo uses Dynamic character, not kinematic.. but yeah I see
the problem, will eventually improve it

On Thu, May 7, 2015 at 2:14 PM, SuperUserNameMan <notifications@github.com>
wrote:

> Hi,
>
> I'm testing all the demos of the current head, and I've just discovered
> the "one way paltforms" into the "platformer 2d" and into the "kinematic
> character 2d" demos.
>
> I've found that when you jump too close to a "one way platform", the
> platform propels you over the top of it.
>
> This behavior surprised me because I was expecting them to have a passive
> bahavior. Like for instance, if you jump near a table, the table should not
> propels you over the to of it. The table should become "solid" only once
> your feet jumped higher than it.
> With current bahavior, the table will propels you over the top of it as
> soon as your head will cross it.
> I think it's a bug or a wrong feature.
>
> Here is an animated GID showing the beahvior into the 2d platformer demo :
>
> [image: godot_demo_2d_platformer_20150507_1838]
> <https://cloud.githubusercontent.com/assets/9801802/7521247/9b06803e-f4ec-11e4-81ce-66cffd8335c6.gif>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1854>.
>



-- 

*OkamStudio*

**Comment by SuperUserNameMan** [comment]
yep, you're correct. 
I confused with the "kinematic character" demo in which you added one-way platforms too, and in which this bahavior is noticiable too :
![godot_demo_2d_kinematic_collision_20150507_1846](https://cloud.githubusercontent.com/assets/9801802/7522016/ab6e1b66-f4f2-11e4-819f-b48fc94ca929.gif)

**Comment by reduz** [comment]
yeah kinematic has this problem but for a different reason.. now that the
motion code is unified, it should be much simpler to fix this
