### ISSUE TITLE
3D particles alpha issue

### ISSUE THREAD

**Issue by ricpelo** [okamstudio/godot#1866]
Using latest git HEAD.

When I fix Navmesh Demo (setting diffuse texture in the "antigravity" Particles node), the particles shows inside a black box. It seems to be an alpha problem.

![captura de pantalla 2015-05-08 a las 10 07 02](https://cloud.githubusercontent.com/assets/616169/7532735/b96236da-f56a-11e4-9ec1-00079c804d26.png)

**Comment by Ace-Dragon** [comment]
The diffuse texture in question needs to have an alpha channel to work properly.

**Comment by SuperUserNameMan** [comment]
you can set the "Blend mode" to "add" instead of "'mixed", and you wont have to worry about alpha.

**Comment by SuperUserNameMan** [comment]
or else, you let to "mixed" and you enable the Fixed Flag "Use Alpha" at the top.

**Comment by reduz** [comment]
closed in head
