### ISSUE TITLE
Wrong mentioned date

### ISSUE THREAD

**Issue by theuserbl** [okamstudio/godot#1870]
At the end of the project manager stands:
(C) 2008-2014 Juan Linietsky, Ariel Manzur.
Ath the end of the editor stands the same.
And also in the About-box.

We have currently 2015!

Ok, that with 2008-2014 stands in Godot 1.1 RC2. But I hopw in the Godot 1.1 Final it will be corrected.

**Comment by VikTymZ** [comment]
juan have edited the date on headers files only for now. sure it will be updated on next version. so, it's not really a bug.
