### ISSUE TITLE
1.1rc2 crashes on Windows with -h option

### ISSUE THREAD

**Issue by ratsdiov** [okamstudio/godot#1873]
Running godot_win64-1.1rc2.exe -h  crashes after displaying the help text.

**Comment by SuperUserNameMan** [comment]
Oh yeah, I remember noticing a crash with win32 1.1beta1 too.

I tried again today, and instead of crashing, 1.1beta1 and 1.1rc2.head display these errors at the end of the help :
````
WARNING: ObjectDB::cleanup:  ObjectDB Instances still exist!
At:  core\object.cpp:1733
ERROR: Main::start:  Condition ' !_start_success ' is true. returned: false
At:  main\main.cpp:882
ERROR: Main::cleanup:  Condition ' !_start_success ' is true.
At:  main\main.cpp:1462
````
