### ISSUE TITLE
Engine crashes when trying to make a node2D unique

### ISSUE THREAD

**Issue by caleb272** [okamstudio/godot#1874]
Im working away on this awesome engine and i wanted to see what the make resource unique does and it crashed the engine.
FACTS
1: im running elementary os freye linux
2: my engine version is godot_x11-1.1rc2.64
3: i made some unique script resources earlier

**Comment by reduz** [comment]
I'm sorry, you will have to add more detail to this issue, as making resources unique works perfectly as far as I can test. 
Node2D is not a resource, so I guess it must have been something else.  Could you add more detail to your problem?

**Comment by bojidar-bg** [comment]
It is very simple to reproduce this issue... Just select a node, click the gear icon in the Inspector, and press "Make Resource Unique"... :smile:

**Comment by reduz** [comment]
i totally forgot about that option, will fix it
