### ISSUE TITLE
1.1 rc2 Sprite animation broken: Anim Track Change Value Mode won't go to continuous

### ISSUE THREAD

**Issue by captainwasabi** [okamstudio/godot#1891]
IMPORTANT NEW INFORMATION: IF I BUILD THE EXE MYSELF (Windows) THIS PROBLEM DOES NOT EXIST!! (Maybe you already fixed it in the repo?)

Follow the instructions here: https://www.youtube.com/watch?v=X3flgK75Oz0

When I go to set the Anim Track Change Value Mode (for either the Sprite example or the AnimatedSprite example) the icon stays on discrete, but when I open the pulldown it is set on continuous, but the anim won't play.

Help! ;)

**Comment by reduz** [comment]
i don't remember changing any of this, but this issue seems to be reported
a lot, will check it

**Comment by ThomasMorley-T3D** [comment]
I can confirm that the same issue exists on the Linux 64 bit version of RC2 as well.

**Comment by captainwasabi** [comment]
Is there a way to set this via script?

**Comment by ThomasMorley-T3D** [comment]
![animationplayer](https://cloud.githubusercontent.com/assets/11800663/7645288/6d977b94-fa78-11e4-8a09-ffea32c863ba.jpg)

**Comment by ThomasMorley-T3D** [comment]
You can see the naming of the animation tracks looks off too. The top track is for AnimatedSprite rotation and the bottom track is for the CollisionPolygong2D rotation. The naming convention for the two tracks are different, and debugger throws a "On Animation: 'Rotate', couldn't resolve track: '../CollisionPolygon2d:transform/rot'

**Comment by captainwasabi** [comment]
Interesting.  If I keyframe the frame number it's stuck on discrete, if I keframe rotation (like the screenshot above) it's stuck on continuous.

**Comment by ThomasMorley-T3D** [comment]
Yeah me too.

**Comment by ThomasMorley-T3D** [comment]
Looks like I'll have to abandon the AnimationPlayer altogether until this gets fixed. I need RC2 for the new Layer/Mask functionality so I'll just rotate them in code.

**Comment by ThomasMorley-T3D** [comment]
![error](https://cloud.githubusercontent.com/assets/11800663/7645386/0f001472-fa7a-11e4-8b6b-8dd994a0680f.jpg)

**Comment by SuperUserNameMan** [comment]
@ThomasMorley-T3D :
If I remember correctly, collision shapes nodes exists only into the editor. 
At runtime, they are converted and stored into the Body node.
So, it is normal that they can't be animated.

**Comment by captainwasabi** [comment]
If I build the exe (Windows) myself this problem goes away.  maybe you already fixed it, maybe the rc is using different compile settings (Release vs Debug?)

**Comment by reduz** [comment]
I think I know the problem, somehow float and integer values are getting mixed in the animation so they don't become interpolated even if you set to continuous, i'll add both of those as exception for interpolation

**Comment by reduz** [comment]
please test

**Comment by captainwasabi** [comment]
If that would also keep the GUI widget from changing (but not the dropdown) that could be it.

**Comment by captainwasabi** [comment]
Sorry, how do I test this since it was already working when I built the exe myself?  I just pulled the repo about 40 mins ago.

**Comment by captainwasabi** [comment]
Fixed in 1.1rc3
