### ISSUE TITLE
(export) vars is corrupt!

### ISSUE THREAD

**Issue by OlexiyKravchuk** [okamstudio/godot#1896]
export (TYPE) var NAME_VAR does not work correctly. At the time of construction of the object, all fields that were installed with the help of the inspector, in the editor window during the boot sequence of the scene (at a time when executed, the function _ ready ()), are absolutely empty, even if the original scene takes the field set in the inspector, in advance, before the creation of any instance of such a scene.
And if, in the script, previously obvious way to set default values, they will be in place initially, but when the editor creates a new instance of the scene and in the Inspector, change the field (export), for some other value, and save the scene, then when run scene, the new value will never appear, instead will always be something that was previously specified in the script in obvious way ...

**Comment by Zamaroht** [comment]
Let me add to this that exported arrays are not correctly shown in the inspector.

**Comment by reduz** [comment]
that is intended, try assigning a default value for it to infer type and it will work better, try:

```
export var myvar = 2
```

and it automatically exports an integer

**Comment by OlexiyKravchuk** [comment]
that is intended, try assigning a default value for it to infer type and it will work better, try:

export var myvar = 2
and it automatically exports an integer

@ reduz
as I said higher ...
And if, in the script, previously obvious way to set default values, they will be in place initially, but when the editor creates a new instance of the scene and in the Inspector, change the field (export), for some other value, and save the scene, then when run scene, the new value will never appear, instead will always be something that was previously specified in the script in obvious way ...

**Comment by reduz** [comment]
I am really not seeing that behaviour, can you make a scene where editor
overriden values are not kept so i can test?

**Comment by OlexiyKravchuk** [comment]
https://www.dropbox.com/s/4ry7fytwe3awda0/ZERO_Temperatures_TEST.7z?dl=0
while I was doing this example, I seem to have understood what the problem was, it is because, constructor is late in _init (), you have already is mentioned about it in a different issue.

**Comment by reduz** [comment]
when you edit a node, you might have realized that the script property is
at the bottom. When nodes or resources are loaded, properties are set from
the bottom to the top. This means that the script is set first (thus
_init() is run) and, after all the node has been configured, the property
with the exported variable is set. As you aquire the value in the
constructor, this value has not been set yet.

**Comment by OlexiyKravchuk** [comment]
Thank you for the details, so I close this issue.
