### ISSUE TITLE
[Feature Request] - Node to new scene

### ISSUE THREAD

**Issue by alketii** [okamstudio/godot#1910]
It would be useful to right-click a node, an transform it to a new scene.

**Comment by reduz** [comment]
Scene -> Save to SubScene

This might eventually be made more userfriendly

**Comment by alketii** [comment]
Oh great, thanks. Didn't knew what subscene was :smile:

**Comment by bojidar-bg** [comment]
I've tried "Save to SubScene" a couple of times, and every time it worked like save as...

**Comment by vichug** [comment]
bojuda-bg : did you select the node from which you wanted to make a subscene ?

**Comment by bojidar-bg** [comment]
@vichug strange... now it worked :smile:.
