### ISSUE TITLE
1.1: critical: Materials are not saved with scene

### ISSUE THREAD

**Issue by slapin** [okamstudio/godot#1924]
When using imported .obj, sometimes some elements can't have material set.
In editor everything looks good, but both running scene and reopenning of scene
shows materials missing. In case of FixedMaterial, it is not saved at all,
in case of ShaderMaterial Uniform parameter values are not saved with scene.
Saving Fixedmaterial works, but not with scene.

**Comment by slapin** [comment]
I don't see any attempt to save .msh data when I cahnge tree_top material:

settings changed
SAVING: res://plane.scn
UPDATING: res://plane.scn
SAVING: res://plane.scn
UPDATING: res://plane.scn
SAVING: res://plane.scn
UPDATING: res://plane.scn
SAVING: res://plane.scn
UPDATING: res://plane.scn
SAVING: res://plane.scn
UPDATING: res://plane.scn

As I see, materials in case of imported objects are saved in .msh files.
So if I see
SAVING: res://plane.scn
UPDATING: res://plane.scn
Also saving modified external resource: res://tree_top.msh
SAVING: res://tree_top.msh
SAVE PATH: ../tree_top.obj
SAVE MD5: 0b6caa8af5c4f8fda422e596d9cc8ce9
UPDATING: res://tree_top.msh

Then everything in FixedMaterial works as intended.
So it seems that some really serious critical bug lurking somewhere.

The way for me to trigger saving was to delete entire material and create a new one,
this works just once, then updating doesn't work.

However I was not able to have Uniform parameters saved yet. I wonder how these were tested
or these are officially broken?

**Comment by slapin** [comment]
Sample scene: http://ossfans.org/mat-bug.zip

**Comment by reduz** [comment]
this was quite a serious bug, and I guess many others were probably caused by it.. thanks for reporting :D
