### ISSUE TITLE
Godot crashed on launching

### ISSUE THREAD

**Issue by SouSuke-Ss** [okamstudio/godot#1933]
I am using windows 7 32 bit on netbook with screen resolution 1024x600.
I was launching (starting)  godot_win32-1.1rc2.exe and godot has been crashed after printing "DETECTED MONITORS: 1" in command window and GUI window was freezing .
Here are some screen shoot of the problem.
![godot cmd](https://cloud.githubusercontent.com/assets/12489459/7673764/35a996aa-fd4c-11e4-93ad-28b8ff1f5879.png)
![godot crash](https://cloud.githubusercontent.com/assets/12489459/7673768/671481fa-fd4c-11e4-806f-259bf075bfb7.png)

Thank you :D

**Comment by okamstudio** [comment]
may be possible that your device does not support opengl 2.1? what kind of
chipset does it have?

On Sun, May 17, 2015 at 11:46 PM, SouSuke-Ss <notifications@github.com>
wrote:

> I am using windows 7 32 bit on netbook with screen resolution 1024x600.
> I was launching (starting) godot and godot has been crashed after printing
> "DETECTED MONITORS: 1" in command window.Here are some screen shoot of the
> problem.
> [Uploading godot cmd.png…]()
> [Uploading godot crash.png…]()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1933>.
>



-- 

*OkamStudio*

**Comment by SouSuke-Ss** [comment]
the graphic  is intel graphics media accelerator 3150

**Comment by deliciousfudge** [comment]
By the sounds of it, that particular model only supports up to OpenGL 1.4: http://forums.ppsspp.org/showthread.php?tid=5838

Someone has suggested a workaround for Windows 7, but I'm not sure how reliable it is: http://superuser.com/a/554625

**Comment by reduz** [comment]
nope, godot does not work in this GPU due to lack of shaders, sorry about it, consider upgading your hardware

**Comment by akien-mga** [comment]
Duplicate of #156, related to #1162.
