### ISSUE TITLE
RichTextLabel height zeroed, and Anchor settings reset, when inside a scroll container

### ISSUE THREAD

**Issue by GameCy** [okamstudio/godot#1934]
I am trying to display some formated text, shich should be scrolable. So there is a RichTextLabel (RTL) inside a ScrollContainer.
When the ScrollContainer is moved in the editor, the RTL height is reset to zero, and the anchor to (Begin,Begin,Begin,Begin)
When the RTL is sized (by dragging it's corner in the editor), If it becomes bigger than the text height, it resets to zero.

P.S. is it possible to fix this using a script? e.g.
richTextControl.parse_bbcode(textBB)
richTextControl. . . SetSize() or CalculateHeight   or similar?

**Comment by reduz** [comment]
yes, containers override your height and anchor settings, this is by design.
Use a minimum size instead

**Comment by reduz** [comment]
there is currently no function to calculate the height of the text, may be added at some point
