### ISSUE TITLE
Lost Godot settings when upgrading from 1.0 stable to 1.1 beta

### ISSUE THREAD

**Issue by ScyDev** [okamstudio/godot#1944]
Quite inconvenient, having to set up adb, jarsigner, keystore again.

**Comment by reduz** [comment]
ah the problem is when going back to previous version of godot, I wonder how this can be improved..

**Comment by ScyDev** [comment]
It's possible that I started 1.0 stable once again, after having started 1.1 beta, to test some behaviour.
