### ISSUE TITLE
Dreaming of 1.2 user interface features

### ISSUE THREAD

**Issue by honix** [okamstudio/godot#1948]
Just put here some my ideas of how can 1.2 be (the ideas can be stupid in some way)

- add icon to .exe (i think time is come)
- open godot in fullscreen automaticly (or read last session position)
- tabs to fast scene to scene jumping (i know its in todo-list already)
- working in code and scene editor (or code and code) in one time (good for wide screens)
- when typing a path to a node it can be userfull to choose from a visual tree in popup window(for animation callFunc lines at first)
- reorder nodes just by mouse
- when creating new node itis toggle (do parent/do child(default)) of selected node
- hided and scripted icons of nodes will be in static vertical lines to better read
- in 3d fly mode with mouse look and wasd move
- preview game in scene editor not in new window, or save window pos

I hope it helps

**Comment by reduz** [comment]
please add them to the document in the developers mailing list:

https://groups.google.com/forum/#!topic/godot-engine/f4x7hJGUD7M

**Comment by Calinou** [comment]
As for WASD move, make sure the keys are changeable, so that AZERTY users can use ZQSD, and so that arrow keys users can use arrow keys.

**Comment by honix** [comment]
Moved to google group
