### ISSUE TITLE
"Select all" is non-functional

### ISSUE THREAD

**Issue by Krzycho666** [okamstudio/godot#1950]
After selecting all in text editor ( both script and shader ) there is only a visual selection made. But copying, cuting or deleteding the selected text has no effect. It is for both - using "Edit->Select All" or Ctrl+A shortcut.
( Windows 7)

**Comment by okamstudio** [comment]
this is fixed on github head, please close

On Wed, May 20, 2015 at 9:54 AM, Siewio <notifications@github.com> wrote:

> After selecting all in text editor ( both script and shader ) there is
> only a visual selection made. But copying, cuting or deleteding the
> selected text has no effect. It is for both - using "Edit->Select All" or
> Ctrl+A shortcut.
> ( Windows 7)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1950>.
>



-- 

*OkamStudio*
