### ISSUE TITLE
Add option for ColorPicker to show values in 0-1 range

### ISSUE THREAD

**Issue by Hinsbart** [okamstudio/godot#1952]
If I want to hardcode colors and just use a colorpicker for reference, I need to divide the displayed values by 255. This is not a major issue but it would be nice if you could display color values in the 0-1 range directly ;)

**Comment by romulox-x** [comment]
You can select RAW in the lower left dropdown of the color picker.  This lets you set values much higher than 1, so sliding won't be great in this mode.  But you could find your color in RGB and then switch to RAW to see the 0-1 versions.

**Comment by Hinsbart** [comment]
Ah interesting. I tried RAW mode before but it still gave me 0-255 values when sliding, didn't know you have to set the color in RGB mode first, thanks for that information ;)
