### ISSUE TITLE
Missing function in Color (1.1)

### ISSUE THREAD

**Issue by puppetmaster-** [okamstudio/godot#1971]
**Color**
void Color ( int from )
Construct the color from an RGBA profile.

**Color**
void Color ( String from )
Construct the color from an RGBA profile.

**Comment by choikwa** [comment]
Do you have link to API? I don't see it in https://github.com/okamstudio/godot/wiki/class_color

**Comment by puppetmaster-** [comment]
https://github.com/okamstudio/godot/wiki/class_color/167d23f5cba49e71a63c00895d1c56db80682203 link is hiden in clas revision

**Comment by puppetmaster-** [comment]
Is there a problem with this **Autogen Class List**? When I compare the two revisions it has something to do with returning void.

**Comment by OlexiyKravchuk** [comment]
I confirm this feature is really missing and I do not understand why this is, as well as taking the color from the string function removed?
Juan, what is wrong with these, why ???

**Comment by puppetmaster-** [comment]
Any news about the missing functions?

**Comment by puppetmaster-** [comment]
Any news about the missing functions?

**Comment by puppetmaster-** [comment]
thx reduz
