### ISSUE TITLE
[Change Request] Scene should be text file instead of binary

### ISSUE THREAD

**Issue by hozmaster** [okamstudio/godot#1994]
Git is most popular version control system now days. Git most least weakness is that its not support binary file quite well. Therefore, files which are update often should not be binary files even that there are not big. So .scn files should be text files

**Comment by Calinou** [comment]
Are you aware we support .xml scenes, which are text files and thus fairly VCS-friendly?

Godot seems to prefer binary files over text files, because I guess that's the usual use case (used in private, or not over a VCS).

**Comment by madjestic** [comment]
also you can save the scene file as *.xscn (it's also mentioned in the file dialogue)

**Comment by hozmaster** [comment]
Thanks, I didn't aware of xscn option. So why it's not default option instead of scn format ? Btw, I have use this engine only two days so I'm just learning this engine.

**Comment by kubecz3k** [comment]
hozmaster: generally in production scn will be faster to load, what might be noticeable especially on mobile.

**Comment by SuperUserNameMan** [comment]
if it is solved, please close this issue.

**Comment by okamstudio** [comment]
It amounts to:

1) scn is much faster to load than xml, this is mostly noticeable on 3D
scenes, complex animations, etc.
2) scn stores floating point values with full precision
3) scn is more compact

There is work in progress for a new, text based, scene file format that is
more human readable and easier to parse than xml,, but not for anytime soon.


On Thu, May 28, 2015 at 8:54 AM, SuperUserNameMan <notifications@github.com>
wrote:

> if it is solved, please close this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1994#issuecomment-106288921>.
>



-- 

*OkamStudio*

**Comment by hozmaster** [comment]
Ok, I will accept that xml is not ideal format format for saving scene data. Glad to hear that there is new format coming in some release in some day. 

I'm closing this. Thanks with your support.
