### ISSUE TITLE
The first scritpting tuto dont work

### ISSUE THREAD

**Issue by Jerome67000** [okamstudio/godot#1999]
Hello,

Im a mobile developper and i have followed the steps on this [link](https://github.com/okamstudio/godot/wiki/tutorial_scripting) but its dont work, the debbuger show :

````
Attempt to call function 'connect' in base 'null instance' on a null instance.
````
Is the tuto outdated ? I use Godot 1.1 and i have tried in Linux and Windows, same issue.

**Comment by TheoXD** [comment]
I don't think so. Please ask on forum/irc/fb before creating an issue with questions.

**Comment by Jerome67000** [comment]
What is that mentality ? -_-

Im not a beginner in programmation and making games, i want to try Godot with a tuto and he dont work, i have followed step by step and copy/past the script, so i guess that this problem its not my fault. 

Is it a problem no ? Because many people will want to follow this tutorial and they will encounter the same problem with Godot 1.1. Try the tuto with the last version of Godot...

**Comment by TheoXD** [comment]
Steps are all fine, and if you have troubles - do not create issues until you're absolutely sure that it's a bug or a typo somewhere in the docs. If something would have changed in the API - every game that ever existed would break, and that wiki page hasn't changed since 2014, so, yeah... keep trying :)

**Comment by SuperUserNameMan** [comment]
@Jerome67000 :
I've just tested it too. It works perfectly.
Even I you consider yourself as an experienced game-developer, you're nonetheless a n00b with Godot.
Maybe you should consider adopting the appropriate 'mentality' and reconsider the hypothesis that the problem _could_ be on your side ?

**Comment by reduz** [comment]
Jerome, I can't say the tutorials are 100% bulletproof and it is very
likely they assume that some things are obvious for readers when they may
not be. The fact you are not understanding what is going on means something
can be improved on them.

However, it is impossible to tell what's going on from what you have
described. Do you think you could attach the project you were working on
following the tutorial that didn't work? This way we can better understand
which step was not clear to you, help you understand it and improve the
tutorial based on that.

**Comment by puppetmaster-** [comment]
The only problem you can have with this tutorial is ***case sensitive*** and **parent off [Button] is not [Panel]***

get_node("Button") != get_node("button")

**Comment by Jerome67000** [comment]
OMG i have finaly find the problem ! My Button node was in parent of Label and not Panel !

What I do :
* Panel
  * Label
    * Button

What the tuto say :
* Panel
  * Label
  * Button


Thanks for your answers and sorry for my insistance. I guess the tuto can be improved with a warning at this step because when you add the Label, the label take the focus and you must re click on Panel before you add the Button node. For a experimented developer on Godot i guess this is obvious, but not for a n00b. ;)

For my information, if i want hold my first configuration with Button parent of Label, how i can do the trick ? Juste navigate to the nodes like that ? Im not at home and im curious :p.
```
get_node("Label").get_node("Button").connect("pressed",self,"_on_button_pressed")
```

**Comment by TheoXD** [comment]
You just solved your own issue and answered your own question, keep it that way xD
Don't forget to close the issue after you.

**Comment by okamstudio** [comment]
Jerome, you were not the first with this issue, so will add clarification
in the tutorial

On Thu, May 28, 2015 at 12:13 PM, TheoXD <notifications@github.com> wrote:

> You just solved your own issue and answered your own question, keep it
> that way xD
> Don't forget to close the issue after you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1999#issuecomment-106393717>.
>



-- 

*OkamStudio*

**Comment by okamstudio** [comment]
Added a clarification note at the end of the tutorial

On Thu, May 28, 2015 at 12:14 PM, Juan Linietsky <juan@okamstudio.com>
wrote:

> Jerome, you were not the first with this issue, so will add clarification
> in the tutorial
>
> On Thu, May 28, 2015 at 12:13 PM, TheoXD <notifications@github.com> wrote:
>
>> You just solved your own issue and answered your own question, keep it
>> that way xD
>> Don't forget to close the issue after you.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/okamstudio/godot/issues/1999#issuecomment-106393717>.
>>
>
>
>
> --
>
> *OkamStudio*
>



-- 

*OkamStudio*

**Comment by puppetmaster-** [comment]
I have made the same mistake!! :-)

**Comment by Jerome67000** [comment]
The clarificaiton is perfect ;)
