### ISSUE TITLE
[PATCH] Blender collada exporter produces files unreadable by Assimp

### ISSUE THREAD

**Issue by TheJosh** [okamstudio/godot#2001]
Hi,

I'm using your collada exporter, but the files weren't readable by the popular library Assimp. I've made some changes, and thought I should send them upstream.

https://github.com/TheJosh/chaotic-rage/commit/fdc9962daee33b98f7847041f00f0c497795db15

Cheers,
Josh

**Comment by reduz** [comment]
cool, feel free to make a pull request

**Comment by TheJosh** [comment]
Pull request --  #2023
