### ISSUE TITLE
Stereoscopic rendering

### ISSUE THREAD

**Issue by unfa** [okamstudio/godot#2031]
Since Google Cardbord has appeared, more and more companies produce alike devices to make cheap VR-like experience availabile.

I wonder if it'd be possible for Godot to render stereoscopic images?

Several technologies are availabile:

Side-by-side straigth (for Google Cartboard like mounts) - left eye is left part of the screen, and vice versa.

Side-by-side inverted (for crossed-eye watching) - left eye is right part of the screen and vice versa.

Anaglyph (for oldschool 3D-glasses) - two images with altered colours are blended and displayed on top of each other, tinted glasses filter inmages for left and right eye.

Frame-interlace (for IMAX-like 3D glasses) - the images fro left and right eyes are interleaved in time, and the glasses on user's head dim the eyes to make the images go for left and right eye one at a time.

I can imagine this work for 3D games... and 2D games as well with parrarel backgrounds and overlay layers "popping out".

---

I see playing a game without having a touch interface availabile might be hard, but I've got one idea:

Using the phone with Google Cartboard for VR-like 3D display.
Using laptop/desktop PC as an input device (keyboard/mouse) transmitted via WiFi or Bluetooth to the smartphone.

**Comment by Krzycho666** [comment]
I thing that you could easily do it on your own, using two viewports connected to two different cameras fixed to each other with some horizontal translation.
After havingtwo different viewports  rendered to two different FBOs you can do whatever you want to do with them. Those effects are really easy achievable.

Here are some shader example for anaglyphic:
http://r3dux.org/2011/05/anaglyphic-3d-in-glsl/

The rest of the effects are straightforward to achive too.

**Comment by unfa** [comment]
Thanks a lot! I see now that it's all possible. Closing the issue.
