### ISSUE TITLE
Scale go back to original size if node is Rigidbody (1.1)

### ISSUE THREAD

**Issue by puppetmaster-** [okamstudio/godot#2052]
I can't change the scale of the snowball if it has or is a Rigidbody. It scales always to the original size. 
But when I change the RigidBody to a StaticBody or KinematicBody scaling works.
![image](https://cloud.githubusercontent.com/assets/10463138/8041234/030cb3ea-0e17-11e5-8891-ad8029396be9.png)

**Comment by reduz** [comment]
yes this is by design, the physics engine manages the transforms of the
bodies, and physics does not use scale.
You can try scaling the shapes and meshes manually though (check the
CollisionObject API to scale the shapes).
Eventually some helpers will be added to make this more transparent.

**Comment by puppetmaster-** [comment]
I will look if I can go with a KinematicBody, if not I try scaling throw API.
thx reduz

**Comment by bluenote10** [comment]
> Eventually some helpers will be added to make this more transparent.

Is there any update / documentation on this?
