### ISSUE TITLE
duplicate animationPlayer

### ISSUE THREAD

**Issue by ilearain** [okamstudio/godot#2054]
I have new scene look like : 

-Node2D
--Sprite
--AnimationPlayer -> with 1 track to animate the sprite

Then duplicating : 

-Node2D
--Sprite
--Sprite1
--AnimationPlayer
--AnimationPlayer1

When i change the AnimationPayer1 track source (Sprite/pos -> Sprite1/pos)
1st animationPlayer track source is also changed.

I need more thn one animationPlayer to run autoplay together (one autoplay at given time).

**Comment by captainwasabi** [comment]
Go to the second one, click on the settings icon in teh inspector Iit looks like a gear).  Select "Make Resources Unique"

**Comment by ilearain** [comment]
I want to make other animation with same movement, if i put new track in same animation i must create new keys (its many keys). So i need to duplicating the track, but i dont know how to duplicate track. So i duplicate the animationPlayer with track included. I try to change track resouce in 2nd animationplayer but 1st animationplayer track resource is also changed.
But try to make resource unique may be will fix my problem, ill try this tonight. Thanks

**Comment by ilearain** [comment]
captainwasabi, you right its work by make resource unique. Thanks

**Comment by reduz** [comment]
Artists at okam almost murdered me because of this when they modified and
erased an existing animation, so will add a dialog that says "Also
duplicate animations?"
