### ISSUE TITLE
Z sorting of Sprite3D misbehaving for orthogonal camera

### ISSUE THREAD

**Issue by ScyDev** [okamstudio/godot#2063]
I have a problem with Sprite3D in relation to camera position.
All the objects in my levels are Sprite3D and the camera is in orthogonal mode and can not rotate. In most cases this looks good. 
But with the walls and hedges, where some Sprite3D are overlapping there is a problem (Z ordering?), when said sprites are in the corners of the camera. Suddenly they misbehave and are displayed in the wrong order.
This problem can be seen in the video at 1:33 in the bottom right corner.
Is there anything I can do about that?

https://youtu.be/K70x3WegT8Y?t=90

**Comment by ScyDev** [comment]
![screenshot from 2015-06-12 10 07 51](https://cloud.githubusercontent.com/assets/1307146/8126008/1da2c678-10eb-11e5-827b-a7fb812293b2.png)

Please reopen the ticket (I can't).

Something has changed, but Z sorting is exactly the wrong way around now.
But it's no longer changing, relative to the cameras position. I'ts reliabliy wrong always :D

**Comment by reduz** [comment]
i think it should be fixed now, please try again

**Comment by ScyDev** [comment]
Yes, it's fixed now. Thanks! But now I once again have a big problem with the performance of the custom build: http://www.godotengine.org/forum/viewtopic.php?f=12&t=1482&p=10020#p10020

**Comment by okamstudio** [comment]
do you think you can put together a small test with only the required
assets that shows the performance bottleneck? this way I can profile it,
 see if it's anything engine related and fix it

On Mon, Jun 15, 2015 at 11:18 AM, ScyDev <notifications@github.com> wrote:

> Yes, it's fixed now. Thanks! But now I once again have a big problem with
> the performance of the custom build:
> http://www.godotengine.org/forum/viewtopic.php?f=12&t=1482&p=10020#p10020
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2063#issuecomment-112085391>.
>



-- 

*OkamStudio*

**Comment by ScyDev** [comment]
We are currently talking about two different performance issues.

I created a new ticket for the custom Godot build problem: https://github.com/okamstudio/godot/issues/2095
