### ISSUE TITLE
RigidBody sleeping after collision

### ISSUE THREAD

**Issue by Zorgan25** [okamstudio/godot#2064]
Hi, I'm having a weird result with a very basic scene. I'm making a roll-a-ball game with Godot. Basically, i have a floor (StaticBody) and a sphere (RigidBody). When the scene start my sphere fall on the floor but when i try to apply velocity nothing happen. Actually, if i apply velocity BEFORE the sphere hit the floor, it's working. It is not because of friction (i tried with extremly high number and +Y velocity still nothing).

Weirdly, if I turn off "can sleep" on my sphere everything works.

If I understand correctly, for some reason when my sphere hit the floor the RigidBody start sleeping. Ok, fine i can live with that. 

But, when i explicitly apply force to that object the RigidBody I expect the RigidBody to wake up.

**Comment by reduz** [comment]
I think this was fixed recently and bodies woke up when you applied some
force or changed state. Are you using GitHub version?

**Comment by Zorgan25** [comment]
I'm not, I'm using my own custom version of Godot. 

I will try and find the fix and apply it to my version. Ty for the reply!

**Comment by Zorgan25** [comment]
Ok i found the fix. 
I added the FORCE_INLINE wakeup() in body_sw.h and added 3 calls to wakeup() in body.cpp.

It works when i use set_linear_velocity but doesn't when i use set_axis_velocity.
