### ISSUE TITLE
[1.1][bug] User signals don't work if defined in ready()

### ISSUE THREAD

**Issue by kubecz3k** [okamstudio/godot#2069]
Defining signal in ready() with ``add_user_signal()`` don't work. They need to be added in ``_init()``.
Minimal working example:https://dl.dropboxusercontent.com/u/168251/godot/some/issues/UserSignals.7z

**Comment by volzhs** [comment]
_ready() is called when instance is added to display list(stage).
so, it will work if you add instance first and connect signal.
I think it's not a bug.

**Comment by kubecz3k** [comment]
@volzhs You are right it's not a bug. ``connect`` don't work because ready function in which signal is defined was not called yet at this point. Closing
