### ISSUE TITLE
.fscache and motion demo engine.cfg

### ISSUE THREAD

**Issue by ni-code** [okamstudio/godot#2079]
I think this file needs to be removed from git:
demos/2d/fog_of_war.fscache

and console shows errors in engine.cfg when loading the 2d motion demo
I'm not sure, but it looks like the file got corrupted somehow and lines 6 and 14 needs to be deleted. 

ERROR: load: Syntax error on line 6 of file /demos/2d/motion/engine.cfg
   At: core/io/config_file.cpp:718.
ERROR: load: Syntax error on line 14 of file /demos/2d/motion/engine.cfg
   At: core/io/config_file.cpp:718.

**Comment by bojidar-bg** [comment]
The motion demo thing seems to be a leftover of some bad merge:
 https://github.com/okamstudio/godot/blob/master/demos/2d/motion/engine.cfg

**Comment by reduz** [comment]
will check!
also, .fscache is no longer used by newer versions of godot
