### ISSUE TITLE
[Feature request] Exposing script variables in the GUI

### ISSUE THREAD

**Issue by kernelcrasher** [okamstudio/godot#2124]
In one of the games I'm working on, I've decided to make the enemies configurable. This is easily done via GDScript, but it's very cumbersome when there are dozens or hundreds of them in the scene and each one of them has to be initialized by adding a line to the scene script. It also makes keeping track of the changes borderline impossible. 
What would be best is if there was an ability to expose the configuration variables in the GUI, so that one could see the effects while designing the level.

**Comment by mohaalak** [comment]
you can export variable and it will appear in property menu of object yiu
can change. see the tutorial for gdscript.
for example

export var speed=30;

you can change this configuration in editor when you design.

you can even have config for textures files
