### ISSUE TITLE
Crash when queue_free called on windows.

### ISSUE THREAD

**Issue by dbsGen** [okamstudio/godot#2130]
func _on_start_pressed():
	  Globals.main.loading_scene.start()
	  yield(NewTimer.wait(0.8), "timeout")
	  var loader = Globals.main.load_level("level_test.scn")
	  yield(loader, "complete")
	  Globals.main.loading_scene.over()
	  queue_free()  #work fine when  delete this line.

This script works fine on linux or OSX, crash on windows.

**Comment by choikwa** [comment]
Saw similar issue when queue_free() was called without node having a parent. Does this node have a parent?

**Comment by dbsGen** [comment]
Yes this node have a parent. I will test it more later.

**Comment by choikwa** [comment]
How about just free or delete?

**Comment by dbsGen** [comment]
Oh! I download the last code on github. This issue no longer happen.
