### ISSUE TITLE
Encrypting scripts leads to Godot not being able to load game assets

### ISSUE THREAD

**Issue by ScyDev** [okamstudio/godot#2131]
I'm in the process of releasing my game. When I supply 256bit hex key for encrypting the scripts, the game won't get past the splash screen.

In the debug console it is apparent that the *.gd assets can not be loaded.

Should this be working?

**Comment by ScyDev** [comment]
It seems I'm not the only one having this problem: http://www.godotengine.org/forum/viewtopic.php?f=11&t=1883

**Comment by okamstudio** [comment]
you have to compile godot and the export templates with this same key, or
else it won't work

On Sat, Jun 20, 2015 at 5:55 AM, ScyDev <notifications@github.com> wrote:

> It seems I'm not the only one having this problem:
> http://www.godotengine.org/forum/viewtopic.php?f=11&t=1883
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2131#issuecomment-113733750>.
>



-- 

*OkamStudio*

**Comment by ScyDev** [comment]
And how do I do that? What is the name and usage of the flag?

**Comment by volzhs** [comment]
I want to know how to do this too. :)

**Comment by punto-** [comment]
It's an environment variable during compilation. So on a linux shell would
be something like this:

SCRIPT_AES256_ENCRYPTION_KEY="ffffffffffffffffff" scons p=android
target="release"

(make sure it's an actual AES256 hex key)

**Comment by ScyDev** [comment]
Thanks! :)

I wonder why these things are never documented ...

**Comment by okamstudio** [comment]
documenting takes way too much time, hopefully next godot site will allow
community made documentation :(


On Sat, Jun 20, 2015 at 10:16 AM, ScyDev <notifications@github.com> wrote:

> Thanks! :)
>
> I wonder why these things are never documented ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2131#issuecomment-113768203>.
>



-- 

*OkamStudio*

**Comment by ScyDev** [comment]
It is still just one tick of a checkbox to make this GitHub wiki editable by the community.

**Comment by KillerJaguar** [comment]
>It is still just one tick of a checkbox to make this GitHub wiki editable by the community.

I really wish they'd do this instead of bottle necking for the new site. The documentation can be moved over when it goes live. It would help everyone to let the GitHub wiki editable now. I don't understand what's the problem.

**Comment by ScyDev** [comment]
Same here... I've been waiting for half a year now for the wiki to be opened to the public :(

**Comment by ScyDev** [comment]
I have re-compiled the templates and the editor with:
SCRIPT_AES256_ENCRYPTION_KEY="E14D690C99769BDF5D447145E91298DEB021492B8C81E9120D66CE9464DAB0D9"

Below is the error log, when I try to run the exported game.

Has anyone had success with this?

```
:~$ '/media/PROJECTS/Godot Projects/No Rest for the Wicked Ones/release/No Rest for the Wicked Ones - DEMO v0.94 - linux.32' 
open and parse!
MAGIC: 1128612935
MODE: 1
ERROR: open_and_parse: Condition ' String::md5(md5.digest)!=String::md5(md5d) ' is true. returned: ERR_FILE_CORRUPT
   At: core/io/file_access_encrypted.cpp:70.
ERROR: load_byte_code: Condition ' err ' is true. returned: err
   At: modules/gdscript/gd_script.cpp:1994.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: modules/gdscript/gd_script.cpp:2671.
ERROR: load: Method/Function Failed, returning: RES()
   At: core/io/resource_loader.cpp:209.
ERROR: poll: Method/Function Failed, returning: error
   At: core/io/resource_format_xml.cpp:1437.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:136.
ERROR: load: Method/Function Failed, returning: RES()
   At: core/io/resource_loader.cpp:209.
ERROR: start: Condition ' !scene ' is true. returned: false
   At: main/main.cpp:1260.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound/spatial_sound_server_sw.cpp:598.
ERROR: free: Attempt to free invalid ID
   At: servers/spatial_sound_2d/spatial_sound_2d_server_sw.cpp:612.
freed code id 1
ERROR: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:1783.

```

**Comment by ScyDev** [comment]
@KillerJaguar I've forked the official Godot wiki and made it editable by the public.
https://github.com/ScyDev/godot/wiki

GitHub ensures that at any time can Okam Studio merge all the additions into the official wiki, if they so choose. And this also works the other way around.

Of course, this is far from ideal.

**Comment by punto-** [comment]
@ScyDev what's the exact command you're using to compile the new binary?

**Comment by punto-** [comment]
Also check if after compiling you have the file
code/script_encryption_key.cpp with your key (file is created in core/SCsub)

**Comment by ScyDev** [comment]
@punto- 

SCRIPT_AES256_ENCRYPTION_KEY="E14D690C99769BDF5D447145E91298DEB021492B8C81E9120D66CE9464DAB0D9"

scons -j4 platform=x11 target=release_debug

And for all the templates I'm using this script: 
https://github.com/okamstudio/godot/wiki/compiling_batch_templates

In fact, I have all these commands in a single shell script, in this order.

Will check for that file once the current build is done...

**Comment by punto-** [comment]
oh, it's actually all 1 command, like this:

SCRIPT_AES256_ENCRYPTION_KEY="your_key" scons p=x11 etc

if you want to do it in 2 commands, the first one should be

export SCRIPT_AES256_ENCRYPTION_KEY="your_key"

and then the scons command.

**Comment by ScyDev** [comment]
Thanks @punto-,  trying that now.

I did a test with "echo $SCRIPT_AES256_ENCRYPTION_KEY" before compiling, and that did output the keys value, so I thought that was ok.

**Comment by ScyDev** [comment]
That did the trick. Thanks again!

I made a short step by step: https://github.com/ScyDev/godot/wiki/Export-Encrypt-Scripts
