### ISSUE TITLE
Android 2.3.3 Crash

### ISSUE THREAD

**Issue by mohaalak** [okamstudio/godot#2141]
Platformer Example crash on android versions before 4 , it does not show any force close or anything, just a black screen then it just got out of app this is the stacktrace

06-21 21:29:02.379: W/dalvikvm(21511): Link of class 'Lcom/android/godot/Godot$1;' failed
06-21 21:29:02.379: E/dalvikvm(21511): Could not find class 'com.android.godot.Godot$1', referenced from method com.android.godot.Godot.UiChangeListener
06-21 21:29:02.379: W/dalvikvm(21511): VFY: unable to resolve new-instance 217 (Lcom/android/godot/Godot$1;) in Lcom/android/godot/Godot;
06-21 21:29:02.379: W/dalvikvm(21511): VFY: unable to resolve virtual method 661: Landroid/view/View;.setSystemUiVisibility (I)V
06-21 21:29:02.399: W/dalvikvm(21511): VFY: unable to resolve virtual method 661: Landroid/view/View;.setSystemUiVisibility (I)V
06-21 21:29:02.399: I/ApplicationPackageManager(21511): cscCountry is not German : THR
06-21 21:29:02.409: D/GODOT(21511): ** GODOT ACTIVITY CREATED HERE ***
06-21 21:29:02.549: I/VoiceActionsFactory(21028): Applications list changed, recalculating supported actions
06-21 21:29:02.649: D/PhoneApp(11294): updateProximitySensorMode: lock already released.
06-21 21:29:02.869: I/DEBUG(11199): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-21 21:29:02.869: I/DEBUG(11199): Build fingerprint: 'samsung/GT-S5830/GT-S5830:2.3.3/GINGERBREAD/JPKP9:user/release-keys'
06-21 21:29:02.879: I/DEBUG(11199): pid: 21511, tid: 21511  >>> org.godotengine.platformer <<<
06-21 21:29:02.879: I/DEBUG(11199): signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 810570d8
06-21 21:29:02.879: I/DEBUG(11199):  r0 00000000  r1 00000000  r2 810570ca  r3 81cf0c68
06-21 21:29:02.879: I/DEBUG(11199):  r4 81cf0cd8  r5 0000000a  r6 00000004  r7 00000000
06-21 21:29:02.879: I/DEBUG(11199):  r8 803182c0  r9 0000cec8  10 4428fb98  fp 46517ad4
06-21 21:29:02.879: I/DEBUG(11199):  ip 81ce4c4c  sp bea3f088  lr b00037f5  pc 810570d8  cpsr 80000010
06-21 21:29:02.879: I/DEBUG(11199):  d0  4024000000000000  d1  4033000000000000
06-21 21:29:02.879: I/DEBUG(11199):  d2  bfd3441350baf6de  d3  c1493000c1323800
06-21 21:29:02.879: I/DEBUG(11199):  d4  4900000040dcb000  d5  000000000006e580
06-21 21:29:02.879: I/DEBUG(11199):  d6  4515a00000000800  d7  40800000c48ee000
06-21 21:29:02.879: I/DEBUG(11199):  d8  0000000000000000  d9  0000000000000000
06-21 21:29:02.879: I/DEBUG(11199):  d10 0000000000000000  d11 0000000000000000
06-21 21:29:02.879: I/DEBUG(11199):  d12 0000000000000000  d13 0000000000000000
06-21 21:29:02.879: I/DEBUG(11199):  d14 0000000000000000  d15 0000000000000000
06-21 21:29:02.879: I/DEBUG(11199):  scr 80000012
06-21 21:29:03.149: I/DEBUG(11199):          #00  pc 000570d8  /mnt/asec/org.godotengine.platformer-1/lib/libgodot_android.so
06-21 21:29:03.159: I/DEBUG(11199):          #01  lr b00037f5  /system/bin/linker
06-21 21:29:03.159: I/DEBUG(11199): code around pc:
06-21 21:29:03.159: I/DEBUG(11199): 810570b8 000076fc 00007560 00007328 000073b4 
06-21 21:29:03.209: I/DEBUG(11199): 810570c8 e59f3068 e92d00f0 e08f3003 e2834070 
06-21 21:29:03.209: I/DEBUG(11199): 810570d8 eddf0b12 eddf1b13 e1a00003 e59f1050 
06-21 21:29:03.219: I/DEBUG(11199): 810570e8 e59f2050 f4440a8f e3a0c000 e3a07d0a 
06-21 21:29:03.219: I/DEBUG(11199): 810570f8 e3a06e1e e3a05001 e5a0c080 e5837064 
06-21 21:29:03.219: I/DEBUG(11199): code around lr:
06-21 21:29:03.219: I/DEBUG(11199): b00037d4 2a002601 1e48d003 18e40083 00b64276 
06-21 21:29:03.219: I/DEBUG(11199): b00037e4 e0061c0d 19a46823 32031e5a 4798d800 
06-21 21:29:03.219: I/DEBUG(11199): b00037f4 2d003d01 bd70dcf6 1c03b510 1c0433e8 
06-21 21:29:03.219: I/DEBUG(11199): b0003804 28006818 3304d004 22016819 ffdef7ff 
06-21 21:29:03.219: I/DEBUG(11199): b0003814 682334f4 d0002b00 bd104798 4c05b510 
06-21 21:29:03.219: I/DEBUG(11199): stack:
06-21 21:29:03.219: I/DEBUG(11199):     bea3f048  803182c0  /system/lib/libdvm.so
06-21 21:29:03.219: I/DEBUG(11199):     bea3f04c  0000cec8  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f050  4428fb98  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f054  afd29857  /system/lib/libc.so
06-21 21:29:03.219: I/DEBUG(11199):     bea3f058  00000000  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f05c  afd1ca69  /system/lib/libc.so
06-21 21:29:03.219: I/DEBUG(11199):     bea3f060  81cf0c00  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f064  81ce5000  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f068  00000020  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f06c  8105e460  /mnt/asec/org.godotengine.platformer-1/lib/libgodot_android.so
06-21 21:29:03.219: I/DEBUG(11199):     bea3f070  81cf0bfc  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f074  81ce5000  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f078  00000000  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f07c  81ce3fb0  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f080  df002777  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f084  e3a070ad  
06-21 21:29:03.219: I/DEBUG(11199): #00 bea3f088  81ce3fb4  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f08c  0000000a  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f090  00000004  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f094  00000000  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f098  b000e744  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f09c  b000e740  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f0a0  00002755  
06-21 21:29:03.219: I/DEBUG(11199):     bea3f0a4  b00038a9  /system/bin/linker
06-21 21:29:03.219: I/DEBUG(11199):     bea3f0a8  00d0b000  
06-21 21:29:03.229: I/DEBUG(11199):     bea3f0ac  afd00000  /system/lib/libc.so
06-21 21:29:03.229: I/DEBUG(11199):     bea3f0b0  00000020  
06-21 21:29:03.229: I/DEBUG(11199):     bea3f0b4  b000e660  
06-21 21:29:03.229: I/DEBUG(11199):     bea3f0b8  81ce40c8  
06-21 21:29:03.229: I/DEBUG(11199):     bea3f0bc  b000e660  
06-21 21:29:03.229: I/DEBUG(11199):     bea3f0c0  00002755  
06-21 21:29:03.229: I/DEBUG(11199):     bea3f0c4  b0004f93  /system/bin/linker
06-21 21:29:03.229: I/DEBUG(11199):     bea3f0c8  00000020  
06-21 21:29:03.229: I/DEBUG(11199):     bea3f0cc  b000e6ec

**Comment by reduz** [comment]
Not a bug, this device does not support armv7 (likely Tegra 2).If you want to build Godot yourself so it works in this device, you can try doing it with armv6=true but default builds do not support it.
