### ISSUE TITLE
get_current_scene() is null when changing scenes

### ISSUE THREAD

**Issue by macramole** [okamstudio/godot#2147]
Using https://github.com/okamstudio/godot/wiki/tutorial_singletons for changing between scenes cause get_tree().get_current_scene() to be null

Example: https://dl.dropboxusercontent.com/u/1641659/get_tree_get_current_scene_test.zip

**Comment by reduz** [comment]
that is expected, both APIs use different means to change the scene, as the
root node can have any number of children.

Still though, you can set the current scene manually if you wish to retain
compatibility. I just added it to the tutorial so you can check how to do
it over there

**Comment by macramole** [comment]
Alright ! thanks

2015-06-22 12:05 GMT-03:00 Juan Linietsky <notifications@github.com>:

**Comment by macramole** [comment]
this should be closed, shouldn't it ?

**Comment by bojidar-bg** [comment]
@macramole well, you can click on close issue, can't you?

**Comment by macramole** [comment]
oh sorry, didn't know about that.
