### ISSUE TITLE
Make Github wiki publically editable

### ISSUE THREAD

**Issue by Fiona** [okamstudio/godot#2161]
As mentioned in #2131, it is a very simple task to make the wiki editable by the public. There are a number of users that have expressed a strong desire to improve the documentation and this would allow them to do so.

I know we are waiting for the new community website, but this is a promise made long ago and there is no clear timescale for when it eventually emerges.

Making the wiki editable would be a good stop gap measure, any work done will be moved over to the new site when it emerges.

**Comment by ScyDev** [comment]
What Fiona said!

**Comment by reduz** [comment]
wiki will be moved to the new site very soon, which will be editable by the
community

**Comment by Fiona** [comment]
Yes but as I said, that was a promise made a long time ago and we have no idea when it will be in reality. I'm of the opinion that even if it's only a month away, a lot of good can be done to improving the docs even in that amount of time.

Come on Juan, it's just one click. 

![pleze](http://i.imgur.com/CZtPrs0.jpg)

**Comment by ScyDev** [comment]
True, true, true.

I've heard that before, so long ago, in a galaxy far, far away.

![na9x3](https://cloud.githubusercontent.com/assets/1307146/8308750/d42a22cc-19c6-11e5-8b30-c1b85c677142.jpg)

**Comment by ScyDev** [comment]
Btw. for all who come along here, I forked the Godot wiki and made it public: https://github.com/ScyDev/godot/wiki

But it would be so much better to directly edit the official Godot wiki.

**Comment by TheoXD** [comment]
Merging new wiki changes is just extra work for me, now when most of the wiki pages are already converted to a different markdown. I recently got extra work to do when we've decided to move away from azure to a new VPS, so I updated CMS to the latest version and put changes on git.
There is one last bug left to fix that prevents me from moving the entire forum, but trust me, it's worth waiting :)

**Comment by Fiona** [comment]
Okeeee :( 

![official sad godot cat](http://i.imgur.com/AI13Kpr.jpg)

**Comment by okamstudio** [comment]
There's been many cases of project wikis trolled by anonymous users when
the wiki is this open, and GitHub does not have finer control on this. We
need to be able to have a wiki where users are given editing permissions
upon request, which will be possible in our new website


On Tue, Jun 23, 2015 at 12:55 PM, Fiona Burrows <notifications@github.com>
wrote:

> Closed #2161 <https://github.com/okamstudio/godot/issues/2161>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2161#event-337978765>.
>



-- 

*OkamStudio*
