### ISSUE TITLE
Tilemaps don't keep collision masks

### ISSUE THREAD

**Issue by Mikepicker** [okamstudio/godot#2178]
I tried to set custom collision masks on tiles belonging to tilesets, but once I import them in a level I notice that collisions don't work properly. Can someone confirm the issue?

**Comment by reduz** [comment]
this is expected unfortunately, Godot uses a single body to group all the
shapes, so it's impossible to set different mask for each tile
what you can do instead is use more than one tilemap in the scene, with
different masks

**Comment by Mikepicker** [comment]
Perfect, thanks reduz
