### ISSUE TITLE
Exporting / Importing new tileset.xml does not work properly

### ISSUE THREAD

**Issue by Mikepicker** [okamstudio/godot#2184]
Step to reproduce it:
1. Create a tileset_edit as suggested on the tutorial
2. Load it into a (level) scene and use it in a Tilemap node
3. Modify the tileset_edit (e.g. delete some tiles) and re-export
4. Go back on your level scene: you'll see that the tilemap has not been reloaded properly

This continue to happen even if you clear the current "Tile Set" on your level and try to reload it.

**Comment by Ciastex** [comment]
I believe it's the expected behavior because modifying used tiles messes up the tile association system. You have to repaint your map manually.

**Comment by Mikepicker** [comment]
Yep, I came up with the same idea, but the problem is that on the left bar (which displays the tiles to use) I am still able to see the old tiles that I previously deleted.

**Comment by Ciastex** [comment]
Be sure to set "merge with existing" to off in export dialog.

**Comment by Mikepicker** [comment]
That does the job :) Thanks Clastex :+1:
