### ISSUE TITLE
_init and inheritance.  Expected 1 arguments.

### ISSUE THREAD

**Issue by bitwes** [okamstudio/godot#2193]
If I create a class that takes a parameter in the _init method, I will get an error when trying to create an instance of a subclass of it.  Everything works fine until you call .new on the sublcass.  

In the below example I will get the error:  Invalid call to function '_init'.  Expected 1 arguments on line 27 (func _init(val) in the SubInitParam class).  If I comment out the last two lines everything works fine.  Stack trace indicates the error started at 43 (where .new is called)

You appear to be able to add parameters to _init in subclasses (SubBaseWithParameter instances work fine), but if the base has one, everything goes kaput.

``` python
extends Node2D

class BaseClass:
	var hello='w'
	func _init():
		hello='world'

class SubClass:
	extends BaseClass
	
	func _init():
		hello='goodbye'

class SubBaseWithParameter:
	extends BaseClass
	func _init(val):
		hello='with param:  ' + val

class BaseInitParam:
	var hello = 'asdf'
	
	func _init(val):
		hello = val

class SubInitParam:
	extends BaseInitParam
	func _init(val):
		hello = 'sub:  ' + val

func _ready():
	var base = BaseClass.new()
	print(base.hello)
	
	var sub = SubClass.new()
	print(sub.hello)

	var sub_with = SubBaseWithParameter.new('this works')
	print(sub_with.hello)

	var base_param = BaseInitParam.new('another one')
	print(base_param.hello)
	
	var sub_param = SubInitParam.new('yet another one')
	print(sub_param.hello)
```
This prevents you from being able to inherit from any class that has a parameter in the _init method.  
You also can't just make the sub class's _init method have no parameters.  You get the same error.

As a side note, I don't think this is restricted to just _init and inheritance.  I've seen this in other places as well but I've been able to work around them in the past.  I've currently painted myself into a corner and being able to do this would save a lot of refactoring.  

P.S.
This might be related or a separate issue, but calling .new() with the wrong number of parameters crashes the app (not the editor) with no message, just 'godot.exe has stopped working'

``` python
#call without parameter when it has one
var sub_param = SubInitParam.new()
#call with parameter when it doesn't have one
var sub = SubClass.new(1)
```

**Comment by reduz** [comment]
you forgot to pass back a constructor argument to the previous constructor:

class SubInitParam:
    extends BaseInitParam
    func _init(val).(val):
        hello = 'sub:  ' + val

**Comment by bitwes** [comment]
Ahhhhh.  I hadn't seen that syntax anywhere in the documentation.  So if the superclass expects an argument, you can't override that in the subclass?  Does that also explain why I'm seeing init being called first, even when I don't call it?  I would have expected that the superclass's init method wouldn't be called in the subclass until I explicitly called ._init()?

Sorry if this is covered somewhere and I just hadn't found it yet.  I'd be happy to be pointed to some documentation.

**Comment by okamstudio** [comment]
https://github.com/okamstudio/godot/wiki/gdscript#arguments-to-parent-constructor

On Fri, Jun 26, 2015 at 11:29 PM, Butch Wesley <notifications@github.com>
wrote:

> Reopened #2193 <https://github.com/okamstudio/godot/issues/2193>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2193#event-341779081>.
>



-- 

*OkamStudio*

**Comment by bitwes** [comment]
Ok.  That muddies the waters a bit.  Any hope of that changing?  Seems like there was probably a good reason for the approach but it screws things up if you didn't want to call the super's constructor, or call it later.  Maybe override some defaults for the subclass then fire off the constructor.  things like that.

Are other superclass methods called by default?  On the build I just did today, it looked like the super's _process(delta) was being called right off the bat, then the subclass.  I called the super's and in the sub's and everything happened twice as fast.

**Comment by bitwes** [comment]
I found other threads that jogged my memory.  I think I knew this at one point or another but hadn't dealt with it in awhile.  Thanks for pointing me in the right direction.  If anyone else finds this, this thread helped me out. 

http://www.godotengine.org/forum/viewtopic.php?f=12&t=731

**Comment by EdwardAngeles** [comment]
The link is dead and I'm having the same issue D:

I don't want a parent's function class to be called.
