### ISSUE TITLE
Non-power of 2 textures don't repeat

### ISSUE THREAD

**Issue by sketchyfun** [okamstudio/godot#2206]
If you use a texture which isn't power of 2 (or at least the same width/height) then the repeat texture flag doesn't work, or stops working very quickly. 

I've looked through the source to see if I can see the problem, but I haven't had any luck so far.

**Comment by reduz** [comment]
not supported by openGL 2

**Comment by reduz** [comment]
er.. OpenGLES2 backend I mean

**Comment by sketchyfun** [comment]
Ahh okay, I wasn't aware it was a limitation of OpenGL ES 2.0. I'll close this now.
