### ISSUE TITLE
Error ld cannot find -lGL when compiling in Ubuntu 14.04 

### ISSUE THREAD

**Issue by FlyingPumba** [okamstudio/godot#2208]
As title says, I'm trying to compile godot in Ubuntu 14.04
I have run the command:
```
apt-get install scons pkg-config libx11-dev libxcursor-dev build-essential libasound2-dev libfreetype6-dev libgl1-mesa-dev libglu-dev libssl-dev libxinerama-dev
```
and I thought I had all dependencies needed.. but it turns out I don't.
After running:
```scons platform=x11```
It returns with error:
```
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.tools.64] Error 1
scons: building terminated because of errors.
```
Can someone help me debug this problem ? I don't know which library GL is.

**Comment by FlyingPumba** [comment]
If it's talking about OpenGL, I think I have it installed. Running
```glxinfo | grep "OpenGL version"```
yields:
```OpenGL version string: 4.4.12967 Compatibility Profile Context 14.20```

**Comment by romulox-x** [comment]
You should have a file named libGL.so on your system.  This is what -lGL is looking for.  Mine's in /usr/lib/libGL.so in Ubuntu 13.10.  I imagine it's the same in 14.04, but I'm just assuming.  Do you have this file?

**Comment by FlyingPumba** [comment]
@romulox-x Nop, I don't have no such file. However, I do have: /usr/lib/fglrx/libGL.so (ATI file)

**Comment by FlyingPumba** [comment]
In case anyone has the same problem in the future: I managed to solve it by creating a symlink to the exiting libGL.so
```sudo ln -s /usr/lib/fglrx/libGL.so /usr/lib/libGL.so```
Then restarted, and run again ```scons platform=x11```
Now it built whit no problems.

**Comment by choikwa** [comment]
Alternatively, LD_LIBRARY_PATH can be set to include /usr/lib/fglrx.
