### ISSUE TITLE
RegEx does not detect end of line anchor

### ISSUE THREAD

**Issue by leezh** [okamstudio/godot#2230]
On 1.1stable Windows, the following code:

    var test = RegEx.new()
    test.compile("\\w+$")
    print(test.find("hello"))
    print(test.find(" hello"))
    print(test.find("hello!"))
    print(test.find("hello world!"))
    test.compile("^\\w+")
    print(test.find("hello"))
    print(test.find(" hello"))
    print(test.find("hello!"))
    print(test.find("hello world!"))

should match the first two lines but instead produces this output:

    -1 <-- Should be 0
    -1 <-- Should be 1
    -1
    -1
    0
    -1
    0
    0

**Comment by punto-** [comment]
Yeah the RegEx class is just some library we found that suited some needs
at some point, but it's not really a complete implementation.. Another
problem it has is that it's not endian safe, so for example on PS3 it
failed completely :( The only advantage it has is that it's really tiny,
which is something we would definitely want to keep if we ever replace it.

**Comment by leezh** [comment]
Hey, I've been working on a replacement for trex and wondered what you thought about it. Is this something along the lines of what you'd want?

https://github.com/leezh/nrex

**Comment by punto-** [comment]
that looks good.. does it allocate memory? we usually prefer stuff that
uses our own String, Vector, etc instead of STL (another thing that was a
pain in the ass to compile on ps3 and similar platforms), but it looks like
a great alternative to the current one..

**Comment by leezh** [comment]
It is quite reliant on STL, so that would be an issue. :/

As for memory allocation, each node is allocated individually while compiling. They're automatically cleaned up when the destructor is called. The searching function uses mostly stack memory.

**Comment by reduz** [comment]
We can probably replace the containers

**Comment by leezh** [comment]
Yup, so with the latest commit, https://github.com/leezh/nrex should now be free of STL containers. ^_^ Tested on Linux and Windows. I am quite keen on getting this to work as my text-heavy game would benefit a lot from this. Should a new bug report be opened for the library replacement effort?

**Comment by punto-** [comment]
Can you make it use String instead of std::string? apis should be pretty
similar, String stores wide chars directly.

**Comment by leezh** [comment]
I already got rid of the std::string dependency. All that is needed is a c string pointer. I should probably update the README example to reflect that. If you edit the header to uncomment NREX_UNICODE, the character type would also change to a wchar_t.

**Comment by punto-** [comment]
Oh I see, I was looking at the nrex_compile_error, which still takes a
std::string parameter, the nrex api looks good. Can you change the
memory allocations to use our allocators? You need to replace "new"
with "memnew" and "memnew_arr" (for arrays), and delete with
"memdelete" and "memdelate_arr". For example:

SomeClass* some_instance = memnew(SomeClass);
SomeClass* some_instance = memnew(SomeClass(constructor_parameter));
uint8_t *some_buffer = memnew_arr(uint8_t, buf_size);

and

memdelete(some_instance);
memdelete_arr(some_buffer);

It's all provided by code/os/memory.h. I think that should be the last
change we need, the rest looks good.

**Comment by leezh** [comment]
Done :D I've also added a configuration file so that updating the library means not having to edit the two main files.

There should be two config files in there. One is for the library to run standalone, and the other should be using Godot's memory management.
