### ISSUE TITLE
MultiScenes: show Scene of selected .gd script

### ISSUE THREAD

**Issue by AlexHolly** [okamstudio/godot#2262]
It's annoying to open the Scene tab manually after you select a .gd script from the list.

**Comment by reduz** [comment]
but a script could be in multiple scenes, how do you propose changing this?

**Comment by AlexHolly** [comment]
You can skip the first ideas, and go to 4. i think it's the easiest and won't hurt anybody.

1. My scripts are unique, lets say i have a scene that has only one Node(Wall) with a script("wall.gd")
Now i build a Map with this Node(Wall) and use the "Instance a scene file as a Node" function.

This function represents a link to the real scene and we can see that it is a link (i hope).
1.1. So when we select "wall.gd" it will probably check which scene is using the wall.gd and is not a link.

2. Lets say there are really multiple scenes that use the same script, would it hurt to just open the first?

3. Another Idea is to open/select the first script in the selected scene tree, so when you click on the script tab the first script is already selected.

4. Now I understand the yellow mark in the script tab ..! Let's say there is only one script with a marker on a selected scene("Wall") then it will automatically select this script("Wall.gd"). Now i click on the script tab and it will show what i expect(My "Wall.gd").

**Comment by okamstudio** [comment]
Actually, I was thinking of adding a mode when you select a scene tab, it
opens the dominant script

On Fri, Aug 21, 2015 at 10:37 PM, AlexHolly <notifications@github.com>
wrote:

> Closed #2262 <https://github.com/okamstudio/godot/issues/2262>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2262#event-389369342>.
>



-- 

*OkamStudio*

**Comment by AlexHolly** [comment]
What defines a "dominant script"? Most lines, higher in tree or maybe most recent changed?

The reason for closing this issue is the script button on the scene tabs, it is already a lot better when before with this feature.

Maybe automatically selecting the scene when klicking on the script button and adding different modes on the script button is a good solution for this issue.
