### ISSUE TITLE
Godot 1.1 crashing on startup (Win7 32bit)

### ISSUE THREAD

**Issue by jfmdev** [okamstudio/godot#2267]
When I try to execute `godot_win32-1.1.stable.exe`, the application crash, showing the message: **"godot_win32-1.1.stable.exe has stopped working"**

In the console (which is opened when executing the .exe file), the next entries are displayed:

```
EXEC PATHP: C:\Workpace\godot_win32-1.1.stable.exe
EXEC PATHP: C:\Workpace\godot_win32-1.1.stable.exe
DETECTED MONITORS: 1
```

The PC specs are the following:

```
OS: Windows 7 Professional SP1
Processor: Pentium Dual-Core E5800 3.20GHz
Video Adapter: Intel(R) G41 Express Chipset
```

**Comment by bojidar-bg** [comment]
@jfmdev Just a blind suggestion: are your drivers up-to-date?

Also, are you able to run games/programs that require openGL?

**Comment by jfmdev** [comment]
@bojidar-bg Thanks for the suggestion, but:
 * Yes, my drivers are up-to-date.
 * Yes, I'm able to run programs that require OpenGL (I can run Blender, Unity and MakeHuman without problems).

**Comment by bojidar-bg** [comment]
@jfmdev I'm pretty sure I've seen this problem on a friend's machine. (though I don't remember the workaround). Maybe you can try to build from source yourself?
Also, are you sure you are on a 32bit machine? If you aren't sure you can try the 64bit version too :smiley: .

@jfmdev ~ BTW, Unity uses DirectX on windows (except if you run it with the --force-opengl flag) :laughing:

**Comment by jfmdev** [comment]
@bojidar-bg Yes, I'm 100% sure that's a 32bit machine.
I tried to build _godot_ from the source, but the error keeps occurring.

By adding some `cout` instructions to code, I have find out that the application crash when tries to execute the line 1203 of the file `os_windows.cpp`:  `visual_server->init();`. And if I go to the definition of that method, in the file `visual_server_raster.cpp`, the application crash on the line 7466: `rasterizer->init();`.

**Comment by bojidar-bg** [comment]
@jfmdev Where exactly in the `rasterizer->init()` does it crash :smiley: ?

**Comment by jfmdev** [comment]
I have also build the release 1.0, but the error occurs also in that version.

**Comment by bojidar-bg** [comment]
@jfmdev ~ What about downloading the 1.0 version? Does it work?

**Comment by jfmdev** [comment]
@bojidar-bg Thanks for your help, but it seems that I'm at a dead end: Godot do not works in some Intel GMA based GPUs (source [Error while starting godot_win32.exe](http://www.godotengine.org/forum/viewtopic.php?f=11&t=45) and [Installer Crashes #995 ](https://github.com/okamstudio/godot/issues/995)), so _no godot for me_...

**Comment by bojidar-bg** [comment]
@jfmdev Well, installing linux or playing around with virtualbox was always an option..... :wink:

**Comment by erik90mx** [comment]
I have the exact same issue, Windows 7 32 bits , this hardware specs: https://translate.google.com.mx/translate?sl=es&tl=en&js=y&prev=_t&hl=es-419&ie=UTF-8&u=https%3A%2F%2Fpcel.com%2FAcer-5736Z-4359-70825&edit-text=&act=url

**Comment by VictorNutty** [comment]
Try to run Godot on compatibility mode and in administrator mode, I had the same problem and this solved it.
Right click on Godot > Properties > Compatibility > Select a Operating System that you think it will work properly > (at the end of the window) Check run as administrator > OK > Test! :laughing: 
Or
Right click on Godot > Solve compatibility problems > Follow the instructions :wink:

**Comment by akien-mga** [comment]
Duplicate of #156, related to #1162.
