### ISSUE TITLE
How to realize the function like HingeJoint2D in unity

### ISSUE THREAD

**Issue by zhagsenkk** [okamstudio/godot#2276]
There just exists HingeJoint in 3D.

**Comment by bojidar-bg** [comment]
@zhagsenkk If you check the Rube Goldberg demo, you will see that PinJoin2D-s were used to make the pendulum. (not sure if you mean this, though)

**Comment by cheesymoo** [comment]
I know this issue is closed, but I think it should be reopened for 3.0
There is still no HingeJoint2D and I don't know if the Rube Goldberg demo made it to 3.0

PinJoint2D almost gets there, but I cannot figure a way to constrain the allowed rotation of the connected bodies.

**Comment by vnen** [comment]
@cheesymoo if you're missing something in PinJoint2D, just open a new issue about. No need to revive 3 year-old issue which was closed by the OP.
