### ISSUE TITLE
Stop updating the godot project?

### ISSUE THREAD

**Issue by cjmxp** [okamstudio/godot#2287]
Stop updating the godot project?

**Comment by volzhs** [comment]
not at all

**Comment by MrGreenTea** [comment]
yes please! ty

**Comment by reduz** [comment]
No, Juan on trip in Europe, just back from it.

**Comment by Ace-Dragon** [comment]
More information on what was going on
http://www.godotengine.org/wp/godot-at-rmll2015-france/

This was why there was such a break in the development

**Comment by reduz** [comment]
it makes me happy that so many pull requests and issues piled up in just so
weeks though, community is contributing more and more

**Comment by Ace-Dragon** [comment]
I just hope the Godot engine becomes that ideal open source game development solution that the Blender Game Engine wasn't able to fully achieve (this includes continual improvement on Godot's I/O with Blender).

**Comment by pixelr0** [comment]
i wish godot supported Ubuntu Phones, there are already 3 Ubuntu Phones on sale http://www.ubuntu.com/phone/devices

**Comment by reduz** [comment]
I wish ubuntu paid godot developers to support their phones :P

**Comment by punto-** [comment]
3 phones? That's enough for 2 people to have a conversation and 1 to get a
busy signal. Nice field testing strategy.

**Comment by slapin** [comment]
+1 for FirefoxOS phone too And Nokia N900 for that matter.

**Comment by cjmxp** [comment]
Welcome back!
