### ISSUE TITLE
EDITING:: Extreme memory inefficiencies in the update_tree function (when loading a scene)?

### ISSUE THREAD

**Issue by Ace-Dragon** [okamstudio/godot#2289]
Supposedly I found that Godot starts throwing *out of memory* errors and fails to load the tree setup when a scene file gets to where it contains a thousand or so nodes (including the nodes contained with scene instances).

Case in point
![godot_errors](https://cloud.githubusercontent.com/assets/10081256/8814594/ec323864-2fd3-11e5-9a3b-275b217ade36.jpg)

There's a problem though, this error is on a machine with 16 gigabytes of RAM and I would think the engine can load up a few thousand nodes within that amount of space. Otherwise it could be a potential turnoff as people will find Godot unable to handle anything more than a somewhat small level size.

I've already tried reducing the net number of scene instances surrounding the spikes, but got the same result. The July 3 build of Godot meanwhile manages to load the tree, but prevents you from doing anything with it.

I hope this is something that can be resolved on Godot's side, as proper handling of large numbers of objects is a must for a modern game engine.

**Comment by Ace-Dragon** [comment]
This is using Godot on Windows 7 64 bit by the way using a 64 bit Godot build, so it's definitely not an issue of bits.

**Comment by punto-** [comment]
looks like it's running out of memory on the message queue of one of the
servers (probably VisualServer), can you try loading the scene using an
InteractiveLoader and call VisualServer::sync() in between a couple of
calls to poll()?

**Comment by Ace-Dragon** [comment]
How do I do that?

I'm simply opening the scene in the editor by selecting the file in the file browser window (the game is not running). I also don't have any compiler and source-code knowledge so I can't do anything that requires that.

**Comment by punto-** [comment]
You don't need to compile, but it's just to load the scene with a script..
If you need it on the editor then you need a way to make that queue bigger,
or maybe the engine can try to flush it in the middle of the load.

**Comment by Ace-Dragon** [comment]
I'm not really sure what functions are there to make the queue bigger (that are available in GDscript or accessible via the settings at least).

I found the *editor script* field in the settings menu, but I'm not sure what to do so the scene loads properly.

**Comment by Ace-Dragon** [comment]
Did a bit of sleuthing work (looking at the console errors), and found that changing a couple of value fields I didn't think were working to fix it has fixed it.
![godot_errors_fixed](https://cloud.githubusercontent.com/assets/10081256/8835695/a99b322c-3081-11e5-9333-0a2dd9c5ee42.jpg)

Now to see about reducing the number of nodes to prevent it from happening again.
