### ISSUE TITLE
GDScript: Parent variables aren't accessible in sub classes

### ISSUE THREAD

**Issue by Cybolic** [okamstudio/godot#2303]
Put in another way, sub classes seem to be instanced in a separate scope from the main class.

Example script showing the issue: http://pastebin.com/wSF6bxhY

Expected output: "Hello World"
Actual output: Parse error: Identifier not found: global_var

**Comment by okamstudio** [comment]
There are no globals

**Comment by Cybolic** [comment]
Member variables of the parent class then? In any case, shouldn't they be accessible somehow?

**Comment by FEDE0D** [comment]
There is no issue here. You have to use the 'extends' keyword to extend another class.
The parent variables are accessible as in any other language. If you want to use a parent function you use the dot, example: 
```gdscript
func hello():
    .hello()
    #something else
```

**Comment by punto-** [comment]
This is what you'd normally use upvalues (or sometimes closures) for, but
we don't have them. In this case you need an instance of the parent to
access its members, but keep in mind that if the parent also has an
instance of the child class, you're creating a cyclic reference, so it
won't be deleted when they both go out of scope (you can solve that with a
weak reference).

**Comment by Cybolic** [comment]
Ah, ok. So each class is completely separate in scope, got it.
Maybe I just approached if from the wrong angle, but it might be worth highlighting in the wiki.
