### ISSUE TITLE
Is there any function can realise ClippingNode like this.

### ISSUE THREAD

**Issue by zhagsenkk** [okamstudio/godot#2312]
![wkiom1q20_oae1zaabnuemwlvrk144](https://cloud.githubusercontent.com/assets/10054853/8934497/87b96a22-357a-11e5-8496-e9b20ccb005d.gif)
This is done by cocos2d-x.Using ClippingNode function.
I want to make a gun shot function by using this. 
Thx!

**Comment by reduz** [comment]
3D or 2D?

**Comment by reduz** [comment]
you could also blit that into a texture if you wish

**Comment by zhagsenkk** [comment]
2d.like it showing in the picture,there is a hole which can see the background.i will try it tomorrow.thx!
23:50.....

**Comment by zhagsenkk** [comment]
is there any way to realize this except by shader?I'm not familiar with shader.thx

**Comment by reduz** [comment]
for this exact functionality, and given there is a variable amount of
clipping objects,
definitely the only way to do it is blitting to an image and then updating
the texture

**Comment by reduz** [comment]
i don't think it's even doable with shaders.. only modifying the texture
will work
