### ISSUE TITLE
Casting of Variant to double loses precision

### ISSUE THREAD

**Issue by marcosbitetti** [okamstudio/godot#2318]
In GDScript I have:

       dc['batman']=3.1415

I try to store it using a module:

      case Variant::REAL:
                sqlite3_bind_double(stmt, i, (double) *value);
                break;

Storede in database the value is:

      3.1414999961853

In geometry it can be inexpressive.
If I use it to store money of a character it will be sad.

**Comment by eevee** [comment]
General advice: never store money as floating-point.  Store it as an integer number of cents.

**Comment by marcosbitetti** [comment]
It not a good idea to work, store money is a example think, other cases can be affected like ranks calculation, real money, etc.

For now, my soluction is:

    String tmp = (String) *value;
    sqlite3_bind_text(stmt,i, tmp.utf8().get_data(),tmp.size()-1,SQLITE_TRANSIENT);

Well, in test:

    printf("AAA> %s\n",tmp.utf8().get_data());
    printf("BBB> %f\n",(double) *value);

The results is:

    AAA> 3.1415
    BBB>3.141500

I suppose that is not realy a Godot bug, then I focus in sqlite configuration to find it. Then close this one, for now.
