### ISSUE TITLE
preload bug

### ISSUE THREAD

**Issue by Patrulek** [okamstudio/godot#2324]
Windows 7  Godot 1.1 custom build (5 July)

I don't know if it happens with load function too, but, when we have a file i.e. "texture.png" and we want to preload this in this way:  preload("res://texture.png")  everything is okay, but if we try  preload("res://Texture.png") in editor will be everything ok, but after export to exe that file is not loaded.

**Comment by d3v0x** [comment]
I think this cannot be fixed by Godot; your file system is not case sensitive.

**Comment by Patrulek** [comment]
But it looks like a whole scene(node) stops loading because of this and returns a NIL.

**Comment by reduz** [comment]
This is kind of expected. When you run the project from the editor, Windows
filesystem is case insensitive.
When you export to standalone, it produces a pck which is a case sensitive
filesystem, so it will not work.

**Comment by Patrulek** [comment]
Ok, good to know that for future, because i spent some time locating the bug and didn't suspect something like that.
