### ISSUE TITLE
Windows console

### ISSUE THREAD

**Issue by bugless1** [okamstudio/godot#2373]
I tried -quiet or disable_stdout but nothing... The console still popup.
Is good for debugging but not for final release. I saw there was a similar issue but was closed and marked as fixed... Pretty strange...

**Comment by AlexHolly** [comment]
You mean this option? It works for me...

![hide_console](https://cloud.githubusercontent.com/assets/4741886/9288940/80e3be9e-435f-11e5-92fe-ba19fbdfae82.png)

**Comment by punto-** [comment]
are you running with a binary compiled for release? In general what should
happen is when you build with target=debug or target=debug_release, it gets
linked with /subsystem:console, so there'll be a console windows. If you
use target=release, the flag is /subsystem:window (or something) and
there's no console.

I don't know what happens on the cross compiled mingw builds tho, but there
should be something equivalent..

**Comment by deasanta** [comment]
AlexHolly suggestion worked for me on windows 7 x64 with x64 build from http://151.236.22.217/godot_win64-1.1stable.exe . bugless1 can you give a bit more information about the your environment should the solutions so far not solve your problem. Information that would help may be are you building for windows, linux, mac. Is it the default download or a compiled download from github. tnx

**Comment by bugless1** [comment]
Solved! I was missing target=release...
