### ISSUE TITLE
Exported game conflict with engine - windows

### ISSUE THREAD

**Issue by AlexHolly** [okamstudio/godot#2407]
1. Export the game in the same folder as the "godotengine.exe" is saved.
2. Start "godotengine.exe" and your exported game will start.

**Comment by TierraDelFuego** [comment]
That is a feature not a bug. You should save your games to a different folder.

**Comment by AlexHolly** [comment]
Can you tell me a use case?

**Comment by reduz** [comment]
you, godot by default looks for data.pck and runs that as priority
when you export the game, it gives you executable and pck

**Comment by AlexHolly** [comment]
ok thanks.

I always use my desktop for exports and also update the godot.exe manually after compile..

So i made a link to the /bin/godot.exe put that on the desktop.
No more manually update the engine on dekstop & export to dekstop also works :)

**Comment by okamstudio** [comment]
will probably add at some point that the executable checks for a pck of the
same name eventually instead


On Sun, Aug 30, 2015 at 7:40 PM, AlexHolly <notifications@github.com> wrote:

> ok thanks.
>
> I always use my desktop for exports and also update the godot.exe manually
> after compile..
>
> So i made a link to the /bin/godot.exe put that on the desktop.
> No more manually update the engine on dekstop & export to dekstop also
> works :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2407#issuecomment-136211670>.
>



-- 

*OkamStudio*
