### ISSUE TITLE
Download page of website is down

### ISSUE THREAD

**Issue by Viish** [okamstudio/godot#2420]
The http://www.godotengine.org/wp/download page displays:
Binary Downloads
Warning: file_get_contents(http://151.236.22.217/build.html) [function.file-get-contents]: failed to open stream: Connection timed out in /home/okamstudio/godotengine.org/wp/wp-content/plugins/insert-php/insert_php.php(48) : eval()’d code on line 3

**Comment by punto-** [comment]
There should be a couple of mirrors tho right?

**Comment by guilhermefelipecgs** [comment]
The download page don't show any mirrors.
