### ISSUE TITLE
[2.0alpha] Game runs only 800x600 when play project on editor tool bar.

### ISSUE THREAD

**Issue by volzhs** [okamstudio/godot#2426]
I changed width, height, test_width, test_height.
But It runs only 800x600 window size no matter what size in project settings.

**Comment by ippan** [comment]
have same issue, and game window always start at left down corner

**Comment by ndee85** [comment]
Can confirm this one! Same for me :(

**Comment by reduz** [comment]
merged fix, let me know if it works now

**Comment by ricpelo** [comment]
Seems to works OK. The game window always start at the left down corner of the screen. Is it a side effect or intentional?

**Comment by volzhs** [comment]
@ricpelo see Game Window Placement setting in Editor Settings.

**Comment by ricpelo** [comment]
@volzhs Great! Thank you very much :).
