### ISSUE TITLE
Thin lines around tiles in Platformer 2D Demo

### ISSUE THREAD

**Issue by ricpelo** [okamstudio/godot#2452]
I can see thin lines around tiles in Platformer 2D Demo.

Using just compiled latest git HEAD on Ubuntu and an Intel graphics controller.

![2015-09-08-164959_1280x1024_scrot](https://cloud.githubusercontent.com/assets/616169/9738113/4b6b8230-564a-11e5-9512-cfae5d4cc4a1.png)

**Comment by ricpelo** [comment]
I found a way to fix the issue:

Under Project Settings -> image_loader , uncheck "filter". Now those nasty lines are gone!

But... is there a problem or a side effect by unchecking that option?

**Comment by reduz** [comment]
not that i know, that's the regular way to do it (it's in the tutorial)

**Comment by ricpelo** [comment]
Ok, so the Platformer 2D Demo project should be fixed, IMHO.
