### ISSUE TITLE
[Feature Required] virtual keyboard on mobile

### ISSUE THREAD

**Issue by GrandFunkR** [okamstudio/godot#2456]
It is possible to have a virtual keyboard for mobile input textbox?

**Comment by punto-** [comment]
Yeah it should open automatically when you click on the textbox, although
if I remember correctly none of the mobile apis had clear methods like
"open the keyboard now" and "close the keyboard now". We had to do a bunch
of hacks to implement that.

**Comment by Dafuqz** [comment]
There is no such thing as textbox in godot, only TextEdit. That doesn't pull up keyboard in iOS devices as far as I know.
