### ISSUE TITLE
set_visible_characters for RichTextLabel

### ISSUE THREAD

**Issue by seadra** [okamstudio/godot#2462]
I'm essentially paraphrasing #1329 here, but with a clear feature request.

After all the styling is applied, the number of characters on each is determined already in rich_text_label.cpp (as far as I understand). Setting the number of visible characters (as in TextLabel) should be possible from there.

**Comment by seadra** [comment]
OMG, I don't know when but it seems it is already implemented! Thanks!

**Comment by reduz** [comment]
This is already done in Github

**Comment by seadra** [comment]
Yep, I just found out! Thanks!
I closed both issues.
