### ISSUE TITLE
amscripten chromium doesn’t  start

### ISSUE THREAD

**Issue by ni-code** [okamstudio/godot#2466]
I did a quick test with the new html5 export improvements.

The exported game in firefox works apparently fine, but in crhomium it doesn’t load.
the console shows this output:
```
let it go!
[1;31;40mERROR: get_executable_path: [1;37;40mWarning, don't know how to obtain executable path on this OS! Please override this function properly.
[0;31;40m   At: drivers/unix/os_unix.cpp:492.[0;0;37m
has res dir: 
exists engine cfg? 0
loaded engine.cfg
Init OS
Could not create canvas: Web page was not allowed to create a WebGL context.,:(,{"antialias":false,"alpha":false,"depth":true,"stencil":false,"majorVersion":1,"minorVersion":0}
Init Audio
Init VS
```
os: ubuntu 15.04
Firefox 40.0.3
Chromium 44.0.2403.89
nvidia GTS 450 with nv proprietary driver version 346.59
cpu: i5-2500 CPU @ 3.30GHz × 4 
16 GB ram

**Comment by shackra** [comment]
Please edit your report and format properly your output with 3 ` above and under it

**Comment by okamstudio** [comment]
Interesting, but for some reason it seems you have WebGL disabled...

On Sat, Sep 12, 2015 at 7:53 PM, Jorge Araya Navarro <
notifications@github.com> wrote:

> Please edit your report and format properly your output with 3 ` above and
> under it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2466#issuecomment-139826300>.
>



-- 

*OkamStudio*

**Comment by ni-code** [comment]
Yes, that was it, ty.
I've found how turn webgl on here:
http://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser

Tks for the great work.
Closing this issue.

**Comment by okamstudio** [comment]
did your game work on it? also  just by curiosity, how did your webgl end
up disabled?
I only know that it can be disabled under linux for certain drivers that
Firefox doesn't trust..

On Sat, Sep 12, 2015 at 8:58 PM, ni-code <notifications@github.com> wrote:

> Closed #2466 <https://github.com/okamstudio/godot/issues/2466>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2466#event-407947542>.
>



-- 

*OkamStudio*

**Comment by ni-code** [comment]
In firefox the game ran fine out of the box...

In chromium the game works fine. (now)
I had to type:   chrome://flags/
and the enable "Enable experimental canvas features " that is flagged as experimental feature ans was turn off.

I'm not sure, but I this the Canvas feature is turn off by default.

**Comment by ni-code** [comment]
I'm sorry... almost forgot, I also had the "Use hardware acceleration when available" in the advanced setting turn off (So yeah....) . I have chromium installed around 2 years in this machine, but I never use it. I don't know if it was me turning off stuff long ago or if it's the defaults
