### ISSUE TITLE
Unable to compile server export template

### ISSUE THREAD

**Issue by khairul169** [okamstudio/godot#2475]
![screenshot from 2015-09-16 19 25 05](https://cloud.githubusercontent.com/assets/10296472/9904927/d390ed3c-5cab-11e5-9b16-1c2b5c3f8f87.png)

already have the solution, but i don't know how to pull request.. :sob: 

servers/visual/rasterizer_dummy.h:
line 782 add virtual void restore_framebuffer();

servers/visual/rasterizer_dummy.cpp:
line 1951 add:
void RasterizerDummy::restore_framebuffer() {
	return;
}

**Comment by vnen** [comment]
I had this problem as I stated in #2461 but it was fixed by #2467. Do you have an out of date version or was the issue reintroduced?

**Comment by khairul169** [comment]
ah yeah i'm using outdated version :santa:
solved :rabbit:
