### ISSUE TITLE
exporter bone filter option is not implemented

### ISSUE THREAD

**Issue by slapin** [okamstudio/godot#2476]
Exporter bone filter option is not implemented. it is present in list of options,
you can check/uncheck it but it doesn't do anything.

The option name is use_exclude_ctrl_bones

This options hsould either be removed to reduce confusion (easier)
or should be implemented (harder). Probably there is some version of exporter script with that
implemented, but probability is low. Or there is merge error (unlikely).

This option is in exporter script from the start and it was never implemented.
So for cleanness sake this should be removed.

This is another example of how often the exporter script is used (and
how often the bone system is used, among everything in 3D portion of the engine).

Actually the approach of selecting bones by name is not really good as one could check
of the bone is modifier bone and ignore it if it is not. Now script imports all bones being useful or not,
which leads to messed-up bone system if complicated rigs are used with many mechanism bones
(quite common case with Blender if Rigify is used or clothes rig is needed).

**Comment by reduz** [comment]
Oh, it is implemented and works well (we used it a lot at Okam) Only I
believe It's
not documented though.

I think it works lke

@animationamefilter
+bonefilter to add bones
-bonefilter to add bones

**Comment by reduz** [comment]
filter meaning you can write the exact name or use wildcards such as
@*myanim*

**Comment by slapin** [comment]
There is no reference to use_exclude_ctrl_bones anywhere in exporter script
except where this option is defined.

**Comment by slapin** [comment]
@romulox-x ping

**Comment by slapin** [comment]
bump.
Have anybodu understood what this report was about?

**Comment by reduz** [comment]
sorry, just understood what it was about, misunderstood your previous mail
