### ISSUE TITLE
Building export templates help

### ISSUE THREAD

**Issue by carlosfvieira** [okamstudio/godot#2486]
Hi, i'm building godot without any problems on my debian system... also, building export templates but i get errors in this step:

cvieira@cvieira:~/gamedev/godot$ scons platform=x11 tools=no target=release bits=64
scons: Reading SConscript files ...
sh: 1: i586-mingw32msvc-gcc: not found
sh: 1: x86_64-w64-mingw32-gcc: not found
sh: 1: i686-w64-mingw32-gcc: not found
Enabling PulseAudio
scons: done reading SConscript files.
scons: Building targets ...
^Cscons: Build interrupted.
scons: building terminated because of errors.

I'm following all the steps mentioned in https://github.com/okamstudio/godot/wiki/compiling_linux:
(1) godot build: scons platform=x11 tools=no target=release bits=64
(2) export templates build: scons platform=x11 tools=no target=release bits=64

godot engine editor runs Ok...

**Comment by akien-mga** [comment]
Those are not errors, scons just tells you that you don't have mingw cross-compilation tools to build Windows templates. Ideally those checks should be made only when asking to build for the Windows platform though.

You build terminated because of errors because you interrupted it with ^C, not because of the warnings about missing mingw components.

**Comment by akien-mga** [comment]
Ideally such reports should be made on the forums, Facebook or IRC. GitHub issues should be kept for bugs IMO :)

**Comment by carlosfvieira** [comment]
Hmm, ok yes... but i've just installed missing packages and now it runs all ok:

cvieira@cvieira:~/gamedev/godot$ scons platform=x11
scons: Reading SConscript files ...
Enabling PulseAudio
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
cvieira@cvieira:~/gamedev/godot$ scons platform=x11 tools=no target=release bits=64
scons: Reading SConscript files ...
Enabling PulseAudio
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.

=======

My problem is now, where to find export templates that were built... can't find them to put them where they should be...

Can you give a clue?

**Comment by akien-mga** [comment]
> but i've just installed missing packages and now it runs all ok, without any problems

Note that you don't need those packages if you don't intend to build Windows templates. But if you do, you're all set :)

The 64bit release template for X11 is the one named godot.x11.opt.64. See: https://github.com/okamstudio/godot/wiki/compiling_batch_templates
You then need to place it into ~/.godot/templates and rename it as linux_x11_64_release.

**Comment by carlosfvieira** [comment]
Oh, thanks! i thought that it was a flaw (that's why i've created this issue here)... i was looking for linux_x11_64_release file, like it was in the wiki...

Thanks again for your time and explanation! :)

**Comment by Xananax** [comment]
If I understand correctly, you need to:

1 - run
```bash
scons -j8 platform=x11 tools=no target=release bits=64
scons -j8 platform=x11 tools=no target=release_debug bits=64
``` 
2 - Then find the templates in `bin/`. There will be two: 
- `godot.x11.opt.64`
- `godot.x11.opt.debug.64`
Rename respectively to `linux_x11_64_release` and `linux_x11_64_debug`,

3- move them to 
`~/.local/share/godot/templates/godot3.1`

That's it.

Here is a script I wrote today that does everything you need (adjust to your environment):

```bash
#!/usr/bin/env bash

# Compile Godot Script
# Got tired of doing this manually everytime
# This script:
# 1 - Compiles Godot
# 2 - Compiles the templates
# 3 - moves the templates to the right location
# 4 - creates a .desktop shortcut

# This will be the name of the shortcut (you can use this to differenciate between installed copies)
shortcut_name="Godot Engine (self compiled)"

# I keep this file outside of Godot source
godot_dir="$(pwd)/godot"

cd "$godot_dir"
# Making some vars I'll need:
version=`python -c "import version; print(version.short_name+str(version.major)+'.'+str(version.minor))"`
templates_dest="$HOME/.local/share/godot/templates/$version"
binary_location="$godot_dir/bin/godot.x11.tools.64"
user_applications_dir="$HOME/.local/share/applications"
user_icons_dir="$HOME/.local/share/icons"
godot_shortcut_path="$user_applications_dir/org.godotengine.Godot.desktop"
godot_icon_png_path="$user_icons_dir/godot.png"
godot_icon_svg_path="$user_icons_dir/godot.svg"

echo "Compiling Godot ($version)"
scons -j8 platform=x11

echo "Compiling Templates"
scons -j8 platform=x11 tools=no target=release bits=64
scons -j8 platform=x11 tools=no target=release_debug bits=64

echo "Moving Templates to correct location"
test -e "$templates_dest/linux_x11_64_debug" || mkdir -p "$templates_dest" && cp "$godot_dir/bin/godot.x11.opt.debug.64" "$templates_dest/linux_x11_64_debug"
test -e "$templates_dest/linux_x11_64_release" || mkdir -p "$templates_dest" && cp "$godot_dir/bin/godot.x11.opt.64" "$templates_dest/linux_x11_64_release"

echo "Creating a shortcut"

test -e "$godot_shortcut_path" || mkdir -p "$user_applications_dir" && \
  cat "$godot_dir/misc/dist/linux/org.godotengine.Godot.desktop" | sed "s#^Exec=.*#Exec=$binary_location#; s#^Name=.*#Name=$shortcut_name#" > "$godot_shortcut_path"
test -e "$godot_icon_png_path" || mkdir -p "$user_icons_dir" && cp "$godot_dir/icon.png" "$godot_icon_png_path"
test -e "$godot_icon_svg_path" || mkdir -p "$user_icons_dir" && cp "$godot_dir/icon.svg" "$godot_icon_svg_path"

echo "Done!"
```
