### ISSUE TITLE
[Feature Request] Possibility to create scenes with root node from external file

### ISSUE THREAD

**Issue by kubecz3k** [okamstudio/godot#2493]
It's impossible to have node from external file as a root node. In our game we use couple of hacks to bypass that limitation but they create another problems and are generally troublesome. 
Why I think there should be this possibility? Because it's easier to do hierarchical objects structure thanks to this, (just like in object oriented programming, but with scenes). **Maybe I will give real life example here.**

Let's say we will have enemies in our game, quite a lot of them most of them very similar to each other. We could create one scene "BaseEnemy" write a script there, add a lot of inner nodes that are needed for this code to work and setup nice amount of export variables (thanks to them we will be able to modify individual enemies behaviour):
![baseenemy](https://cloud.githubusercontent.com/assets/6129594/9976058/4cb2e910-5ed5-11e5-9918-d482628fa555.png)
*A base enemy scene*

Then for each concrete enemy we cloud just simply load BaseEnemy as root node, setup exported values of Enemy and decorate it with additional specific nodes that are needed like model asset, or additional weapon. 
![concreteenemy](https://cloud.githubusercontent.com/assets/6129594/9976059/516670c6-5ed5-11e5-9250-903b202b4499.png)
*A concrete enemy scene*

Now when we need to change some shared node/logic of our enemy in some way, we don't need to update 10 files separately, we only need to update that single "BaseEnemy.xscn" one :) 

I think that this simple feature would make life of at least some of us a lot easier :) What do you think? 
(Off course I mean "simple" from user side, not sure if this feature would not force another scene format change, but hey! They have changed already between current and 1.1 so it could be good time for this :)

**Comment by reduz** [comment]
The problem is that in Godot the "scene" itself doesn't exist, it's just
nodes. Given there is no scene, it's simply impossible to instance a
foreign scene as the root. Yet I kind of understand the issue, given it's
useful to have a specific type of rootnode such as kinematic or rigid body.
The concept of some sort of scene inheritance was proposed a few times, but
it's not clear what should be inherited and what should not be. Also it's
not clear how if the original scene changes, the one that inherits will not
break.

The scene packer (PackedScene) could have a "original" scene instanced as a
base and then everything else built upon it, the problem is:

1) Recognizing the "difference" between both scenes is an extremely time
consuming task. Saving would take aeons on a large scene.
2) This could be made simpler by making the original nodes read-only, but
then it would not be useful
3) If the original is changed, it would be pretty easy to break all the
derived ones in unexpected ways or not have your changes recognized because
they are overriden by the other scenes.

I can't really think of a practical way to do this, so it would probably
better if we focus on what the problem is instead and try to find a way to
make some sort of tool to make your life easier.

**Comment by okamstudio** [comment]
I will think about it, might not be that difficult after all

On Sat, Sep 19, 2015 at 9:40 AM, Juan Linietsky <notifications@github.com>
wrote:

> The problem is that in Godot the "scene" itself doesn't exist, it's just
> nodes. Given there is no scene, it's simply impossible to instance a
> foreign scene as the root. Yet I kind of understand the issue, given it's
> useful to have a specific type of rootnode such as kinematic or rigid body.
> The concept of some sort of scene inheritance was proposed a few times, but
> it's not clear what should be inherited and what should not be. Also it's
> not clear how if the original scene changes, the one that inherits will not
> break.
>
> The scene packer (PackedScene) could have a "original" scene instanced as a
> base and then everything else built upon it, the problem is:
>
> 1) Recognizing the "difference" between both scenes is an extremely time
> consuming task. Saving would take aeons on a large scene.
> 2) This could be made simpler by making the original nodes read-only, but
> then it would not be useful
> 3) If the original is changed, it would be pretty easy to break all the
> derived ones in unexpected ways or not have your changes recognized because
> they are overriden by the other scenes.
>
> I can't really think of a practical way to do this, so it would probably
> better if we focus on what the problem is instead and try to find a way to
> make some sort of tool to make your life easier.
>
>
>
>
> On Sat, Sep 19, 2015 at 8:53 AM, kubecz3k <notifications@github.com>
> wrote:
>
> > It's impossible to have node from external file as a root node. In our
> > game we use couple of hacks to bypass that limitation but they create
> > another problems and are generally troublesome.
> > Why I think there should be this possibility? Because it's easier to do
> > hierarchical objects structure thanks to this, (just like in object
> > oriented programming, but with scenes). *Maybe I will give real life
> > example here.*
> >
> > Let's say we will have enemies in our game, quite a lot of them most of
> > them very similar to each other. We could create one scene "BaseEnemy"
> > write a script there, add a lot of inner nodes that are needed for this
> > code to work and setup nice amount of export variables (thanks to them we
> > will be able to modify individual enemies behaviour):
> > [image: baseenemy]
> > <
> https://cloud.githubusercontent.com/assets/6129594/9976058/4cb2e910-5ed5-11e5-9918-d482628fa555.png
> >
> > *A base enemy scene*
> >
> > Then for each concrete enemy we cloud just simply load BaseEnemy as root
> > node, setup exported values of Enemy and decorate it with additional
> > specific nodes that are needed like model asset, or additional weapon.
> > [image: concreteenemy]
> > <
> https://cloud.githubusercontent.com/assets/6129594/9976059/516670c6-5ed5-11e5-9250-903b202b4499.png
> >
> > *A concrete enemy*
> >
> > Now when we need to change some shared node/logic of our enemy in some
> > way, we don't need to update 10 files separately, we only need to update
> > that single "BaseEnemy.xscn" one :)
> >
> > I think that this simple feature would make life of at least some of us a
> > lot easier :) What do you think?
> > (Off course I mean "simple" from user side, not sure if this feature
> would
> > not force another scene format change, but hey! They have changed already
> > between current and 1.1 so it could be good time for this :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/issues/2493>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2493#issuecomment-141660728>.
>



-- 

*OkamStudio*

**Comment by bojidar-bg** [comment]
:+1: Just like you can add custom nodes to instanced scenes... Maybe there can be some "fake-root"?

**Comment by reduz** [comment]
next push will have all this, including scene inheritance. I hope you test
it well :P

**Comment by bojidar-bg** [comment]
@reduz Nicee.... Can't wait to compile :smile:

**Comment by kubecz3k** [comment]
With new scene system in current main I think this one can be closed now. Have test it and it seems to work well :). At this point I think new bug-reports should be made in case of any problems.
