### ISSUE TITLE
[Error] Compiling from source

### ISSUE THREAD

**Issue by sezit** [okamstudio/godot#2500]
When compiling in VS 2013 gives an error message in "rectangle_shape_2d.cpp(62) RectangleShape2D::get_rect must return a value.

Windows
P.S. Mb only i have this error

**Comment by neikeq** [comment]
I don't have any compilation error, but get_rect should actually return something. Looks like Juan forgot to add return keyword here: https://github.com/okamstudio/godot/commit/83d9a692be648668b5b363f2424c619e15639843#diff-26b588e71aedf4d918e0b73bb3e5b76dR60

**Comment by sezit** [comment]
Yep. I added by hand and everything works.
