### ISSUE TITLE
Doctool flips &gt;/&lt; at each run

### ISSUE THREAD

**Issue by akien-mga** [okamstudio/godot#2511]
In doc/base/classes.xml, we have a string with a ">" symbol, XML escaped as &gt;:
```
Add a custom filter. Filter format is: "mask ; description", example (C++): dialog-&gt;add_filter("*.png ; PNG Images");
```

However, each time ```godot -doctool doc/base/classes.xml```, it flips the sign and replaces &gt; by &lt;, or &lt; by &gt;, so we get:
```
diff --git a/doc/base/classes.xml b/doc/base/classes.xml
index 74cacb0..7a5e908 100644
--- a/doc/base/classes.xml
+++ b/doc/base/classes.xml
@@ -10346,7 +10346,7 @@
                        <argument index="0" name="filter" type="String">
                        </argument>
                        <description>
-                       Add a custom filter. Filter format is: "mask ; description", example (C++): dialog-&gt;add_filter("*.png ; PNG Images");
+                       Add a custom filter. Filter format is: "mask ; description", example (C++): dialog-&lt;add_filter("*.png ; PNG Images");
                        </description>
                </method>
                <method name="get_current_dir" qualifiers="const">
```

When executing doctool again, the "flip" is reverted.

**Comment by reduz** [comment]
oops, check the following functions in ustring.cpp

String String::xml_escape(bool p_escape_quotes) const {


and


static _FORCE_INLINE_ int _xml_unescape(const CharType *p_src,int
p_src_len,CharType *p_dst) {


they are escaping < and > backwards, feel free to send a PR (my tree is
quite broken atm)

**Comment by akien-mga** [comment]
I confirm the fix :)
