### ISSUE TITLE
Tooltip help shows badly parsed newlines

### ISSUE THREAD

**Issue by akien-mga** [okamstudio/godot#2516]
The tooltip help for the Y sort function recently documented is as shown here:
![contextual-help](https://cloud.githubusercontent.com/assets/4701338/10059062/0bf270cc-6249-11e5-9623-fa3fe5ba119d.jpg)

The corresponding description is however:
```
		<method name="set_y_sort_mode">
			<argument index="0" name="enable" type="bool">
			</argument>
			<description>
			Set the Y sort mode. Enabled Y sort mode means that children of the tilemap will be drawn in the order defined by their Y coordinate.
			A tile with a higher Y coordinate will therefore be drawn later, potentially covering up the tile(s) above it if its sprite is higher than its cell size.
			</description>
		</method>
```
(with tabs instead of spaces)

So there is a newline before "A tile with a higher...", but it's somehow last when parsing the XML data to generate the tooltip.

**Comment by bojidar-bg** [comment]
I suspect the bug might be somewhere here... must check first :D https://github.com/okamstudio/godot/blob/ca11b2fa4b87642d6e1bbd000bfa74e4922b390b/core/ustring.cpp#L3051

**Comment by bojidar-bg** [comment]
Ok, [here](https://jsbin.com/vogokanehe/edit?html,js,console,output) is a JSBin showcasing the issue (who said we can't use JS? :smile: )
