### ISSUE TITLE
ShaderGraph dont have if statement.

### ISSUE THREAD

**Issue by sezit** [okamstudio/godot#2530]
I cant find in shader graph if statement. It's missing or just disabled because that is rarely used?

**Comment by bojidar-bg** [comment]
@sezit ~ I don't think shaders have an IF statement at all.... The best you can do is use an approximation of the [Heaviside step function](https://en.wikipedia.org/wiki/Heaviside_step_function).

**Comment by sezit** [comment]
Thank, i new in shaders.

**Comment by sezit** [comment]
Thank, i new in shaders.
