### ISSUE TITLE
label no longer clipped by scroll container

### ISSUE THREAD

**Issue by romulox-x** [okamstudio/godot#2571]
Put a label inside a scroll container, and it won't be clipped by the scroll container's edges.  Sprites, for example, are still clipped.  Strangely, when opening an existing project with multiple labels as descendants on the scroll container, only some of the labels behave this way.  Others are clipped correctly.

Example project:
https://copy.com/jtp0XccvYj8qcfNa

**Comment by leezh** [comment]
romulox-x and I narrowed down the issue over IRC.

Seems like the issue is that when child nodes use clipping, it overrides the parent's clipping box. This also happens when a scroll container is placed inside another scroll container.
