### ISSUE TITLE
Changing the properties of an instanced scene, from the editor

### ISSUE THREAD

**Issue by seadra** [okamstudio/godot#2582]
Let's say I have am Item scene, which contains a Node2D as the root, and a Sprite (with multiple frames, from a spritesheet) as a child, among other stuff.
And I make multiple instances of Item.

Can I set the Frame property of different instances separately from the editor, or do I have to call get_node("ItemN/Sprite").set_frame(n) for each instance of Item using script?

If the answer is "yes, setting from the editor should work", well, it only looks like it's working inside the editor but when I run the game, it doesn't.

If the answer is no, then it shouldn't show different frames inside the editor too (which is quite misleading), right?

Either way, there is a problem.

**Comment by reduz** [comment]
This ability is currently being worked on, but the plan is to fully support
editing the instanced scene and keeping the changes. It will likey be
pushed to github head or a testing branch next week

**Comment by seadra** [comment]
Oh I see. That's a cool feature!

**Comment by seadra** [comment]
Any news?

**Comment by reduz** [comment]
this is already commited and on github, give it a try.. it should work.

**Comment by seadra** [comment]
It *is* working, awesome! Thanks!
