### ISSUE TITLE
AnimationPlayer not working right fo ranimations that last less than 1 second

### ISSUE THREAD

**Issue by vichug** [okamstudio/godot#2590]
it's all in the title
When i tried that, the animation would simply not play. If i extended the animation time to be more than 1 second, it worked (even if all the animation points were before 1 second).

**Comment by kubecz3k** [comment]
Hello. 
I tried to reproduce your bug on 1.1 as well as nightly from 3.10.2015 without luck. Everything works fine for me... Probably simple sample project would be helpful.

**Comment by vichug** [comment]
i can't... can't reproduce anymore..... i worked this around somehow, it must have been something else... sprry for the noise, i'll reopen if i stumble upon it again with reproducible steps.
