### ISSUE TITLE
[Bug] Array in Singletons (Autoload)

### ISSUE THREAD

**Issue by sezit** [okamstudio/godot#2593]
I'ts very strange. In autoload i have array, and when assign its in scene and if i clear local array, its remove it in autoload too! Here screenshot.
![default](https://cloud.githubusercontent.com/assets/6241034/10412433/57cb302c-6f8e-11e5-9963-ac23fb8f4498.PNG)

**Comment by vnen** [comment]
Isn't this intended behavior since arrays are passed by reference?

**Comment by volzhs** [comment]
It's not a bug like @vnen said

**Comment by sezit** [comment]
I doubt, that why i delete it and add again. Its mean array passed by reference, and number variable just copy it? Thx! I dont know this. 
![default](https://cloud.githubusercontent.com/assets/6241034/10416400/ac1ee7aa-701e-11e5-94a6-a79f45671270.PNG)
