### ISSUE TITLE
[2.0 Alpha] [bug] [New scene system] Can't delete/modify nodes in previously saved scene

### ISSUE THREAD

**Issue by kubecz3k** [okamstudio/godot#2610]
Compilation from Oct 17, 2015 (17a90ddc0824bb51b5ea707f5d4d11aed301f91d commit)
I have 2 scenes, "Actor" and "Enemy". Enemy was created with "New Inherited Scene" option, with the base choosen as Actor. In enemy scene I added another scene with model (mesh/asset). 
Now when I open Actor scene I cant delete it's nodes.

Quick steps to reproduce problem:
1. Open "Actor.xscn" from sample project
2. Try to delete CollisionShape node.

Sample project: https://dl.dropboxusercontent.com/u/168251/godot/some/issues/NewSceneSystem2.7z

**UPDATE:**
Just like @WriterOfAlicrow noticed scene inheretance is not needed to reproduce this. Just save your scene reopen it and you will not be able to delete it's nodes. (changed title a little to reflect this)

**Comment by WriterOfAlicrow** [comment]
This is happening to me whenever I close and re-open a scene (no inheritance necessary). I try to delete an object from the scene, and it tells me "Can't operate on nodes the current scene inherits from!"

If saved as xml, the scene file contains a string "editable_instances", followed by an empty array. I think Godot is supposed to use that array to keep track of what's editable, but it doesn't save it properly, so when it loads it, it thinks nothing is editable.

**Comment by GalanCM** [comment]
This seems to still be a problem, at least on OS X. I have the latest code from master, and I still can't edit nodes from an opened scene, but new nodes work.

**Comment by reduz** [comment]
this is weird, can you record a small video or post a description about the
issue?
