### ISSUE TITLE
Reset property button displayed for all non-default values

### ISSUE THREAD

**Issue by eska014** [okamstudio/godot#2614]
When opening an existing scene, properties of nodes that are not instanced (and are not children of instanced nodes) that have a non-default value display the reset property button. Clicking it has no effect, but it won't disappear either.

**Comment by eska014** [comment]
To reproduce:
 1. Create a new scene
 2. Add Node2D
 3. alter `transform/pos`
 4. Save & close
 5. Reopen
 6. Check `transform/pos` property

Seems to concern all properties that are non-default as per `PROPERTY_USAGE_STORE_IF_NONONE` and `PROPERTY_USAGE_STORE_IF_NONZERO`

**Comment by eska014** [comment]
This issue persists for the following types of properties:
 -  properties of instanced nodes and their children
 -  properties of non-base nodes in inherited scenes

Not sure if it's expected for the first, but the latter seems incorrect.

**Comment by reduz** [comment]
Is that not intended?

**Comment by okamstudio** [comment]
I think this is expected behavior, if something is changed from original
scene, revert appears

On Sat, Oct 17, 2015 at 8:13 PM, Juan Linietsky <notifications@github.com>
wrote:

> Is that not intended?
> On Oct 17, 2015 7:34 PM, "eska014" <notifications@github.com> wrote:
>
> > This issue persists for the following types of properties:
> >
> > - properties of instanced nodes and their children
> > - properties of non-base nodes in inherited scenes
> >
> > Not sure if it's expected for the first, but the latter seems incorrect.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/okamstudio/godot/issues/2614#issuecomment-148956693
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2614#issuecomment-148959684>.
>



-- 

*OkamStudio*

**Comment by eska014** [comment]
This example should reproduce what I mean:
 1. Create a new scene (not inherited)
 2. Add 1 Node
 3. Save & close
 4. Scene->New Inherited Scene
 5. Choose just created scene as base
 6. Add a Control node as child to the root in this new Inherited scene
 7. Observe that `margin/right`, `margin/bottom`, `rect/size`, `size_flags/horizontal`, `size_flags/vertical` of the new Control node all have the button without any functionality.

I'm not sure if this intended. I don't think properties of nodes added in an inherited scene should have a revert button while editing that same inherited scene (since there is nothing to revert to).
