### ISSUE TITLE
[2.0 Alpha] [bug] [New scene system] Changing name of node that is a part of the base scene duplicate this node instead

### ISSUE THREAD

**Issue by kubecz3k** [okamstudio/godot#2615]
If you change name of the node that is part of the base scene, save inherited scene close it and reopen then this node will be duplicated (with new name). I know that there was no plans for allowing to change these names, but this behaviour don't seems to be expected as well.
Also don't know if call it a bug or a feature (since that might be handy) but for sure it feels like not planned behaviour.

To recreate:
1. Create scene from option "new inherited scene"
2. Change name of one of the nodes from base scene
3. Save and close scene
4. Reopen closed scene

Quick 40s wid that show this process: https://youtu.be/zqDUXy39d80

**Comment by reduz** [comment]
uh.. it should not allow you to rename.. i totally missed that...
