### ISSUE TITLE
[Editor] Buttons for node edition suddenly disabled for all loaded scenes, except new nodes.

### ISSUE THREAD

**Issue by hetdegon** [okamstudio/godot#2633]
After updating to current master at the time of writing (0a02c28b2be8e8271d5f3ffb95a4b09f91c3bd32), I loaded a scene in .xscn format, and noticed I couldn't delete/reparent/move nodes anymore, the interface buttons appear disabled.
![snapshot7](https://cloud.githubusercontent.com/assets/323651/10569485/f3fd9a22-7626-11e5-9c77-97d1c886c4ce.png)

Deleting the nodes using the Del key works, only the interface seems disabled.

When adding a new node to that scene, the buttons activate, so it seems to be just a problem with the user interface. I don't know the exact commit that broke the buttons, but seems it was since 1-2 days ago.

**Comment by ni-code** [comment]
I noticed that if we rename a node with the problem, the delete/reparent/move buttons become active.
If we renaming it back to its "original" name, the buttons will become inactive again.

**Comment by reduz** [comment]
was this not fixed?

**Comment by reduz** [comment]
oh i think i pushed a tentative fix, let me know if this works for you

**Comment by kubecz3k** [comment]
Checked with 35959f9c5a314effc9a442931baccec2408b8ece commit. From my tests it looks like it's fixed :+1:

**Comment by ni-code** [comment]
yup, just compiled and it is working fine. ty

**Comment by MarianoGnu** [comment]
remember to close the issue :)

**Comment by hetdegon** [comment]
Seems it's fixed. Going to close the issue, then.
