### ISSUE TITLE
Godot crashes when I click on "X" scene close button

### ISSUE THREAD

**Issue by ricpelo** [okamstudio/godot#2634]
Using latest git HEAD (commit 0a02c28).

Steps to reproduce:

1. Open one or several scenes. Each scene opens in a tab.
2. Click on an "X" close button to close a scene.

Actual behavior: Godot crashes and close it fully.

Expected behavior: Only the selected scene closes.

**Comment by akien-mga** [comment]
Duplicate of 2623.

**Comment by ricpelo** [comment]
You're right! Sorry.
