### ISSUE TITLE
[BUG] OS.get_date().month returns worng month 

### ISSUE THREAD

**Issue by karolgotowala** [okamstudio/godot#2643]
Win 8.1
Both 1.1 and alpha 2.0

When OS.get_date().month called returns the wrong month, the month returned is always bigger by 1 from actual one

**Comment by vnen** [comment]
I believe months goes from 1 to 12, not from 0 to 11, so this is intended behavior. See #2365, which enforces this behavior on Linux too.

**Comment by karolgotowala** [comment]
Thank you for quick response. Please add mentioned fix  #2365 to android as well because android has 0-11 numeration too.
