### ISSUE TITLE
[Error] Compiling on Windows produces TypeError

### ISSUE THREAD

**Issue by Tybobobo** [okamstudio/godot#2666]
While I won't disregard the possibility of user error on my part; I believe there *might* be an issue with the latest godot build.

Following the guide in the wiki ([here](https://github.com/okamstudio/godot/wiki/compiling_windows)), I have installed python 2.7 and latest version of scones. 

I have cloned the repository and attempted to compile using scons. I get an error;
([screenshot here](http://i.imgur.com/nzq1TlY.png))

#### Administrator: Developer Command Prompt for VS2015:
**C:\godot>scons platform=windows
scons: Reading SConscript files ...
TypeError: cannot concatenate 'str' and 'NoneType' objects:
  File "C:\godot\SConstruct", line 230:
    detect.configure(env)
  File "./platform/windows\detect.py", line 221:
    env.Append(CCFLAGS=['/I'+os.getenv("WindowsSdkDir")+"/Include"])**

Is this a common problem? I have tried searching for it, but could not find a solution. 
Could it possibly be a version problem with VS? I am using Visual Studio Community 2015.

**Comment by vnen** [comment]
The guide you cited does say it doesn't work with VS2015. It seems that VS2012 is also problematic. You can download VS2013 (even the Community version) which is known to work, or help fix the issue, if you can.

**Comment by Tybobobo** [comment]
Ah, I must have missed it. Thank you.

**Comment by jduhls** [comment]
In case someone else runs into this: "WindowsSdkDir" env variable has not been set. I followed instructions in this github comment (you have to create a new C++ project in VS2015 to install for the first time): https://github.com/nodejs/node-gyp/issues/694#issuecomment-145230097

I am godot 2.0, python 2.7, VS2015 on Windows 10

**Comment by toger5** [comment]
I tried compiling godot only with thw
E microsoft c++ build tools.
I have the same problem. 
`env.Append(CCFLAGS=['/I'+os.getenv("WindowsSdkDir")+"/Include"])`
I installed the build tools with the windows 10 sdk. Should i have used the windows 8.1 ones?

**Comment by vnen** [comment]
@toger5 The problem is that `WindowsSdkDir` env var is not defined. I never used the build tools, so I'm not sure what environment it provides. This should be fixed by setting the `WindowsSdkDir` yourself, or finding if there's another one to replace it.

**Comment by toger5** [comment]
Ty @vnen
Tmfor anyone else runninginto that issue,there is a file called vsvars32.bat in the common7 folder.
It swts up the path and env vars correctly

**Comment by akien-mga** [comment]
You really need to fix your spellcheck @toger5 :)
