### ISSUE TITLE
Automatic Y-sorting for sprites

### ISSUE THREAD

**Issue by seadra** [okamstudio/godot#2675]
That's necessary when your sprites are of 2 tiles height, but only the bottom tile has collision. The sprites with lower Y should be drawn first.
Something like this:
![phantasystar4-3](https://cloud.githubusercontent.com/assets/9574367/10716674/5451e5a4-7b0e-11e5-878b-77b6d533a13a.jpg)

**Comment by seadra** [comment]
Related discussion in #405

**Comment by seadra** [comment]
To clarify, I did try adding adding two sprites under a YSort (I don't know what it exactly does though, it's not documented yet) with Sort set to enabled, but it had no effect.

**Comment by reduz** [comment]
Put sprites as children of tilemap and enable sorting

**Comment by seadra** [comment]
Tried that too, not working.

**Comment by seadra** [comment]
BTW, I have KineticBody2D's, which have a sprite as a child.

To clear on what I just tried:

* I have a tilemap with y-sort enabled. I tried moving two kinetic bodies under it; not working.
* I have a tilemap with y-sort enabled. Added a YSort as a child (with sorting enable), and moved two kinetic bodies under it; still not working.

**Comment by seadra** [comment]
It's so bizarre. I've been using reparent so far.
I tried removing & re-adding the scenes containing the kinematic bodies, and it worked.
