### ISSUE TITLE
mingw cross compilation fails

### ISSUE THREAD

**Issue by seadra** [okamstudio/godot#2683]
```
i686-w64-mingw32-g++ -o bin/godot.windows.tools.32.exe -static -static-libgcc -static-libstdc++ -g platform/windows/godot_win.windows.tools.32.o platform/windows/context_gl_win.windows.tools.32.o platform/windows/os_windows.windows.tools.32.o platform/windows/ctxgl_procaddr.windows.tools.32.o platform/windows/key_mapping_win.windows.tools.32.o platform/windows/tcp_server_winsock.windows.tools.32.o platform/windows/packet_peer_udp_winsock.windows.tools.32.o platform/windows/stream_peer_winsock.windows.tools.32.o main/libmain.windows.tools.32.a modules/libmodules.windows.tools.32.a bin/tests/libtests.windows.tools.32.a drivers/libdrivers.windows.tools.32.a drivers/libdrivers0.windows.tools.32.a drivers/libdrivers1.windows.tools.32.a drivers/libdrivers2.windows.tools.32.a drivers/libdrivers3.windows.tools.32.a tools/libtool.windows.tools.32.a tools/freetype/libfreetype_builtin2.windows.tools.32.a tools/freetype/libfreetype_builtin1.windows.tools.32.a scene/libscene.windows.tools.32.a servers/libservers.windows.tools.32.a core/libcore.windows.tools.32.a -lmingw32 -lopengl32 -ldsound -lole32 -ld3d9 -lwinmm -lgdi32 -liphlpapi -lshlwapi -lwsock32 -lkernel32 -lpthread -ldl -lws2_32
/usr/lib/gcc/i686-w64-mingw32/5.2.0/../../../../i686-w64-mingw32/bin/ld: cannot find -ldl
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.windows.tools.32.exe] Error 1
scons: building terminated because of errors.
```

On 64-bit Linux. Getting a similar error for `platform=windows bits=64`.

**Comment by phobos-tro** [comment]
Hi seadra,

both works fine for me (32 + 64 bits). So i cannot confirm your issue.
Are you using the latest git version?

Would you mind to provide the following information:

`uname -a`

and

`git log -1 --format="%cd"`

**Comment by seadra** [comment]
I'm on 64-bit Arch Linux, and everything (including mingw-w64 packages) is up-to-date. I've been compiling just fine until recently.
And I'm at the tip of git too, the latest commit I have is bd736e

**Comment by vnen** [comment]
I've built it fine on my 64-bit Arch Linux machine, the same commit and just ran `pacman -Syu` to update everything. However, here it's not linking with the last 3 libraries that shows on your command: `-lpthread -ldl -lws2_32`. Are you using some other flags for scons?

**Comment by seadra** [comment]
I ran `pacman -Syu` this morning too.
That's odd.
Nope, I'm running `scons platform=windows bits=64` or `scons platform=windows bits=32`.

**Comment by seadra** [comment]
Ah, I found the problem. It's the 3rd party gdnet module.
Sorry!

**Comment by seadra** [comment]
`-dl` was due to gdsqlite though.
