### ISSUE TITLE
Background color doesn't change on Help page in editor

### ISSUE THREAD

**Issue by xxblx** [okamstudio/godot#332]
Hello. 
Godot editor support customization of editor's color scheme. It is really cool feature. 
I changed color scheme from dark background with light font to light background with dark font. Check the screen please: http://itmages.com/image/view/1638062/a64dfcf5

But when you change color scheme of script editor it strange work on Help page. 
Help page still uses default background color, but font color it uses from script editor. Check this screenshot please: http://itmages.com/image/view/1638064/11bfe00e

So. 
Either Help page need use all color setting from script editor (Help page need to use script editor's background color), or Help page need use always default colors. 
Else Help page become to be unreadable if you prefer to use light background in script editor. 

I understand that you have really much important problems but this issue do work with Godot for people with eye problems (like me) really hard. 
It is not urgently. Just look possible solutions in a future please. 

Thanks. 
Oleg.

**Comment by UsernameIsAReservedWord** [comment]
the auto-completion box is also affected.

**Comment by UsernameIsAReservedWord** [comment]
@xxblx : if you're still interested, i have published a fix for this issue. PR #1580.
