### ISSUE TITLE
Error in "File" with "READ_WRITE" or "open_encrypted_with_pass"

### ISSUE THREAD

**Issue by amagnoni** [okamstudio/godot#378]
when i try to get a variable from a file with "File.READ_WRITE":
f.get_var()

ERROR: decode_variant: Condition ' len<4 ' is true. returned: ERR_INVALID_DATA
   At: core/io/marshalls.cpp:39.
ERROR: get_var: Condition ' err!=OK ' is true. returned: Variant()
   At: core/bind/core_bind.cpp:1148.

project example:
http://s000.tinyupload.com/index.php?file_id=03843245076948565692

if i use "File.READ" it works normal!

and using:
f.open_encrypted_with_pass(save_file,File.READ,OS.get_unique_ID())

project example:
http://s000.tinyupload.com/index.php?file_id=03194428085999592865

im getting this error on ubuntu:

ERROR: get_unique_ID: Method/Function Failed, returning: ""
   At: core/os/os.cpp:433.

**Comment by Spooner** [comment]
I have this problem too - if I open a file in READ_WRITE it is always truncated (for you, this means the file is length=0, so you can't read 4 bytes from it)

My usage, however, is to fake an APPEND mode with:
    var file = File.new()
    file.open("log.txt", File.READ_WRITE)
    file.seek_end()
    # Now should be able to append...

Since the file is empty on opening (truncated), this doesn't work so well!

**Comment by Spooner** [comment]
Oh, no, "wb+" does truncate any file if it already exists! We really want "rb+" for either of our usages (obviously I would be better using "ab" mode, but "rb+" would allow me to do what I need).

@reduz Do you actually want it to be wb+ or can it be rw+ which is considerably more useful (you may have a use case that needs wb+, of course)?

**Comment by okamstudio** [comment]
which one opens the file and allows to change and append? I honestly never
used it so it might be broken. if it's rb+ feel free to send a PR with that
on both FileAccessWindows and FileAccessUnix

On Mon, Feb 16, 2015 at 5:33 PM, Bil Bas <notifications@github.com> wrote:

> Oh, no, "wb+" does truncate any file if it already exists! We really want
> "rb+" for either of our usages (obviously I would be better using "ab"
> mode, but "rb+" would allow me to do what I need).
>
> @reduz <https://github.com/reduz> Do you actually want it to be wb+ or
> can it be rw+ which is considerably more useful (you may have a use case
> that needs wb+, of course)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/378#issuecomment-74568342>.
>



-- 

*OkamStudio*

**Comment by Spooner** [comment]
http://www.cplusplus.com/reference/cstdio/fopen/

rb+ is open for reading and writing (file must already exist).
wb+ is open for reading and writing (file truncated if it already exists; created if it doesn't exist).

I think a PR is definitely in order! Thanks for the feedback!

**Comment by reduz** [comment]
oh rb+ is then, thanks to you!

**Comment by Spooner** [comment]
I tested it with my logger code and it works nicely now.
