### ISSUE TITLE
MeshDataTool crashes on a newly generated surface

### ISSUE THREAD

**Issue by TheoXD** [okamstudio/godot#457]
I was trying to modify a plane I generated using SurfaceTool (to make it larger for instance) and it kinda works, but is very unpredictable. It may crash, or it may just draw one triangle only. Attach it to a meshinstance, add new material using inspector and watch the result. It will show a triangle first time you run it, but if you restart the game - it will crash.

Here's the code:
```python
extends MeshInstance

export(FixedMaterial) var material = null

func _ready():
	var up = Vector3(0, 1, 0)
	
	var surface = SurfaceTool.new()
	surface.begin(VisualServer.PRIMITIVE_TRIANGLE_STRIP)
	
	if(material):
		surface.set_material(material)

	#Generate a surface
	surface.add_vertex(Vector3(1, 0, -1))
	surface.add_uv(Vector2(1, 0))
	surface.add_normal(up)

	surface.add_vertex(Vector3(1, 0, 1))
	surface.add_uv(Vector2(1, 1))
	surface.add_normal(up)

	surface.add_vertex(Vector3(-1, 0, -1))
	surface.add_uv(Vector2(0, 0))
	surface.add_normal(up)

	surface.add_vertex(Vector3(-1, 0, 1))
	surface.add_uv(Vector2(0, 1))
	surface.add_normal(up)

	var mesh = surface.commit()


	#Modify the surface
	var datatool = MeshDataTool.new()
	datatool.create_from_surface(mesh, 0)
	datatool.set_vertex(0, datatool.get_vertex(0) * 10)
	datatool.set_vertex(1, datatool.get_vertex(1) * 10)
	datatool.set_vertex(2, datatool.get_vertex(2) * 10)
	datatool.set_vertex(3, datatool.get_vertex(3) * 10)
	print(datatool.get_vertex_count())
	
	mesh.surface_remove(0) #Remove the old one
	datatool.commit_to_surface(mesh)

	set_mesh(mesh)
```

**Comment by TheoXD** [comment]
I remember this being fixed, doesn't crash anymore

**Comment by toger5** [comment]
I copied your code to try it out too.
But it didn´t work. There was no problem with the SurfaceTool but I couldn´t  use the MeshDataTool.
In this line:
```python
datatool.create_from_surface(mesh, 0)
```
occured an error.
I went to the source code and had a look:
In line 47:
```c++
ERR_FAIL_COND_V(p_mesh->surface_get_primitive_type(p_surface)!=Mesh::PRIMITIVE_TRIANGLES,ERR_INVALID_PARAMETER);
```
I found the information that the: ```python datatool.create_from_surface(mesh, 0) ``` function only works when the mesh type is: ``` PRIMITIVE_TRIANGLES ``` 

I changed line 9:
```python
surface.begin(VisualServer.PRIMITIVE_TRIANGLE_STRIP)
``` 
to:
```python
 surface.begin(VisualServer.PRIMITIVE_TRIANGLES)
``` 
and it worked.
Maybe anyody else has that problem so i wanted to post it. I havent found that information in any tutorial/documentation.
