### ISSUE TITLE
Assigning a new value to a euler after fetching it crashes Godot

### ISSUE THREAD

**Issue by Ace-Dragon** [okamstudio/godot#978]
So let's say you have this in your code

	var trans = get_global_transform()
	var base = trans.basis
	var euler = base.get_euler()
	euler[2] = 1

The addition of the last line will cause the game to crash 100 percent of the time, the idea was that I would use that to directly set an object's global rotation, if only the code could work.

If you can take a look at it, that would be good.

Thanks.

**Comment by reduz** [comment]
this was a bug, fixed it.
