### ISSUE TITLE
canvas_draw_polygon cannot work under android platform

### ISSUE THREAD

**Issue by sanikoyes** [okamstudio/godot#991]
I was written spine support for godog eninge, codes is fully write completed, and it's work correct under windows platform, but can't draw anything under android platform, this is a problem in RasterizerGLES2::canvas_draw_polygon API.

then i writed some test scripts:

	class Shape extends Node2D:
		var vertices
	
		func _init(vertices):
			self.vertices = vertices
		
		func _draw():
			draw_colored_polygon(self.vertices, Color(0,0.6,0.7,0.5))
			draw_circle(Vector2(0, 0), 100, Color(0, 1, 0, 0.5))

these code draw correct under windows platform, but cannot draw anything under android platform...

![image](https://cloud.githubusercontent.com/assets/6880378/5486748/26745d9c-86e5-11e4-8cbc-b62bb91490ad.png)

How to fix this problem??? please help me.

**Comment by reduz** [comment]
ok i think this should be fixed, please test

**Comment by wbasile** [comment]
I confirm this bug on a (very cheap) Samsung Galaxy Trend GT-S7580 running Android 4.2.2
