### ISSUE TITLE
[Documentation] Instructions for building for Android contradictory.

### ISSUE THREAD

**Issue by Evi1M4chine** [okamstudio/godot#996]
Hi,

The instructions on [compiling for Android](https://github.com/okamstudio/godot/wiki/compiling_android) have some confusing/wrong information:

––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

    C:\godot> copy bin/libgodot_android.debug.so platform/android/java/libs/armeabi/libgodot_android.so
    
    alternatively if you are under unix you can symlink:
    
    user@host:~/godot$ ln -s platform/android/libgodot_android.debug.so platform/android/java/libs/armeabi/libgodot_android.so

Should probably read:

    C:\godot> copy platform/android/bin/libgodot.android.debug.so platform/android/java/libs/armeabi/libgodot_android.so
    
    alternatively if you are under unix you can symlink:
    
    user@host:~/godot$ ln -s platform/android/bin/libgodot.android.debug.so platform/android/java/libs/armeabi/libgodot_android.so

Changes:
* The source file is actually called `libgodot.android.debug.so`, with a dot instead of an underscore.
* In both cases it is probably found in `platform/android/bin/`, or `bin/`, not `platform/android/`. Or does it differ, depending on the OS?

––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

But the section after that, about building the templates, contradicts the whole thing:

    C:\godot> cp bin/libgodot_android.opt.debug.so platform/android/java/libs/armeabi

and

    C:\godot> cp bin/libgodot_android.opt.so platform/android/java/libs/armeabi

Apart from also using `bin/` and the underscore in the source path, in both cases, there is the additional `opt` or `debug` part, and the target path does not rename it. I wonder:
* Does this mean that there are now three files in the `armeabi` directory?
* If this creates the templates, then what does the above section (with the `libgodot_android.so`) create?
* If I run `ant debug`, which of those three libraries does it use? What if I run `ant release`?
* Which of those libraries will it include in the template APKs? All three? (My self-generated templates are huge, compared to the templates from your website.)
* What did I do wrong, to have the Pong example result in ~180MB (!!) when installed on Android.

Because I just tried to write a small build script to rebuild everything after a git pull, and I can’t tell what’s the correct procedure.

If you could improve that wiki page, I would be soo happy. :)

**Comment by reduz** [comment]
ok changed the page with new stuff. should be clearer i hope
